# Netdata — real-time metrics, zero-config, self-hosted
# CNCF member, MIT-licensed community edition
# The Observatory: node-level host metrics → Grafana via Prometheus exporter

[global]
  hostname = trancendos-production
  history = 3600
  update every = 1
  memory mode = ram

[web]
  bind to = 0.0.0.0:19999
  allow connections from = localhost 127.0.0.1 10.* 172.* 192.168.*

[plugins]
  proc = yes
  sys = yes
  diskspace = yes
  tc = no
  cgroups = yes
  python.d = yes
  go.d = yes

[logs]
  error log = /dev/stderr
  access log = /dev/null
  debug log = /dev/null
