version: "2"

run:
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  settings:
    govet:
      enable-all: false
    errcheck:
      check-type-assertions: false
      check-blank: false
