"""Emit PostgreSQL DDL from the domain model: schemas, tables, keys, RLS.

This is the reason to have a domain model rather than a diagram. One model
produces the schema, the foreign keys and the row-level security policies, so
"who may read this column" is answered in the same place as "what is this
column" -- instead of in a permissions matrix that drifts from the tables it
describes.

Three choices worth stating, because each prevents a specific failure:

* **Schema per module, not database per module.** `the_citadel.location`,
  `the_ice_box.container`. Cross-schema joins work, one backup covers everything,
  one connection pool. A database per Location would recreate the 96-file SQLite
  problem with a heavier engine.

* **RLS is enabled with a default deny.** PostgreSQL's own rule: a table with row
  security enabled and no policy returns nothing. Generating the ENABLE without
  generating policies therefore fails closed, which is the safe direction for a
  generator to be incomplete in.

* **Calculated attributes get no column.** Mendix's stored/calculated split
  carried through, so a value derived at read time cannot silently become a
  stale copy in a row.
"""

from __future__ import annotations

from typing import List

from src.domain.model import Access, DomainModel, Entity

HEADER = """-- Generated by scripts/build_domain_model.py — do not edit.
--
-- Schema, constraints and row-level security for the Trancendos domain model.
-- Regenerate rather than patching: this file is derived from src/domain/build.py,
-- which reads the platform's own registers.
--
-- Row-level security below depends on two session settings the application must
-- set per request, after authenticating:
--
--   SET LOCAL trancendos.location = '<Location name>';
--   SET LOCAL trancendos.role     = '<Job Description>';
--
-- LOCAL, so the setting dies with the transaction rather than leaking into the
-- next request that borrows the same pooled connection. A policy that reads an
-- unset setting sees NULL and matches nothing, which is the correct failure.
"""


def _column(entity: Entity) -> List[str]:
    lines: List[str] = []
    for attribute in entity.attributes:
        if not attribute.stored:
            continue
        parts = [f"    {attribute.column} {attribute.type.sql}"]
        if attribute.required:
            parts.append("NOT NULL")
        if attribute.default is not None:
            parts.append(f"DEFAULT {attribute.default}")
        lines.append(" ".join(parts))
    return lines


def table_ddl(entity: Entity) -> str:
    if not entity.persistable:
        return f"-- {entity.name}: non-persistable, no table.\n"

    columns = _column(entity)
    # Every entity gets a surrogate key. The natural keys here (pid, aid, ci_id)
    # are stable today, but a CMDB that keys rows on an identifier the estate
    # might renumber has to rewrite its foreign keys when it does.
    body = ["    id BIGSERIAL PRIMARY KEY"]
    body.extend(columns)

    natural = next((a for a in entity.attributes if a.required and a.stored), None)
    statements = [
        f"CREATE SCHEMA IF NOT EXISTS {entity.schema};",
        "",
        f"-- {entity.description}" if entity.description else "",
        f"-- Source: {entity.source}" if entity.source else "",
        f"CREATE TABLE IF NOT EXISTS {entity.qualified} (",
        ",\n".join(body),
        ");",
    ]
    if natural:
        statements.append(
            f"CREATE UNIQUE INDEX IF NOT EXISTS {entity.table}_{natural.column}_key "
            f"ON {entity.qualified} ({natural.column});"
        )
    return "\n".join(s for s in statements if s != "") + "\n"


def rls_ddl(entity: Entity) -> str:
    if not entity.persistable:
        return ""

    lines = [
        f"ALTER TABLE {entity.qualified} ENABLE ROW LEVEL SECURITY;",
        f"ALTER TABLE {entity.qualified} FORCE ROW LEVEL SECURITY;",
    ]

    if not entity.access_rules:
        lines.append(
            f"-- No access rules modelled for {entity.name}. RLS is enabled with no "
            f"policy, so this table returns nothing until rules are added. That is "
            f"deliberate: an unmodelled table must fail closed."
        )
        return "\n".join(lines) + "\n"

    for index, rule in enumerate(entity.access_rules):
        if rule.access is Access.NONE:
            continue
        policy = f"{entity.table}_p{index}_{_role_slug(rule.role)}"
        constraint = rule.constraint or "true"
        role_check = (
            "true"
            if rule.role == "*"
            else f"current_setting('trancendos.role', true) = {_sql_literal(rule.role)}"
        )
        using = f"({role_check}) AND ({constraint})"

        if rule.description:
            lines.append(f"-- {rule.description}")
        lines.append(f"-- members: {', '.join(rule.members)}")
        if rule.access is Access.READ:
            lines.append(
                f"CREATE POLICY {policy} ON {entity.qualified} FOR SELECT USING ({using});"
            )
        else:
            lines.append(
                f"CREATE POLICY {policy} ON {entity.qualified} FOR ALL "
                f"USING ({using}) WITH CHECK ({using});"
            )

        # Member-level access is Mendix's model and not something a row policy can
        # express: RLS filters rows, not columns. Column privileges are the
        # PostgreSQL feature that does, and saying so here keeps the gap visible
        # rather than letting a reader assume the row policy covered it.
        named = [m for m in rule.members if m != "*"]
        if named and rule.access is not Access.NONE:
            columns = ", ".join(entity.attribute(m).column for m in named if entity.attribute(m))
            if columns:
                verb = "SELECT" if rule.access is Access.READ else "SELECT, UPDATE"
                lines.append(
                    f"-- column-level grant (RLS filters rows, not columns):\n"
                    f"-- GRANT {verb} ({columns}) ON {entity.qualified} TO <role>;"
                )
        sensitive = entity.sensitive_attributes
        if sensitive and "*" in rule.members:
            lines.append(
                f"-- WARNING: this rule uses '*' on an entity with sensitive members "
                f"({', '.join(sensitive)}). Name members explicitly instead."
            )
        lines.append("")
    return "\n".join(lines)


def association_ddl(model: DomainModel) -> str:
    lines: List[str] = []
    for association in model.associations:
        owner = model.entity(association.owner)
        target = model.entity(association.target)
        if owner is None or target is None:
            lines.append(
                f"-- {association.name}: owner or target not modelled "
                f"({association.owner} -> {association.target}); skipped."
            )
            continue
        if association.multiplicity.value == "*-*":
            join = f"{owner.schema}.{owner.table}_{target.table}"
            lines.append(f"-- {association.description}" if association.description else "")
            lines.append(
                f"CREATE TABLE IF NOT EXISTS {join} (\n"
                f"    {owner.table}_id BIGINT NOT NULL REFERENCES {owner.qualified}(id) "
                f"ON DELETE CASCADE,\n"
                f"    {target.table}_id BIGINT NOT NULL REFERENCES {target.qualified}(id) "
                f"ON DELETE CASCADE,\n"
                f"    PRIMARY KEY ({owner.table}_id, {target.table}_id)\n"
                f");"
            )
        else:
            column = f"{_column_for(association.name, target.table)}_id"
            null = " NOT NULL" if association.required else ""
            lines.append(f"-- {association.description}" if association.description else "")
            lines.append(
                f"ALTER TABLE {owner.qualified} ADD COLUMN IF NOT EXISTS "
                f"{column} BIGINT{null} REFERENCES {target.qualified}(id);"
            )
        lines.append("")
    return "\n".join(s for s in lines if s is not None)


def _column_for(association_name: str, target_table: str) -> str:
    from src.domain.model import _snake

    # Two associations from Container to Location (custody and jurisdiction) must
    # not collapse onto one `location_id` column -- that would merge two facts the
    # whole shared-jurisdiction model exists to keep apart.
    return _snake(association_name)


def _role_slug(role: str) -> str:
    from src.domain.model import _snake

    return _snake(role) if role != "*" else "all"


def _sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def generate(model: DomainModel) -> str:
    parts = [HEADER, ""]
    for entity in model.entities:
        parts.append(f"-- ── {entity.name} ({entity.module}) " + "─" * 30)
        parts.append(table_ddl(entity))
        parts.append("")
    parts.append("-- ── Associations " + "─" * 40)
    parts.append(association_ddl(model))
    parts.append("-- ── Row-level security " + "─" * 34)
    for entity in model.entities:
        parts.append(rls_ddl(entity))
    return "\n".join(parts).rstrip() + "\n"
