"""Emit PostgreSQL DDL from the domain model: schemas, tables, keys, RLS.

This is the reason to have a domain model rather than a diagram. One model
produces the schema, the foreign keys and the row-level security policies, so
"who may read this column" is answered in the same place as "what is this
column" -- instead of in a permissions matrix that drifts from the tables it
describes.

Three choices worth stating, because each prevents a specific failure:

* **Schema per module, not database per module.** `the_citadel.location`,
  `the_ice_box.container`. Cross-schema joins work, one backup covers everything,
  one connection pool. A database per Location would recreate the 96-file SQLite
  problem with a heavier engine.

* **RLS is enabled with a default deny.** PostgreSQL's own rule: a table with row
  security enabled and no policy returns nothing. Generating the ENABLE without
  generating policies therefore fails closed, which is the safe direction for a
  generator to be incomplete in.

* **Calculated attributes get no column.** Mendix's stored/calculated split
  carried through, so a value derived at read time cannot silently become a
  stale copy in a row.
"""

from __future__ import annotations

from typing import List

from src.domain.model import Access, DomainModel, Entity, Multiplicity

HEADER = """-- Generated by scripts/build_domain_model.py — do not edit.
--
-- Schema, constraints and row-level security for the Trancendos domain model.
-- Regenerate rather than patching: this file is derived from src/domain/build.py,
-- which reads the platform's own registers.
--
-- Row-level security below depends on two session settings the application must
-- set per request, after authenticating:
--
--   SET LOCAL trancendos.location = '<Location name>';
--   SET LOCAL trancendos.role     = '<role class>';
--
--   The role is a CLASS, not one of the 56 Job Description titles in
--   module_roles(). 'Location seat' and 'The Ice Box seat' are generic over
--   every Location, which is what lets one rule cover all 43; no Job
--   Description string will ever equal them. This header said
--   '<Job Description>' until 2026-09-28, which made every non-wildcard
--   policy read as unsatisfiable to anyone setting a real seat title.
--
-- LOCAL, so the setting dies with the transaction rather than leaking into the
-- next request that borrows the same pooled connection. A policy that reads an
-- unset setting sees NULL and matches nothing, which is the correct failure.
"""


def _column(entity: Entity) -> List[str]:
    lines: List[str] = []
    for attribute in entity.attributes:
        if not attribute.stored:
            continue
        parts = [f"    {attribute.column} {attribute.type.sql}"]
        if attribute.required:
            parts.append("NOT NULL")
        if attribute.default is not None:
            parts.append(f"DEFAULT {attribute.default}")
        lines.append(" ".join(parts))
    return lines


def table_ddl(entity: Entity) -> str:
    if not entity.persistable:
        return f"-- {entity.name}: non-persistable, no table.\n"

    columns = _column(entity)
    # Every entity gets a surrogate key. The natural keys here (pid, aid, ci_id)
    # are stable today, but a CMDB that keys rows on an identifier the estate
    # might renumber has to rewrite its foreign keys when it does.
    body = ["    id BIGSERIAL PRIMARY KEY"]
    body.extend(columns)

    natural = next((a for a in entity.attributes if a.required and a.stored), None)
    statements = [
        f"CREATE SCHEMA IF NOT EXISTS {entity.schema};",
        "",
        f"-- {entity.description}" if entity.description else "",
        f"-- Source: {entity.source}" if entity.source else "",
        f"CREATE TABLE IF NOT EXISTS {entity.qualified} (",
        ",\n".join(body),
        ");",
    ]
    if natural:
        statements.append(
            f"CREATE UNIQUE INDEX IF NOT EXISTS {entity.table}_{natural.column}_key "
            f"ON {entity.qualified} ({natural.column});"
        )
    return "\n".join(s for s in statements if s != "") + "\n"


def rls_ddl(entity: Entity) -> str:
    if not entity.persistable:
        return ""

    lines = [
        f"ALTER TABLE {entity.qualified} ENABLE ROW LEVEL SECURITY;",
        f"ALTER TABLE {entity.qualified} FORCE ROW LEVEL SECURITY;",
    ]

    if not entity.access_rules:
        lines.append(
            f"-- No access rules modelled for {entity.name}. RLS is enabled with no "
            f"policy, so this table returns nothing until rules are added. That is "
            f"deliberate: an unmodelled table must fail closed."
        )
        return "\n".join(lines) + "\n"

    for index, rule in enumerate(entity.access_rules):
        if rule.access is Access.NONE:
            continue
        policy = f"{entity.table}_p{index}_{_role_slug(rule.role)}"
        constraint = rule.constraint or "true"
        role_check = (
            "true"
            if rule.role == "*"
            else f"current_setting('trancendos.role', true) = {_sql_literal(rule.role)}"
        )
        using = f"({role_check}) AND ({constraint})"

        if rule.description:
            lines.append(f"-- {rule.description}")
        lines.append(f"-- members: {', '.join(rule.members)}")
        # Tables, indexes and association columns are all IF NOT EXISTS; policies
        # were the one unconditional CREATE, so re-applying the regenerated
        # schema to a database that already had it stopped at the first policy.
        # A generated artefact that can only ever be applied once cannot be the
        # thing that keeps a database in step with the model.
        lines.append(f"DROP POLICY IF EXISTS {policy} ON {entity.qualified};")
        lines.append(f"DROP POLICY IF EXISTS {policy}_r ON {entity.qualified};")
        lines.append(f"DROP POLICY IF EXISTS {policy}_w ON {entity.qualified};")
        if rule.access is Access.READ:
            lines.append(
                f"CREATE POLICY {policy} ON {entity.qualified} FOR SELECT USING ({using});"
            )
        else:
            # READ_WRITE emits SELECT + UPDATE, not FOR ALL. `Access` carries
            # Mendix's three levels, so "write" is one value covering every
            # statement -- and FOR ALL is INSERT, UPDATE and DELETE. Every
            # READ_WRITE rule in this model describes editing rows that already
            # exist ("may edit its operational fields", "owns personality
            # assignment", "may edit every container record"); these are derived
            # registers a build pipeline populates, so a seat deleting its own
            # register row is not a power the rule claimed. Granting it because the
            # enum had no finer level is the kind of silent widening this file
            # refuses elsewhere. A rule that genuinely needs INSERT or DELETE
            # should say so by extending the model, where it is reviewable.
            lines.append(
                f"CREATE POLICY {policy}_r ON {entity.qualified} FOR SELECT USING ({using});"
            )
            lines.append(
                f"CREATE POLICY {policy}_w ON {entity.qualified} FOR UPDATE "
                f"USING ({using}) WITH CHECK ({using});"
            )

        # Member-level access is Mendix's model and not something a row policy can
        # express: RLS filters rows, not columns. Column privileges are the
        # PostgreSQL feature that does, and saying so here keeps the gap visible
        # rather than letting a reader assume the row policy covered it.
        named = [m for m in rule.members if m != "*"]
        if named and rule.access is not Access.NONE:
            columns = ", ".join(entity.attribute(m).column for m in named if entity.attribute(m))
            if columns:
                verb = "SELECT" if rule.access is Access.READ else "SELECT, UPDATE"
                lines.append(
                    f"-- column-level grant (RLS filters rows, not columns):\n"
                    f"-- GRANT {verb} ({columns}) ON {entity.qualified} TO <role>;"
                )
        sensitive = entity.sensitive_attributes
        if sensitive and "*" in rule.members:
            lines.append(
                f"-- WARNING: this rule uses '*' on an entity with sensitive members "
                f"({', '.join(sensitive)}). Name members explicitly instead."
            )
        lines.append("")
    return "\n".join(lines)


def association_ddl(model: DomainModel) -> str:
    lines: List[str] = []
    for association in model.associations:
        owner = model.entity(association.owner)
        target = model.entity(association.target)
        if owner is None or target is None:
            lines.append(
                f"-- {association.name}: owner or target not modelled "
                f"({association.owner} -> {association.target}); skipped."
            )
            continue
        if association.multiplicity is Multiplicity.MANY_TO_MANY:
            join = f"{owner.schema}.{owner.table}_{target.table}"
            # A self-referential many-to-many derives the same column name on
            # both sides. LocationDependsOnLocation produced `location_id`
            # twice and PRIMARY KEY (location_id, location_id); PostgreSQL
            # answers that with `column "location_id" appears twice in primary
            # key constraint` and refuses the whole file, so nothing after line
            # 127 -- every RLS policy in the schema -- was ever created.
            if owner is target:
                left, right = f"source_{owner.table}_id", f"target_{target.table}_id"
            else:
                left, right = f"{owner.table}_id", f"{target.table}_id"
            lines.append(f"-- {association.description}" if association.description else "")
            lines.append(
                f"CREATE TABLE IF NOT EXISTS {join} (\n"
                f"    {left} BIGINT NOT NULL REFERENCES {owner.qualified}(id) "
                f"ON DELETE CASCADE,\n"
                f"    {right} BIGINT NOT NULL REFERENCES {target.qualified}(id) "
                f"ON DELETE CASCADE,\n"
                f"    PRIMARY KEY ({left}, {right})\n"
                f");"
            )
            # A join table left outside RLS is a way around every policy on the
            # tables it joins: the dependency graph would be readable in full by
            # anyone the row policies deny.
            lines.append(f"ALTER TABLE {join} ENABLE ROW LEVEL SECURITY;")
            lines.append(f"ALTER TABLE {join} FORCE ROW LEVEL SECURITY;")
            slug = f"{owner.table}_{target.table}_read"
            lines.append(f"DROP POLICY IF EXISTS {slug} ON {join};")
            lines.append(
                f"CREATE POLICY {slug} ON {join} FOR SELECT USING (true);"
                "  -- the graph itself is not sensitive; its endpoints carry their own policies"
            )
        else:
            # Which table carries the key is the multiplicity's business, not the
            # association name's. See Multiplicity's docstring.
            if association.multiplicity is Multiplicity.ONE_TO_MANY:
                holder, references = target, owner
            else:
                holder, references = owner, target
            column = f"{_column_for(association.name, references.table)}_id"
            lines.append(f"-- {association.description}" if association.description else "")
            # A required association is added nullable and then constrained,
            # rather than `ADD COLUMN ... NOT NULL` in one statement. The
            # one-statement form has no default, so PostgreSQL rejects it the
            # moment the table already holds a row -- and the replay test only
            # ever exercised an empty schema, so nothing here noticed. Splitting
            # it means re-applying this file to a populated database adds the
            # column, stops at a NOT NULL it cannot satisfy, and says which rows
            # need a reference. That is a failure an operator can act on, where
            # the single statement failed before the column existed at all.
            #
            # The backfill cannot be generated: which row should point where is
            # the data's business, not the model's, and inventing a reference
            # would be worse than stopping.
            lines.append(
                f"ALTER TABLE {holder.qualified} ADD COLUMN IF NOT EXISTS "
                f"{column} BIGINT REFERENCES {references.qualified}(id);"
            )
            if association.required:
                lines.append(
                    f"-- Required by the model. Backfill {holder.qualified}.{column} for any "
                    f"existing rows, then:"
                )
                lines.append(f"ALTER TABLE {holder.qualified} ALTER COLUMN {column} SET NOT NULL;")
            if association.multiplicity is Multiplicity.ONE_TO_ONE:
                # Without this the schema permits many-to-one on a column the
                # model declares one-to-one -- the constraint exists only in the
                # model, which is the drift this file exists to remove.
                index = f"{holder.table}_{column}_uniq"
                lines.append(
                    f"CREATE UNIQUE INDEX IF NOT EXISTS {index} ON {holder.qualified} ({column});"
                )
        lines.append("")
    return "\n".join(s for s in lines if s is not None)


def _column_for(association_name: str, target_table: str) -> str:
    from src.domain.model import _snake

    # Two associations from Container to Location (custody and jurisdiction) must
    # not collapse onto one `location_id` column -- that would merge two facts the
    # whole shared-jurisdiction model exists to keep apart.
    return _snake(association_name)


def _role_slug(role: str) -> str:
    from src.domain.model import _snake

    return _snake(role) if role != "*" else "all"


def _sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def generate(model: DomainModel) -> str:
    parts = [HEADER, ""]
    for entity in model.entities:
        parts.append(f"-- ── {entity.name} ({entity.module}) " + "─" * 30)
        parts.append(table_ddl(entity))
        parts.append("")
    parts.append("-- ── Associations " + "─" * 40)
    parts.append(association_ddl(model))
    parts.append("-- ── Row-level security " + "─" * 34)
    for entity in model.entities:
        parts.append(rls_ddl(entity))
    return "\n".join(parts).rstrip() + "\n"
