apiVersion: v1
kind: ServiceAccount
metadata:
  name: tranc3-api
  namespace: tranc3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tranc3-api
  namespace: tranc3
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tranc3-api
  namespace: tranc3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tranc3-api
subjects:
  - kind: ServiceAccount
    name: tranc3-api
    namespace: tranc3