// AeonMind gRPC Protocol Buffer Definitions
// Tranc3 Infinity Ecosystem v0.9.0
//
// Custom Hierarchy:
//   AI    = The overarching ML/LLM Complex (Tier 3)
//   Agent = Lower-level autonomous AI (Tier 4)
//   Bot   = Stateless service worker/function (Tier 5)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aeonmind.proto

package aeonmind

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tier int32

const (
	Tier_TIER_UNSPECIFIED  Tier = 0
	Tier_TIER_HUMAN        Tier = 1
	Tier_TIER_ORCHESTRATOR Tier = 2
	Tier_TIER_PRIME        Tier = 3
	Tier_TIER_AI           Tier = 4
	Tier_TIER_AGENT        Tier = 5
	Tier_TIER_BOT          Tier = 6
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_HUMAN",
		2: "TIER_ORCHESTRATOR",
		3: "TIER_PRIME",
		4: "TIER_AI",
		5: "TIER_AGENT",
		6: "TIER_BOT",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED":  0,
		"TIER_HUMAN":        1,
		"TIER_ORCHESTRATOR": 2,
		"TIER_PRIME":        3,
		"TIER_AI":           4,
		"TIER_AGENT":        5,
		"TIER_BOT":          6,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_aeonmind_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_aeonmind_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{0}
}

type SentinelChannel int32

const (
	SentinelChannel_CHANNEL_UNSPECIFIED    SentinelChannel = 0
	SentinelChannel_CHANNEL_PLATFORM       SentinelChannel = 1
	SentinelChannel_CHANNEL_AGENTS         SentinelChannel = 2
	SentinelChannel_CHANNEL_MODELS         SentinelChannel = 3
	SentinelChannel_CHANNEL_WORKFLOWS      SentinelChannel = 4
	SentinelChannel_CHANNEL_SECURITY       SentinelChannel = 5
	SentinelChannel_CHANNEL_HIVE           SentinelChannel = 6
	SentinelChannel_CHANNEL_NEXUS          SentinelChannel = 7
	SentinelChannel_CHANNEL_BRIDGE         SentinelChannel = 8
	SentinelChannel_CHANNEL_PILLARS        SentinelChannel = 9
	SentinelChannel_CHANNEL_INFRASTRUCTURE SentinelChannel = 10
	SentinelChannel_CHANNEL_EVENTS         SentinelChannel = 11
)

// Enum value maps for SentinelChannel.
var (
	SentinelChannel_name = map[int32]string{
		0:  "CHANNEL_UNSPECIFIED",
		1:  "CHANNEL_PLATFORM",
		2:  "CHANNEL_AGENTS",
		3:  "CHANNEL_MODELS",
		4:  "CHANNEL_WORKFLOWS",
		5:  "CHANNEL_SECURITY",
		6:  "CHANNEL_HIVE",
		7:  "CHANNEL_NEXUS",
		8:  "CHANNEL_BRIDGE",
		9:  "CHANNEL_PILLARS",
		10: "CHANNEL_INFRASTRUCTURE",
		11: "CHANNEL_EVENTS",
	}
	SentinelChannel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED":    0,
		"CHANNEL_PLATFORM":       1,
		"CHANNEL_AGENTS":         2,
		"CHANNEL_MODELS":         3,
		"CHANNEL_WORKFLOWS":      4,
		"CHANNEL_SECURITY":       5,
		"CHANNEL_HIVE":           6,
		"CHANNEL_NEXUS":          7,
		"CHANNEL_BRIDGE":         8,
		"CHANNEL_PILLARS":        9,
		"CHANNEL_INFRASTRUCTURE": 10,
		"CHANNEL_EVENTS":         11,
	}
)

func (x SentinelChannel) Enum() *SentinelChannel {
	p := new(SentinelChannel)
	*p = x
	return p
}

func (x SentinelChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SentinelChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_aeonmind_proto_enumTypes[1].Descriptor()
}

func (SentinelChannel) Type() protoreflect.EnumType {
	return &file_aeonmind_proto_enumTypes[1]
}

func (x SentinelChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SentinelChannel.Descriptor instead.
func (SentinelChannel) EnumDescriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{1}
}

type EntityType int32

const (
	EntityType_ENTITY_UNSPECIFIED EntityType = 0
	EntityType_ENTITY_AI_COMPLEX  EntityType = 1
	EntityType_ENTITY_AGENT       EntityType = 2
	EntityType_ENTITY_BOT         EntityType = 3
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_UNSPECIFIED",
		1: "ENTITY_AI_COMPLEX",
		2: "ENTITY_AGENT",
		3: "ENTITY_BOT",
	}
	EntityType_value = map[string]int32{
		"ENTITY_UNSPECIFIED": 0,
		"ENTITY_AI_COMPLEX":  1,
		"ENTITY_AGENT":       2,
		"ENTITY_BOT":         3,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_aeonmind_proto_enumTypes[2].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_aeonmind_proto_enumTypes[2]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{2}
}

type AgentStatus int32

const (
	AgentStatus_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_STATUS_IDLE        AgentStatus = 1
	AgentStatus_STATUS_RUNNING     AgentStatus = 2
	AgentStatus_STATUS_WAITING     AgentStatus = 3
	AgentStatus_STATUS_ERROR       AgentStatus = 4
	AgentStatus_STATUS_TERMINATED  AgentStatus = 5
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_IDLE",
		2: "STATUS_RUNNING",
		3: "STATUS_WAITING",
		4: "STATUS_ERROR",
		5: "STATUS_TERMINATED",
	}
	AgentStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_IDLE":        1,
		"STATUS_RUNNING":     2,
		"STATUS_WAITING":     3,
		"STATUS_ERROR":       4,
		"STATUS_TERMINATED":  5,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aeonmind_proto_enumTypes[3].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_aeonmind_proto_enumTypes[3]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{3}
}

type FluidicState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Velocity      []float64              `protobuf:"fixed64,1,rep,packed,name=velocity,proto3" json:"velocity,omitempty"`
	Acceleration  []float64              `protobuf:"fixed64,2,rep,packed,name=acceleration,proto3" json:"acceleration,omitempty"`
	Energy        float64                `protobuf:"fixed64,3,opt,name=energy,proto3" json:"energy,omitempty"`
	Coherence     float64                `protobuf:"fixed64,4,opt,name=coherence,proto3" json:"coherence,omitempty"`
	Entropy       float64                `protobuf:"fixed64,5,opt,name=entropy,proto3" json:"entropy,omitempty"`
	Compression   float64                `protobuf:"fixed64,6,opt,name=compression,proto3" json:"compression,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FluidicState) Reset() {
	*x = FluidicState{}
	mi := &file_aeonmind_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FluidicState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluidicState) ProtoMessage() {}

func (x *FluidicState) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluidicState.ProtoReflect.Descriptor instead.
func (*FluidicState) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{0}
}

func (x *FluidicState) GetVelocity() []float64 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *FluidicState) GetAcceleration() []float64 {
	if x != nil {
		return x.Acceleration
	}
	return nil
}

func (x *FluidicState) GetEnergy() float64 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *FluidicState) GetCoherence() float64 {
	if x != nil {
		return x.Coherence
	}
	return 0
}

func (x *FluidicState) GetEntropy() float64 {
	if x != nil {
		return x.Entropy
	}
	return 0
}

func (x *FluidicState) GetCompression() float64 {
	if x != nil {
		return x.Compression
	}
	return 0
}

func (x *FluidicState) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IntelligenceScore struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DecisionQuality    float64                `protobuf:"fixed64,1,opt,name=decision_quality,json=decisionQuality,proto3" json:"decision_quality,omitempty"`
	AdaptationSpeed    float64                `protobuf:"fixed64,2,opt,name=adaptation_speed,json=adaptationSpeed,proto3" json:"adaptation_speed,omitempty"`
	StateCoherence     float64                `protobuf:"fixed64,3,opt,name=state_coherence,json=stateCoherence,proto3" json:"state_coherence,omitempty"`
	ResourceEfficiency float64                `protobuf:"fixed64,4,opt,name=resource_efficiency,json=resourceEfficiency,proto3" json:"resource_efficiency,omitempty"`
	Communication      float64                `protobuf:"fixed64,5,opt,name=communication,proto3" json:"communication,omitempty"`
	Overall            float64                `protobuf:"fixed64,6,opt,name=overall,proto3" json:"overall,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IntelligenceScore) Reset() {
	*x = IntelligenceScore{}
	mi := &file_aeonmind_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntelligenceScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntelligenceScore) ProtoMessage() {}

func (x *IntelligenceScore) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntelligenceScore.ProtoReflect.Descriptor instead.
func (*IntelligenceScore) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{1}
}

func (x *IntelligenceScore) GetDecisionQuality() float64 {
	if x != nil {
		return x.DecisionQuality
	}
	return 0
}

func (x *IntelligenceScore) GetAdaptationSpeed() float64 {
	if x != nil {
		return x.AdaptationSpeed
	}
	return 0
}

func (x *IntelligenceScore) GetStateCoherence() float64 {
	if x != nil {
		return x.StateCoherence
	}
	return 0
}

func (x *IntelligenceScore) GetResourceEfficiency() float64 {
	if x != nil {
		return x.ResourceEfficiency
	}
	return 0
}

func (x *IntelligenceScore) GetCommunication() float64 {
	if x != nil {
		return x.Communication
	}
	return 0
}

func (x *IntelligenceScore) GetOverall() float64 {
	if x != nil {
		return x.Overall
	}
	return 0
}

type ScoringWeights struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DecisionQuality    float64                `protobuf:"fixed64,1,opt,name=decision_quality,json=decisionQuality,proto3" json:"decision_quality,omitempty"`
	AdaptationSpeed    float64                `protobuf:"fixed64,2,opt,name=adaptation_speed,json=adaptationSpeed,proto3" json:"adaptation_speed,omitempty"`
	StateCoherence     float64                `protobuf:"fixed64,3,opt,name=state_coherence,json=stateCoherence,proto3" json:"state_coherence,omitempty"`
	ResourceEfficiency float64                `protobuf:"fixed64,4,opt,name=resource_efficiency,json=resourceEfficiency,proto3" json:"resource_efficiency,omitempty"`
	Communication      float64                `protobuf:"fixed64,5,opt,name=communication,proto3" json:"communication,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScoringWeights) Reset() {
	*x = ScoringWeights{}
	mi := &file_aeonmind_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoringWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoringWeights) ProtoMessage() {}

func (x *ScoringWeights) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoringWeights.ProtoReflect.Descriptor instead.
func (*ScoringWeights) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{2}
}

func (x *ScoringWeights) GetDecisionQuality() float64 {
	if x != nil {
		return x.DecisionQuality
	}
	return 0
}

func (x *ScoringWeights) GetAdaptationSpeed() float64 {
	if x != nil {
		return x.AdaptationSpeed
	}
	return 0
}

func (x *ScoringWeights) GetStateCoherence() float64 {
	if x != nil {
		return x.StateCoherence
	}
	return 0
}

func (x *ScoringWeights) GetResourceEfficiency() float64 {
	if x != nil {
		return x.ResourceEfficiency
	}
	return 0
}

func (x *ScoringWeights) GetCommunication() float64 {
	if x != nil {
		return x.Communication
	}
	return 0
}

type DnaVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genes         []float64              `protobuf:"fixed64,1,rep,packed,name=genes,proto3" json:"genes,omitempty"`
	Fitness       float64                `protobuf:"fixed64,2,opt,name=fitness,proto3" json:"fitness,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnaVector) Reset() {
	*x = DnaVector{}
	mi := &file_aeonmind_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnaVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnaVector) ProtoMessage() {}

func (x *DnaVector) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnaVector.ProtoReflect.Descriptor instead.
func (*DnaVector) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{3}
}

func (x *DnaVector) GetGenes() []float64 {
	if x != nil {
		return x.Genes
	}
	return nil
}

func (x *DnaVector) GetFitness() float64 {
	if x != nil {
		return x.Fitness
	}
	return 0
}

func (x *DnaVector) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type QuantumCircuitConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NQubits            int32                  `protobuf:"varint,1,opt,name=n_qubits,json=nQubits,proto3" json:"n_qubits,omitempty"`
	NLayers            int32                  `protobuf:"varint,2,opt,name=n_layers,json=nLayers,proto3" json:"n_layers,omitempty"`
	RotationsPerLayer  int32                  `protobuf:"varint,3,opt,name=rotations_per_layer,json=rotationsPerLayer,proto3" json:"rotations_per_layer,omitempty"`
	AdaptiveDepth      bool                   `protobuf:"varint,4,opt,name=adaptive_depth,json=adaptiveDepth,proto3" json:"adaptive_depth,omitempty"`
	MaxDepth           int32                  `protobuf:"varint,5,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	EntanglingGate     string                 `protobuf:"bytes,6,opt,name=entangling_gate,json=entanglingGate,proto3" json:"entangling_gate,omitempty"`
	EntanglingStrategy string                 `protobuf:"bytes,7,opt,name=entangling_strategy,json=entanglingStrategy,proto3" json:"entangling_strategy,omitempty"`
	ParameterRange     []float64              `protobuf:"fixed64,8,rep,packed,name=parameter_range,json=parameterRange,proto3" json:"parameter_range,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuantumCircuitConfig) Reset() {
	*x = QuantumCircuitConfig{}
	mi := &file_aeonmind_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuantumCircuitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantumCircuitConfig) ProtoMessage() {}

func (x *QuantumCircuitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantumCircuitConfig.ProtoReflect.Descriptor instead.
func (*QuantumCircuitConfig) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{4}
}

func (x *QuantumCircuitConfig) GetNQubits() int32 {
	if x != nil {
		return x.NQubits
	}
	return 0
}

func (x *QuantumCircuitConfig) GetNLayers() int32 {
	if x != nil {
		return x.NLayers
	}
	return 0
}

func (x *QuantumCircuitConfig) GetRotationsPerLayer() int32 {
	if x != nil {
		return x.RotationsPerLayer
	}
	return 0
}

func (x *QuantumCircuitConfig) GetAdaptiveDepth() bool {
	if x != nil {
		return x.AdaptiveDepth
	}
	return false
}

func (x *QuantumCircuitConfig) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *QuantumCircuitConfig) GetEntanglingGate() string {
	if x != nil {
		return x.EntanglingGate
	}
	return ""
}

func (x *QuantumCircuitConfig) GetEntanglingStrategy() string {
	if x != nil {
		return x.EntanglingStrategy
	}
	return ""
}

func (x *QuantumCircuitConfig) GetParameterRange() []float64 {
	if x != nil {
		return x.ParameterRange
	}
	return nil
}

type ReservoirConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InputSize      int32                  `protobuf:"varint,1,opt,name=input_size,json=inputSize,proto3" json:"input_size,omitempty"`
	ReservoirSize  int32                  `protobuf:"varint,2,opt,name=reservoir_size,json=reservoirSize,proto3" json:"reservoir_size,omitempty"`
	SpectralRadius float64                `protobuf:"fixed64,3,opt,name=spectral_radius,json=spectralRadius,proto3" json:"spectral_radius,omitempty"`
	LeakingRate    float64                `protobuf:"fixed64,4,opt,name=leaking_rate,json=leakingRate,proto3" json:"leaking_rate,omitempty"`
	InputScaling   float64                `protobuf:"fixed64,5,opt,name=input_scaling,json=inputScaling,proto3" json:"input_scaling,omitempty"`
	Connectivity   float64                `protobuf:"fixed64,6,opt,name=connectivity,proto3" json:"connectivity,omitempty"`
	Washout        int32                  `protobuf:"varint,7,opt,name=washout,proto3" json:"washout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReservoirConfig) Reset() {
	*x = ReservoirConfig{}
	mi := &file_aeonmind_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservoirConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservoirConfig) ProtoMessage() {}

func (x *ReservoirConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservoirConfig.ProtoReflect.Descriptor instead.
func (*ReservoirConfig) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{5}
}

func (x *ReservoirConfig) GetInputSize() int32 {
	if x != nil {
		return x.InputSize
	}
	return 0
}

func (x *ReservoirConfig) GetReservoirSize() int32 {
	if x != nil {
		return x.ReservoirSize
	}
	return 0
}

func (x *ReservoirConfig) GetSpectralRadius() float64 {
	if x != nil {
		return x.SpectralRadius
	}
	return 0
}

func (x *ReservoirConfig) GetLeakingRate() float64 {
	if x != nil {
		return x.LeakingRate
	}
	return 0
}

func (x *ReservoirConfig) GetInputScaling() float64 {
	if x != nil {
		return x.InputScaling
	}
	return 0
}

func (x *ReservoirConfig) GetConnectivity() float64 {
	if x != nil {
		return x.Connectivity
	}
	return 0
}

func (x *ReservoirConfig) GetWashout() int32 {
	if x != nil {
		return x.Washout
	}
	return 0
}

type GeneticConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PopulationSize     int32                  `protobuf:"varint,1,opt,name=population_size,json=populationSize,proto3" json:"population_size,omitempty"`
	DnaLength          int32                  `protobuf:"varint,2,opt,name=dna_length,json=dnaLength,proto3" json:"dna_length,omitempty"`
	MutationRate       float64                `protobuf:"fixed64,3,opt,name=mutation_rate,json=mutationRate,proto3" json:"mutation_rate,omitempty"`
	MutationStrength   float64                `protobuf:"fixed64,4,opt,name=mutation_strength,json=mutationStrength,proto3" json:"mutation_strength,omitempty"`
	CrossoverRate      float64                `protobuf:"fixed64,5,opt,name=crossover_rate,json=crossoverRate,proto3" json:"crossover_rate,omitempty"`
	TournamentSize     int32                  `protobuf:"varint,6,opt,name=tournament_size,json=tournamentSize,proto3" json:"tournament_size,omitempty"`
	ElitismCount       int32                  `protobuf:"varint,7,opt,name=elitism_count,json=elitismCount,proto3" json:"elitism_count,omitempty"`
	MaxGenerations     int32                  `protobuf:"varint,8,opt,name=max_generations,json=maxGenerations,proto3" json:"max_generations,omitempty"`
	DiversityThreshold float64                `protobuf:"fixed64,9,opt,name=diversity_threshold,json=diversityThreshold,proto3" json:"diversity_threshold,omitempty"`
	AdaptiveMutation   bool                   `protobuf:"varint,10,opt,name=adaptive_mutation,json=adaptiveMutation,proto3" json:"adaptive_mutation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GeneticConfig) Reset() {
	*x = GeneticConfig{}
	mi := &file_aeonmind_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneticConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneticConfig) ProtoMessage() {}

func (x *GeneticConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneticConfig.ProtoReflect.Descriptor instead.
func (*GeneticConfig) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{6}
}

func (x *GeneticConfig) GetPopulationSize() int32 {
	if x != nil {
		return x.PopulationSize
	}
	return 0
}

func (x *GeneticConfig) GetDnaLength() int32 {
	if x != nil {
		return x.DnaLength
	}
	return 0
}

func (x *GeneticConfig) GetMutationRate() float64 {
	if x != nil {
		return x.MutationRate
	}
	return 0
}

func (x *GeneticConfig) GetMutationStrength() float64 {
	if x != nil {
		return x.MutationStrength
	}
	return 0
}

func (x *GeneticConfig) GetCrossoverRate() float64 {
	if x != nil {
		return x.CrossoverRate
	}
	return 0
}

func (x *GeneticConfig) GetTournamentSize() int32 {
	if x != nil {
		return x.TournamentSize
	}
	return 0
}

func (x *GeneticConfig) GetElitismCount() int32 {
	if x != nil {
		return x.ElitismCount
	}
	return 0
}

func (x *GeneticConfig) GetMaxGenerations() int32 {
	if x != nil {
		return x.MaxGenerations
	}
	return 0
}

func (x *GeneticConfig) GetDiversityThreshold() float64 {
	if x != nil {
		return x.DiversityThreshold
	}
	return 0
}

func (x *GeneticConfig) GetAdaptiveMutation() bool {
	if x != nil {
		return x.AdaptiveMutation
	}
	return false
}

type AdaptiveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LearningRate  float64                `protobuf:"fixed64,1,opt,name=learning_rate,json=learningRate,proto3" json:"learning_rate,omitempty"`
	MemorySize    int32                  `protobuf:"varint,2,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	MaxIterations int32                  `protobuf:"varint,3,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	Tolerance     float64                `protobuf:"fixed64,4,opt,name=tolerance,proto3" json:"tolerance,omitempty"`
	GradientClip  float64                `protobuf:"fixed64,5,opt,name=gradient_clip,json=gradientClip,proto3" json:"gradient_clip,omitempty"`
	Momentum      float64                `protobuf:"fixed64,6,opt,name=momentum,proto3" json:"momentum,omitempty"`
	Beta1         float64                `protobuf:"fixed64,7,opt,name=beta1,proto3" json:"beta1,omitempty"`
	Beta2         float64                `protobuf:"fixed64,8,opt,name=beta2,proto3" json:"beta2,omitempty"`
	Epsilon       float64                `protobuf:"fixed64,9,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	DecayRate     float64                `protobuf:"fixed64,10,opt,name=decay_rate,json=decayRate,proto3" json:"decay_rate,omitempty"`
	WarmupSteps   int32                  `protobuf:"varint,11,opt,name=warmup_steps,json=warmupSteps,proto3" json:"warmup_steps,omitempty"`
	UseLbfgs      bool                   `protobuf:"varint,12,opt,name=use_lbfgs,json=useLbfgs,proto3" json:"use_lbfgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptiveConfig) Reset() {
	*x = AdaptiveConfig{}
	mi := &file_aeonmind_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveConfig) ProtoMessage() {}

func (x *AdaptiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveConfig.ProtoReflect.Descriptor instead.
func (*AdaptiveConfig) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{7}
}

func (x *AdaptiveConfig) GetLearningRate() float64 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

func (x *AdaptiveConfig) GetMemorySize() int32 {
	if x != nil {
		return x.MemorySize
	}
	return 0
}

func (x *AdaptiveConfig) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *AdaptiveConfig) GetTolerance() float64 {
	if x != nil {
		return x.Tolerance
	}
	return 0
}

func (x *AdaptiveConfig) GetGradientClip() float64 {
	if x != nil {
		return x.GradientClip
	}
	return 0
}

func (x *AdaptiveConfig) GetMomentum() float64 {
	if x != nil {
		return x.Momentum
	}
	return 0
}

func (x *AdaptiveConfig) GetBeta1() float64 {
	if x != nil {
		return x.Beta1
	}
	return 0
}

func (x *AdaptiveConfig) GetBeta2() float64 {
	if x != nil {
		return x.Beta2
	}
	return 0
}

func (x *AdaptiveConfig) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *AdaptiveConfig) GetDecayRate() float64 {
	if x != nil {
		return x.DecayRate
	}
	return 0
}

func (x *AdaptiveConfig) GetWarmupSteps() int32 {
	if x != nil {
		return x.WarmupSteps
	}
	return 0
}

func (x *AdaptiveConfig) GetUseLbfgs() bool {
	if x != nil {
		return x.UseLbfgs
	}
	return false
}

type AiComplexMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tier          Tier                   `protobuf:"varint,3,opt,name=tier,proto3,enum=aeonmind.Tier" json:"tier,omitempty"`
	Agents        []*AgentEntityMsg      `protobuf:"bytes,4,rep,name=agents,proto3" json:"agents,omitempty"`
	Bots          []*BotServiceMsg       `protobuf:"bytes,5,rep,name=bots,proto3" json:"bots,omitempty"`
	Models        []string               `protobuf:"bytes,6,rep,name=models,proto3" json:"models,omitempty"`
	Status        AgentStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=aeonmind.AgentStatus" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiComplexMsg) Reset() {
	*x = AiComplexMsg{}
	mi := &file_aeonmind_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiComplexMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiComplexMsg) ProtoMessage() {}

func (x *AiComplexMsg) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiComplexMsg.ProtoReflect.Descriptor instead.
func (*AiComplexMsg) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{8}
}

func (x *AiComplexMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AiComplexMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiComplexMsg) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *AiComplexMsg) GetAgents() []*AgentEntityMsg {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *AiComplexMsg) GetBots() []*BotServiceMsg {
	if x != nil {
		return x.Bots
	}
	return nil
}

func (x *AiComplexMsg) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *AiComplexMsg) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_STATUS_UNSPECIFIED
}

func (x *AiComplexMsg) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AgentEntityMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tier          Tier                   `protobuf:"varint,3,opt,name=tier,proto3,enum=aeonmind.Tier" json:"tier,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	FluidicState  *FluidicState          `protobuf:"bytes,5,opt,name=fluidic_state,json=fluidicState,proto3" json:"fluidic_state,omitempty"`
	Dna           *DnaVector             `protobuf:"bytes,6,opt,name=dna,proto3" json:"dna,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Intelligence  *IntelligenceScore     `protobuf:"bytes,8,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Status        AgentStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=aeonmind.AgentStatus" json:"status,omitempty"`
	Subscriptions []SentinelChannel      `protobuf:"varint,10,rep,packed,name=subscriptions,proto3,enum=aeonmind.SentinelChannel" json:"subscriptions,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEntityMsg) Reset() {
	*x = AgentEntityMsg{}
	mi := &file_aeonmind_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEntityMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEntityMsg) ProtoMessage() {}

func (x *AgentEntityMsg) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEntityMsg.ProtoReflect.Descriptor instead.
func (*AgentEntityMsg) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{9}
}

func (x *AgentEntityMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentEntityMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentEntityMsg) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *AgentEntityMsg) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentEntityMsg) GetFluidicState() *FluidicState {
	if x != nil {
		return x.FluidicState
	}
	return nil
}

func (x *AgentEntityMsg) GetDna() *DnaVector {
	if x != nil {
		return x.Dna
	}
	return nil
}

func (x *AgentEntityMsg) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AgentEntityMsg) GetIntelligence() *IntelligenceScore {
	if x != nil {
		return x.Intelligence
	}
	return nil
}

func (x *AgentEntityMsg) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_STATUS_UNSPECIFIED
}

func (x *AgentEntityMsg) GetSubscriptions() []SentinelChannel {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *AgentEntityMsg) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BotServiceMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capability    string                 `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	Stateless     bool                   `protobuf:"varint,4,opt,name=stateless,proto3" json:"stateless,omitempty"`
	Status        AgentStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=aeonmind.AgentStatus" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotServiceMsg) Reset() {
	*x = BotServiceMsg{}
	mi := &file_aeonmind_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotServiceMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotServiceMsg) ProtoMessage() {}

func (x *BotServiceMsg) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotServiceMsg.ProtoReflect.Descriptor instead.
func (*BotServiceMsg) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{10}
}

func (x *BotServiceMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BotServiceMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BotServiceMsg) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *BotServiceMsg) GetStateless() bool {
	if x != nil {
		return x.Stateless
	}
	return false
}

func (x *BotServiceMsg) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_STATUS_UNSPECIFIED
}

func (x *BotServiceMsg) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    EntityType             `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=aeonmind.EntityType" json:"entity_type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tier          Tier                   `protobuf:"varint,3,opt,name=tier,proto3,enum=aeonmind.Tier" json:"tier,omitempty"`
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntityRequest) Reset() {
	*x = CreateEntityRequest{}
	mi := &file_aeonmind_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityRequest) ProtoMessage() {}

func (x *CreateEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntityRequest.ProtoReflect.Descriptor instead.
func (*CreateEntityRequest) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{11}
}

func (x *CreateEntityRequest) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_UNSPECIFIED
}

func (x *CreateEntityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEntityRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *CreateEntityRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntityResponse) Reset() {
	*x = CreateEntityResponse{}
	mi := &file_aeonmind_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityResponse) ProtoMessage() {}

func (x *CreateEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntityResponse.ProtoReflect.Descriptor instead.
func (*CreateEntityResponse) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{12}
}

func (x *CreateEntityResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreateEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateEntityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DispatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskRequest) Reset() {
	*x = DispatchTaskRequest{}
	mi := &file_aeonmind_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskRequest) ProtoMessage() {}

func (x *DispatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskRequest.ProtoReflect.Descriptor instead.
func (*DispatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{13}
}

func (x *DispatchTaskRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *DispatchTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *DispatchTaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DispatchTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DispatchTaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DispatchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskResponse) Reset() {
	*x = DispatchTaskResponse{}
	mi := &file_aeonmind_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResponse) ProtoMessage() {}

func (x *DispatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResponse.ProtoReflect.Descriptor instead.
func (*DispatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{14}
}

func (x *DispatchTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DispatchTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchTaskResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DispatchTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_aeonmind_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{15}
}

func (x *GetEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    EntityType             `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=aeonmind.EntityType" json:"entity_type,omitempty"`
	EntityData    []byte                 `protobuf:"bytes,2,opt,name=entity_data,json=entityData,proto3" json:"entity_data,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_aeonmind_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{16}
}

func (x *GetEntityResponse) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_UNSPECIFIED
}

func (x *GetEntityResponse) GetEntityData() []byte {
	if x != nil {
		return x.EntityData
	}
	return nil
}

func (x *GetEntityResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_aeonmind_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{17}
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveEntities int32                  `protobuf:"varint,2,opt,name=active_entities,json=activeEntities,proto3" json:"active_entities,omitempty"`
	TotalAgents    int32                  `protobuf:"varint,3,opt,name=total_agents,json=totalAgents,proto3" json:"total_agents,omitempty"`
	TotalBots      int32                  `protobuf:"varint,4,opt,name=total_bots,json=totalBots,proto3" json:"total_bots,omitempty"`
	UptimeSeconds  float64                `protobuf:"fixed64,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version        string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_aeonmind_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetActiveEntities() int32 {
	if x != nil {
		return x.ActiveEntities
	}
	return 0
}

func (x *HealthCheckResponse) GetTotalAgents() int32 {
	if x != nil {
		return x.TotalAgents
	}
	return 0
}

func (x *HealthCheckResponse) GetTotalBots() int32 {
	if x != nil {
		return x.TotalBots
	}
	return 0
}

func (x *HealthCheckResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    EntityType             `protobuf:"varint,1,opt,name=entity_type,json=entityType,proto3,enum=aeonmind.EntityType" json:"entity_type,omitempty"`
	Tier          Tier                   `protobuf:"varint,2,opt,name=tier,proto3,enum=aeonmind.Tier" json:"tier,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesRequest) Reset() {
	*x = ListEntitiesRequest{}
	mi := &file_aeonmind_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesRequest) ProtoMessage() {}

func (x *ListEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ListEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{19}
}

func (x *ListEntitiesRequest) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_UNSPECIFIED
}

func (x *ListEntitiesRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *ListEntitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEntitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityIds     []string               `protobuf:"bytes,1,rep,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesResponse) Reset() {
	*x = ListEntitiesResponse{}
	mi := &file_aeonmind_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesResponse) ProtoMessage() {}

func (x *ListEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ListEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{20}
}

func (x *ListEntitiesResponse) GetEntityIds() []string {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

func (x *ListEntitiesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListEntitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       SentinelChannel        `protobuf:"varint,1,opt,name=channel,proto3,enum=aeonmind.SentinelChannel" json:"channel,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_aeonmind_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{21}
}

func (x *BroadcastRequest) GetChannel() SentinelChannel {
	if x != nil {
		return x.Channel
	}
	return SentinelChannel_CHANNEL_UNSPECIFIED
}

func (x *BroadcastRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *BroadcastRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    int32                  `protobuf:"varint,1,opt,name=recipients,proto3" json:"recipients,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_aeonmind_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{22}
}

func (x *BroadcastResponse) GetRecipients() int32 {
	if x != nil {
		return x.Recipients
	}
	return 0
}

func (x *BroadcastResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EvolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Generations   int32                  `protobuf:"varint,2,opt,name=generations,proto3" json:"generations,omitempty"`
	Config        *GeneticConfig         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvolveRequest) Reset() {
	*x = EvolveRequest{}
	mi := &file_aeonmind_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolveRequest) ProtoMessage() {}

func (x *EvolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolveRequest.ProtoReflect.Descriptor instead.
func (*EvolveRequest) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{23}
}

func (x *EvolveRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EvolveRequest) GetGenerations() int32 {
	if x != nil {
		return x.Generations
	}
	return 0
}

func (x *EvolveRequest) GetConfig() *GeneticConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type EvolveResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BestDna              *DnaVector             `protobuf:"bytes,1,opt,name=best_dna,json=bestDna,proto3" json:"best_dna,omitempty"`
	BestFitness          float64                `protobuf:"fixed64,2,opt,name=best_fitness,json=bestFitness,proto3" json:"best_fitness,omitempty"`
	GenerationsCompleted int32                  `protobuf:"varint,3,opt,name=generations_completed,json=generationsCompleted,proto3" json:"generations_completed,omitempty"`
	Converged            bool                   `protobuf:"varint,4,opt,name=converged,proto3" json:"converged,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EvolveResponse) Reset() {
	*x = EvolveResponse{}
	mi := &file_aeonmind_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvolveResponse) ProtoMessage() {}

func (x *EvolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvolveResponse.ProtoReflect.Descriptor instead.
func (*EvolveResponse) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{24}
}

func (x *EvolveResponse) GetBestDna() *DnaVector {
	if x != nil {
		return x.BestDna
	}
	return nil
}

func (x *EvolveResponse) GetBestFitness() float64 {
	if x != nil {
		return x.BestFitness
	}
	return 0
}

func (x *EvolveResponse) GetGenerationsCompleted() int32 {
	if x != nil {
		return x.GenerationsCompleted
	}
	return 0
}

func (x *EvolveResponse) GetConverged() bool {
	if x != nil {
		return x.Converged
	}
	return false
}

type OptimizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Config        *AdaptiveConfig        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	MaxSteps      int32                  `protobuf:"varint,3,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_aeonmind_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{25}
}

func (x *OptimizeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *OptimizeRequest) GetConfig() *AdaptiveConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *OptimizeRequest) GetMaxSteps() int32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

type OptimizeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FinalParameters []float64              `protobuf:"fixed64,1,rep,packed,name=final_parameters,json=finalParameters,proto3" json:"final_parameters,omitempty"`
	FinalLoss       float64                `protobuf:"fixed64,2,opt,name=final_loss,json=finalLoss,proto3" json:"final_loss,omitempty"`
	StepsCompleted  int32                  `protobuf:"varint,3,opt,name=steps_completed,json=stepsCompleted,proto3" json:"steps_completed,omitempty"`
	Converged       bool                   `protobuf:"varint,4,opt,name=converged,proto3" json:"converged,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_aeonmind_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aeonmind_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_aeonmind_proto_rawDescGZIP(), []int{26}
}

func (x *OptimizeResponse) GetFinalParameters() []float64 {
	if x != nil {
		return x.FinalParameters
	}
	return nil
}

func (x *OptimizeResponse) GetFinalLoss() float64 {
	if x != nil {
		return x.FinalLoss
	}
	return 0
}

func (x *OptimizeResponse) GetStepsCompleted() int32 {
	if x != nil {
		return x.StepsCompleted
	}
	return 0
}

func (x *OptimizeResponse) GetConverged() bool {
	if x != nil {
		return x.Converged
	}
	return false
}

var File_aeonmind_proto protoreflect.FileDescriptor

const file_aeonmind_proto_rawDesc = "" +
	"\n" +
	"\x0eaeonmind.proto\x12\baeonmind\"\xde\x01\n" +
	"\fFluidicState\x12\x1a\n" +
	"\bvelocity\x18\x01 \x03(\x01R\bvelocity\x12\"\n" +
	"\facceleration\x18\x02 \x03(\x01R\facceleration\x12\x16\n" +
	"\x06energy\x18\x03 \x01(\x01R\x06energy\x12\x1c\n" +
	"\tcoherence\x18\x04 \x01(\x01R\tcoherence\x12\x18\n" +
	"\aentropy\x18\x05 \x01(\x01R\aentropy\x12 \n" +
	"\vcompression\x18\x06 \x01(\x01R\vcompression\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x01R\ttimestamp\"\x83\x02\n" +
	"\x11IntelligenceScore\x12)\n" +
	"\x10decision_quality\x18\x01 \x01(\x01R\x0fdecisionQuality\x12)\n" +
	"\x10adaptation_speed\x18\x02 \x01(\x01R\x0fadaptationSpeed\x12'\n" +
	"\x0fstate_coherence\x18\x03 \x01(\x01R\x0estateCoherence\x12/\n" +
	"\x13resource_efficiency\x18\x04 \x01(\x01R\x12resourceEfficiency\x12$\n" +
	"\rcommunication\x18\x05 \x01(\x01R\rcommunication\x12\x18\n" +
	"\aoverall\x18\x06 \x01(\x01R\aoverall\"\xe6\x01\n" +
	"\x0eScoringWeights\x12)\n" +
	"\x10decision_quality\x18\x01 \x01(\x01R\x0fdecisionQuality\x12)\n" +
	"\x10adaptation_speed\x18\x02 \x01(\x01R\x0fadaptationSpeed\x12'\n" +
	"\x0fstate_coherence\x18\x03 \x01(\x01R\x0estateCoherence\x12/\n" +
	"\x13resource_efficiency\x18\x04 \x01(\x01R\x12resourceEfficiency\x12$\n" +
	"\rcommunication\x18\x05 \x01(\x01R\rcommunication\"M\n" +
	"\tDnaVector\x12\x14\n" +
	"\x05genes\x18\x01 \x03(\x01R\x05genes\x12\x18\n" +
	"\afitness\x18\x02 \x01(\x01R\afitness\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"\xc3\x02\n" +
	"\x14QuantumCircuitConfig\x12\x19\n" +
	"\bn_qubits\x18\x01 \x01(\x05R\anQubits\x12\x19\n" +
	"\bn_layers\x18\x02 \x01(\x05R\anLayers\x12.\n" +
	"\x13rotations_per_layer\x18\x03 \x01(\x05R\x11rotationsPerLayer\x12%\n" +
	"\x0eadaptive_depth\x18\x04 \x01(\bR\radaptiveDepth\x12\x1b\n" +
	"\tmax_depth\x18\x05 \x01(\x05R\bmaxDepth\x12'\n" +
	"\x0fentangling_gate\x18\x06 \x01(\tR\x0eentanglingGate\x12/\n" +
	"\x13entangling_strategy\x18\a \x01(\tR\x12entanglingStrategy\x12'\n" +
	"\x0fparameter_range\x18\b \x03(\x01R\x0eparameterRange\"\x86\x02\n" +
	"\x0fReservoirConfig\x12\x1d\n" +
	"\n" +
	"input_size\x18\x01 \x01(\x05R\tinputSize\x12%\n" +
	"\x0ereservoir_size\x18\x02 \x01(\x05R\rreservoirSize\x12'\n" +
	"\x0fspectral_radius\x18\x03 \x01(\x01R\x0espectralRadius\x12!\n" +
	"\fleaking_rate\x18\x04 \x01(\x01R\vleakingRate\x12#\n" +
	"\rinput_scaling\x18\x05 \x01(\x01R\finputScaling\x12\"\n" +
	"\fconnectivity\x18\x06 \x01(\x01R\fconnectivity\x12\x18\n" +
	"\awashout\x18\a \x01(\x05R\awashout\"\xa5\x03\n" +
	"\rGeneticConfig\x12'\n" +
	"\x0fpopulation_size\x18\x01 \x01(\x05R\x0epopulationSize\x12\x1d\n" +
	"\n" +
	"dna_length\x18\x02 \x01(\x05R\tdnaLength\x12#\n" +
	"\rmutation_rate\x18\x03 \x01(\x01R\fmutationRate\x12+\n" +
	"\x11mutation_strength\x18\x04 \x01(\x01R\x10mutationStrength\x12%\n" +
	"\x0ecrossover_rate\x18\x05 \x01(\x01R\rcrossoverRate\x12'\n" +
	"\x0ftournament_size\x18\x06 \x01(\x05R\x0etournamentSize\x12#\n" +
	"\relitism_count\x18\a \x01(\x05R\felitismCount\x12'\n" +
	"\x0fmax_generations\x18\b \x01(\x05R\x0emaxGenerations\x12/\n" +
	"\x13diversity_threshold\x18\t \x01(\x01R\x12diversityThreshold\x12+\n" +
	"\x11adaptive_mutation\x18\n" +
	" \x01(\bR\x10adaptiveMutation\"\x81\x03\n" +
	"\x0eAdaptiveConfig\x12#\n" +
	"\rlearning_rate\x18\x01 \x01(\x01R\flearningRate\x12\x1f\n" +
	"\vmemory_size\x18\x02 \x01(\x05R\n" +
	"memorySize\x12%\n" +
	"\x0emax_iterations\x18\x03 \x01(\x05R\rmaxIterations\x12\x1c\n" +
	"\ttolerance\x18\x04 \x01(\x01R\ttolerance\x12#\n" +
	"\rgradient_clip\x18\x05 \x01(\x01R\fgradientClip\x12\x1a\n" +
	"\bmomentum\x18\x06 \x01(\x01R\bmomentum\x12\x14\n" +
	"\x05beta1\x18\a \x01(\x01R\x05beta1\x12\x14\n" +
	"\x05beta2\x18\b \x01(\x01R\x05beta2\x12\x18\n" +
	"\aepsilon\x18\t \x01(\x01R\aepsilon\x12\x1d\n" +
	"\n" +
	"decay_rate\x18\n" +
	" \x01(\x01R\tdecayRate\x12!\n" +
	"\fwarmup_steps\x18\v \x01(\x05R\vwarmupSteps\x12\x1b\n" +
	"\tuse_lbfgs\x18\f \x01(\bR\buseLbfgs\"\xfb\x02\n" +
	"\fAiComplexMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x0e.aeonmind.TierR\x04tier\x120\n" +
	"\x06agents\x18\x04 \x03(\v2\x18.aeonmind.AgentEntityMsgR\x06agents\x12+\n" +
	"\x04bots\x18\x05 \x03(\v2\x17.aeonmind.BotServiceMsgR\x04bots\x12\x16\n" +
	"\x06models\x18\x06 \x03(\tR\x06models\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.aeonmind.AgentStatusR\x06status\x12@\n" +
	"\bmetadata\x18\b \x03(\v2$.aeonmind.AiComplexMsg.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x04\n" +
	"\x0eAgentEntityMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x0e.aeonmind.TierR\x04tier\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12;\n" +
	"\rfluidic_state\x18\x05 \x01(\v2\x16.aeonmind.FluidicStateR\ffluidicState\x12%\n" +
	"\x03dna\x18\x06 \x01(\v2\x13.aeonmind.DnaVectorR\x03dna\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12?\n" +
	"\fintelligence\x18\b \x01(\v2\x1b.aeonmind.IntelligenceScoreR\fintelligence\x12-\n" +
	"\x06status\x18\t \x01(\x0e2\x15.aeonmind.AgentStatusR\x06status\x12?\n" +
	"\rsubscriptions\x18\n" +
	" \x03(\x0e2\x19.aeonmind.SentinelChannelR\rsubscriptions\x12B\n" +
	"\bmetadata\x18\v \x03(\v2&.aeonmind.AgentEntityMsg.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x02\n" +
	"\rBotServiceMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\tR\n" +
	"capability\x12\x1c\n" +
	"\tstateless\x18\x04 \x01(\bR\tstateless\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.aeonmind.AgentStatusR\x06status\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.aeonmind.BotServiceMsg.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\x13CreateEntityRequest\x125\n" +
	"\ventity_type\x18\x01 \x01(\x0e2\x14.aeonmind.EntityTypeR\n" +
	"entityType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x0e.aeonmind.TierR\x04tier\x12A\n" +
	"\x06config\x18\x04 \x03(\v2).aeonmind.CreateEntityRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x14CreateEntityResponse\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8b\x02\n" +
	"\x13DispatchTaskRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.aeonmind.DispatchTaskRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x14DispatchTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"/\n" +
	"\x10GetEntityRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"\x81\x01\n" +
	"\x11GetEntityResponse\x125\n" +
	"\ventity_type\x18\x01 \x01(\x0e2\x14.aeonmind.EntityTypeR\n" +
	"entityType\x12\x1f\n" +
	"\ventity_data\x18\x02 \x01(\fR\n" +
	"entityData\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"\x14\n" +
	"\x12HealthCheckRequest\"\xdb\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12'\n" +
	"\x0factive_entities\x18\x02 \x01(\x05R\x0eactiveEntities\x12!\n" +
	"\ftotal_agents\x18\x03 \x01(\x05R\vtotalAgents\x12\x1d\n" +
	"\n" +
	"total_bots\x18\x04 \x01(\x05R\ttotalBots\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x01R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\xac\x01\n" +
	"\x13ListEntitiesRequest\x125\n" +
	"\ventity_type\x18\x01 \x01(\x0e2\x14.aeonmind.EntityTypeR\n" +
	"entityType\x12\"\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x0e.aeonmind.TierR\x04tier\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"~\n" +
	"\x14ListEntitiesResponse\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x01 \x03(\tR\tentityIds\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"~\n" +
	"\x10BroadcastRequest\x123\n" +
	"\achannel\x18\x01 \x01(\x0e2\x19.aeonmind.SentinelChannelR\achannel\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\"M\n" +
	"\x11BroadcastResponse\x12\x1e\n" +
	"\n" +
	"recipients\x18\x01 \x01(\x05R\n" +
	"recipients\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"}\n" +
	"\rEvolveRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\vgenerations\x18\x02 \x01(\x05R\vgenerations\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.aeonmind.GeneticConfigR\x06config\"\xb6\x01\n" +
	"\x0eEvolveResponse\x12.\n" +
	"\bbest_dna\x18\x01 \x01(\v2\x13.aeonmind.DnaVectorR\abestDna\x12!\n" +
	"\fbest_fitness\x18\x02 \x01(\x01R\vbestFitness\x123\n" +
	"\x15generations_completed\x18\x03 \x01(\x05R\x14generationsCompleted\x12\x1c\n" +
	"\tconverged\x18\x04 \x01(\bR\tconverged\"{\n" +
	"\x0fOptimizeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x120\n" +
	"\x06config\x18\x02 \x01(\v2\x18.aeonmind.AdaptiveConfigR\x06config\x12\x1b\n" +
	"\tmax_steps\x18\x03 \x01(\x05R\bmaxSteps\"\xa3\x01\n" +
	"\x10OptimizeResponse\x12)\n" +
	"\x10final_parameters\x18\x01 \x03(\x01R\x0ffinalParameters\x12\x1d\n" +
	"\n" +
	"final_loss\x18\x02 \x01(\x01R\tfinalLoss\x12'\n" +
	"\x0fsteps_completed\x18\x03 \x01(\x05R\x0estepsCompleted\x12\x1c\n" +
	"\tconverged\x18\x04 \x01(\bR\tconverged*~\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TIER_HUMAN\x10\x01\x12\x15\n" +
	"\x11TIER_ORCHESTRATOR\x10\x02\x12\x0e\n" +
	"\n" +
	"TIER_PRIME\x10\x03\x12\v\n" +
	"\aTIER_AI\x10\x04\x12\x0e\n" +
	"\n" +
	"TIER_AGENT\x10\x05\x12\f\n" +
	"\bTIER_BOT\x10\x06*\x93\x02\n" +
	"\x0fSentinelChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CHANNEL_PLATFORM\x10\x01\x12\x12\n" +
	"\x0eCHANNEL_AGENTS\x10\x02\x12\x12\n" +
	"\x0eCHANNEL_MODELS\x10\x03\x12\x15\n" +
	"\x11CHANNEL_WORKFLOWS\x10\x04\x12\x14\n" +
	"\x10CHANNEL_SECURITY\x10\x05\x12\x10\n" +
	"\fCHANNEL_HIVE\x10\x06\x12\x11\n" +
	"\rCHANNEL_NEXUS\x10\a\x12\x12\n" +
	"\x0eCHANNEL_BRIDGE\x10\b\x12\x13\n" +
	"\x0fCHANNEL_PILLARS\x10\t\x12\x1a\n" +
	"\x16CHANNEL_INFRASTRUCTURE\x10\n" +
	"\x12\x12\n" +
	"\x0eCHANNEL_EVENTS\x10\v*]\n" +
	"\n" +
	"EntityType\x12\x16\n" +
	"\x12ENTITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ENTITY_AI_COMPLEX\x10\x01\x12\x10\n" +
	"\fENTITY_AGENT\x10\x02\x12\x0e\n" +
	"\n" +
	"ENTITY_BOT\x10\x03*\x87\x01\n" +
	"\vAgentStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATUS_IDLE\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x12\n" +
	"\x0eSTATUS_WAITING\x10\x03\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x04\x12\x15\n" +
	"\x11STATUS_TERMINATED\x10\x052\xb9\x05\n" +
	"\x14AeonMindOrchestrator\x12M\n" +
	"\fCreateEntity\x12\x1d.aeonmind.CreateEntityRequest\x1a\x1e.aeonmind.CreateEntityResponse\x12D\n" +
	"\tGetEntity\x12\x1a.aeonmind.GetEntityRequest\x1a\x1b.aeonmind.GetEntityResponse\x12M\n" +
	"\fListEntities\x12\x1d.aeonmind.ListEntitiesRequest\x1a\x1e.aeonmind.ListEntitiesResponse\x12M\n" +
	"\fDispatchTask\x12\x1d.aeonmind.DispatchTaskRequest\x1a\x1e.aeonmind.DispatchTaskResponse\x12R\n" +
	"\rDispatchBatch\x12\x1d.aeonmind.DispatchTaskRequest\x1a\x1e.aeonmind.DispatchTaskResponse(\x010\x01\x12@\n" +
	"\vEvolveAgent\x12\x17.aeonmind.EvolveRequest\x1a\x18.aeonmind.EvolveResponse\x12F\n" +
	"\rOptimizeAgent\x12\x19.aeonmind.OptimizeRequest\x1a\x1a.aeonmind.OptimizeResponse\x12D\n" +
	"\tBroadcast\x12\x1a.aeonmind.BroadcastRequest\x1a\x1b.aeonmind.BroadcastResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.aeonmind.HealthCheckRequest\x1a\x1d.aeonmind.HealthCheckResponseB9Z7github.com/Trancendos/Tranc3/aeonmind/go/proto;aeonmindb\x06proto3"

var (
	file_aeonmind_proto_rawDescOnce sync.Once
	file_aeonmind_proto_rawDescData []byte
)

func file_aeonmind_proto_rawDescGZIP() []byte {
	file_aeonmind_proto_rawDescOnce.Do(func() {
		file_aeonmind_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aeonmind_proto_rawDesc), len(file_aeonmind_proto_rawDesc)))
	})
	return file_aeonmind_proto_rawDescData
}

var file_aeonmind_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_aeonmind_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_aeonmind_proto_goTypes = []any{
	(Tier)(0),                    // 0: aeonmind.Tier
	(SentinelChannel)(0),         // 1: aeonmind.SentinelChannel
	(EntityType)(0),              // 2: aeonmind.EntityType
	(AgentStatus)(0),             // 3: aeonmind.AgentStatus
	(*FluidicState)(nil),         // 4: aeonmind.FluidicState
	(*IntelligenceScore)(nil),    // 5: aeonmind.IntelligenceScore
	(*ScoringWeights)(nil),       // 6: aeonmind.ScoringWeights
	(*DnaVector)(nil),            // 7: aeonmind.DnaVector
	(*QuantumCircuitConfig)(nil), // 8: aeonmind.QuantumCircuitConfig
	(*ReservoirConfig)(nil),      // 9: aeonmind.ReservoirConfig
	(*GeneticConfig)(nil),        // 10: aeonmind.GeneticConfig
	(*AdaptiveConfig)(nil),       // 11: aeonmind.AdaptiveConfig
	(*AiComplexMsg)(nil),         // 12: aeonmind.AiComplexMsg
	(*AgentEntityMsg)(nil),       // 13: aeonmind.AgentEntityMsg
	(*BotServiceMsg)(nil),        // 14: aeonmind.BotServiceMsg
	(*CreateEntityRequest)(nil),  // 15: aeonmind.CreateEntityRequest
	(*CreateEntityResponse)(nil), // 16: aeonmind.CreateEntityResponse
	(*DispatchTaskRequest)(nil),  // 17: aeonmind.DispatchTaskRequest
	(*DispatchTaskResponse)(nil), // 18: aeonmind.DispatchTaskResponse
	(*GetEntityRequest)(nil),     // 19: aeonmind.GetEntityRequest
	(*GetEntityResponse)(nil),    // 20: aeonmind.GetEntityResponse
	(*HealthCheckRequest)(nil),   // 21: aeonmind.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 22: aeonmind.HealthCheckResponse
	(*ListEntitiesRequest)(nil),  // 23: aeonmind.ListEntitiesRequest
	(*ListEntitiesResponse)(nil), // 24: aeonmind.ListEntitiesResponse
	(*BroadcastRequest)(nil),     // 25: aeonmind.BroadcastRequest
	(*BroadcastResponse)(nil),    // 26: aeonmind.BroadcastResponse
	(*EvolveRequest)(nil),        // 27: aeonmind.EvolveRequest
	(*EvolveResponse)(nil),       // 28: aeonmind.EvolveResponse
	(*OptimizeRequest)(nil),      // 29: aeonmind.OptimizeRequest
	(*OptimizeResponse)(nil),     // 30: aeonmind.OptimizeResponse
	nil,                          // 31: aeonmind.AiComplexMsg.MetadataEntry
	nil,                          // 32: aeonmind.AgentEntityMsg.MetadataEntry
	nil,                          // 33: aeonmind.BotServiceMsg.MetadataEntry
	nil,                          // 34: aeonmind.CreateEntityRequest.ConfigEntry
	nil,                          // 35: aeonmind.DispatchTaskRequest.MetadataEntry
}
var file_aeonmind_proto_depIdxs = []int32{
	0,  // 0: aeonmind.AiComplexMsg.tier:type_name -> aeonmind.Tier
	13, // 1: aeonmind.AiComplexMsg.agents:type_name -> aeonmind.AgentEntityMsg
	14, // 2: aeonmind.AiComplexMsg.bots:type_name -> aeonmind.BotServiceMsg
	3,  // 3: aeonmind.AiComplexMsg.status:type_name -> aeonmind.AgentStatus
	31, // 4: aeonmind.AiComplexMsg.metadata:type_name -> aeonmind.AiComplexMsg.MetadataEntry
	0,  // 5: aeonmind.AgentEntityMsg.tier:type_name -> aeonmind.Tier
	4,  // 6: aeonmind.AgentEntityMsg.fluidic_state:type_name -> aeonmind.FluidicState
	7,  // 7: aeonmind.AgentEntityMsg.dna:type_name -> aeonmind.DnaVector
	5,  // 8: aeonmind.AgentEntityMsg.intelligence:type_name -> aeonmind.IntelligenceScore
	3,  // 9: aeonmind.AgentEntityMsg.status:type_name -> aeonmind.AgentStatus
	1,  // 10: aeonmind.AgentEntityMsg.subscriptions:type_name -> aeonmind.SentinelChannel
	32, // 11: aeonmind.AgentEntityMsg.metadata:type_name -> aeonmind.AgentEntityMsg.MetadataEntry
	3,  // 12: aeonmind.BotServiceMsg.status:type_name -> aeonmind.AgentStatus
	33, // 13: aeonmind.BotServiceMsg.metadata:type_name -> aeonmind.BotServiceMsg.MetadataEntry
	2,  // 14: aeonmind.CreateEntityRequest.entity_type:type_name -> aeonmind.EntityType
	0,  // 15: aeonmind.CreateEntityRequest.tier:type_name -> aeonmind.Tier
	34, // 16: aeonmind.CreateEntityRequest.config:type_name -> aeonmind.CreateEntityRequest.ConfigEntry
	35, // 17: aeonmind.DispatchTaskRequest.metadata:type_name -> aeonmind.DispatchTaskRequest.MetadataEntry
	2,  // 18: aeonmind.GetEntityResponse.entity_type:type_name -> aeonmind.EntityType
	2,  // 19: aeonmind.ListEntitiesRequest.entity_type:type_name -> aeonmind.EntityType
	0,  // 20: aeonmind.ListEntitiesRequest.tier:type_name -> aeonmind.Tier
	1,  // 21: aeonmind.BroadcastRequest.channel:type_name -> aeonmind.SentinelChannel
	10, // 22: aeonmind.EvolveRequest.config:type_name -> aeonmind.GeneticConfig
	7,  // 23: aeonmind.EvolveResponse.best_dna:type_name -> aeonmind.DnaVector
	11, // 24: aeonmind.OptimizeRequest.config:type_name -> aeonmind.AdaptiveConfig
	15, // 25: aeonmind.AeonMindOrchestrator.CreateEntity:input_type -> aeonmind.CreateEntityRequest
	19, // 26: aeonmind.AeonMindOrchestrator.GetEntity:input_type -> aeonmind.GetEntityRequest
	23, // 27: aeonmind.AeonMindOrchestrator.ListEntities:input_type -> aeonmind.ListEntitiesRequest
	17, // 28: aeonmind.AeonMindOrchestrator.DispatchTask:input_type -> aeonmind.DispatchTaskRequest
	17, // 29: aeonmind.AeonMindOrchestrator.DispatchBatch:input_type -> aeonmind.DispatchTaskRequest
	27, // 30: aeonmind.AeonMindOrchestrator.EvolveAgent:input_type -> aeonmind.EvolveRequest
	29, // 31: aeonmind.AeonMindOrchestrator.OptimizeAgent:input_type -> aeonmind.OptimizeRequest
	25, // 32: aeonmind.AeonMindOrchestrator.Broadcast:input_type -> aeonmind.BroadcastRequest
	21, // 33: aeonmind.AeonMindOrchestrator.HealthCheck:input_type -> aeonmind.HealthCheckRequest
	16, // 34: aeonmind.AeonMindOrchestrator.CreateEntity:output_type -> aeonmind.CreateEntityResponse
	20, // 35: aeonmind.AeonMindOrchestrator.GetEntity:output_type -> aeonmind.GetEntityResponse
	24, // 36: aeonmind.AeonMindOrchestrator.ListEntities:output_type -> aeonmind.ListEntitiesResponse
	18, // 37: aeonmind.AeonMindOrchestrator.DispatchTask:output_type -> aeonmind.DispatchTaskResponse
	18, // 38: aeonmind.AeonMindOrchestrator.DispatchBatch:output_type -> aeonmind.DispatchTaskResponse
	28, // 39: aeonmind.AeonMindOrchestrator.EvolveAgent:output_type -> aeonmind.EvolveResponse
	30, // 40: aeonmind.AeonMindOrchestrator.OptimizeAgent:output_type -> aeonmind.OptimizeResponse
	26, // 41: aeonmind.AeonMindOrchestrator.Broadcast:output_type -> aeonmind.BroadcastResponse
	22, // 42: aeonmind.AeonMindOrchestrator.HealthCheck:output_type -> aeonmind.HealthCheckResponse
	34, // [34:43] is the sub-list for method output_type
	25, // [25:34] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_aeonmind_proto_init() }
func file_aeonmind_proto_init() {
	if File_aeonmind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aeonmind_proto_rawDesc), len(file_aeonmind_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aeonmind_proto_goTypes,
		DependencyIndexes: file_aeonmind_proto_depIdxs,
		EnumInfos:         file_aeonmind_proto_enumTypes,
		MessageInfos:      file_aeonmind_proto_msgTypes,
	}.Build()
	File_aeonmind_proto = out.File
	file_aeonmind_proto_goTypes = nil
	file_aeonmind_proto_depIdxs = nil
}
