// AeonMind gRPC Protocol Buffer Definitions
// Tranc3 Infinity Ecosystem v0.9.0
//
// Custom Hierarchy:
//   AI    = The overarching ML/LLM Complex (Tier 3)
//   Agent = Lower-level autonomous AI (Tier 4)
//   Bot   = Stateless service worker/function (Tier 5)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: aeonmind.proto

package aeonmind

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AeonMindOrchestrator_CreateEntity_FullMethodName  = "/aeonmind.AeonMindOrchestrator/CreateEntity"
	AeonMindOrchestrator_GetEntity_FullMethodName     = "/aeonmind.AeonMindOrchestrator/GetEntity"
	AeonMindOrchestrator_ListEntities_FullMethodName  = "/aeonmind.AeonMindOrchestrator/ListEntities"
	AeonMindOrchestrator_DispatchTask_FullMethodName  = "/aeonmind.AeonMindOrchestrator/DispatchTask"
	AeonMindOrchestrator_DispatchBatch_FullMethodName = "/aeonmind.AeonMindOrchestrator/DispatchBatch"
	AeonMindOrchestrator_EvolveAgent_FullMethodName   = "/aeonmind.AeonMindOrchestrator/EvolveAgent"
	AeonMindOrchestrator_OptimizeAgent_FullMethodName = "/aeonmind.AeonMindOrchestrator/OptimizeAgent"
	AeonMindOrchestrator_Broadcast_FullMethodName     = "/aeonmind.AeonMindOrchestrator/Broadcast"
	AeonMindOrchestrator_HealthCheck_FullMethodName   = "/aeonmind.AeonMindOrchestrator/HealthCheck"
)

// AeonMindOrchestratorClient is the client API for AeonMindOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AeonMindOrchestratorClient interface {
	// Entity Management
	CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error)
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	ListEntities(ctx context.Context, in *ListEntitiesRequest, opts ...grpc.CallOption) (*ListEntitiesResponse, error)
	// Task Dispatch
	DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error)
	DispatchBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DispatchTaskRequest, DispatchTaskResponse], error)
	// Evolution & Optimization
	EvolveAgent(ctx context.Context, in *EvolveRequest, opts ...grpc.CallOption) (*EvolveResponse, error)
	OptimizeAgent(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error)
	// Sentinel Broadcasting
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error)
	// Health & Monitoring
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aeonMindOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewAeonMindOrchestratorClient(cc grpc.ClientConnInterface) AeonMindOrchestratorClient {
	return &aeonMindOrchestratorClient{cc}
}

func (c *aeonMindOrchestratorClient) CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEntityResponse)
	err := c.cc.Invoke(ctx, AeonMindOrchestrator_CreateEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonMindOrchestratorClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, AeonMindOrchestrator_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonMindOrchestratorClient) ListEntities(ctx context.Context, in *ListEntitiesRequest, opts ...grpc.CallOption) (*ListEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntitiesResponse)
	err := c.cc.Invoke(ctx, AeonMindOrchestrator_ListEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonMindOrchestratorClient) DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTaskResponse)
	err := c.cc.Invoke(ctx, AeonMindOrchestrator_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonMindOrchestratorClient) DispatchBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DispatchTaskRequest, DispatchTaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AeonMindOrchestrator_ServiceDesc.Streams[0], AeonMindOrchestrator_DispatchBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DispatchTaskRequest, DispatchTaskResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AeonMindOrchestrator_DispatchBatchClient = grpc.BidiStreamingClient[DispatchTaskRequest, DispatchTaskResponse]

func (c *aeonMindOrchestratorClient) EvolveAgent(ctx context.Context, in *EvolveRequest, opts ...grpc.CallOption) (*EvolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvolveResponse)
	err := c.cc.Invoke(ctx, AeonMindOrchestrator_EvolveAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonMindOrchestratorClient) OptimizeAgent(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeResponse)
	err := c.cc.Invoke(ctx, AeonMindOrchestrator_OptimizeAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonMindOrchestratorClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastResponse)
	err := c.cc.Invoke(ctx, AeonMindOrchestrator_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeonMindOrchestratorClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AeonMindOrchestrator_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AeonMindOrchestratorServer is the server API for AeonMindOrchestrator service.
// All implementations must embed UnimplementedAeonMindOrchestratorServer
// for forward compatibility.
type AeonMindOrchestratorServer interface {
	// Entity Management
	CreateEntity(context.Context, *CreateEntityRequest) (*CreateEntityResponse, error)
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	ListEntities(context.Context, *ListEntitiesRequest) (*ListEntitiesResponse, error)
	// Task Dispatch
	DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error)
	DispatchBatch(grpc.BidiStreamingServer[DispatchTaskRequest, DispatchTaskResponse]) error
	// Evolution & Optimization
	EvolveAgent(context.Context, *EvolveRequest) (*EvolveResponse, error)
	OptimizeAgent(context.Context, *OptimizeRequest) (*OptimizeResponse, error)
	// Sentinel Broadcasting
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error)
	// Health & Monitoring
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAeonMindOrchestratorServer()
}

// UnimplementedAeonMindOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAeonMindOrchestratorServer struct{}

func (UnimplementedAeonMindOrchestratorServer) CreateEntity(context.Context, *CreateEntityRequest) (*CreateEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEntity not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) ListEntities(context.Context, *ListEntitiesRequest) (*ListEntitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntities not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) DispatchBatch(grpc.BidiStreamingServer[DispatchTaskRequest, DispatchTaskResponse]) error {
	return status.Error(codes.Unimplemented, "method DispatchBatch not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) EvolveAgent(context.Context, *EvolveRequest) (*EvolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvolveAgent not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) OptimizeAgent(context.Context, *OptimizeRequest) (*OptimizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OptimizeAgent not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAeonMindOrchestratorServer) mustEmbedUnimplementedAeonMindOrchestratorServer() {}
func (UnimplementedAeonMindOrchestratorServer) testEmbeddedByValue()                              {}

// UnsafeAeonMindOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AeonMindOrchestratorServer will
// result in compilation errors.
type UnsafeAeonMindOrchestratorServer interface {
	mustEmbedUnimplementedAeonMindOrchestratorServer()
}

func RegisterAeonMindOrchestratorServer(s grpc.ServiceRegistrar, srv AeonMindOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedAeonMindOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AeonMindOrchestrator_ServiceDesc, srv)
}

func _AeonMindOrchestrator_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonMindOrchestratorServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonMindOrchestrator_CreateEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonMindOrchestratorServer).CreateEntity(ctx, req.(*CreateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonMindOrchestrator_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonMindOrchestratorServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonMindOrchestrator_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonMindOrchestratorServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonMindOrchestrator_ListEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonMindOrchestratorServer).ListEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonMindOrchestrator_ListEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonMindOrchestratorServer).ListEntities(ctx, req.(*ListEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonMindOrchestrator_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonMindOrchestratorServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonMindOrchestrator_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonMindOrchestratorServer).DispatchTask(ctx, req.(*DispatchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonMindOrchestrator_DispatchBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AeonMindOrchestratorServer).DispatchBatch(&grpc.GenericServerStream[DispatchTaskRequest, DispatchTaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AeonMindOrchestrator_DispatchBatchServer = grpc.BidiStreamingServer[DispatchTaskRequest, DispatchTaskResponse]

func _AeonMindOrchestrator_EvolveAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonMindOrchestratorServer).EvolveAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonMindOrchestrator_EvolveAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonMindOrchestratorServer).EvolveAgent(ctx, req.(*EvolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonMindOrchestrator_OptimizeAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonMindOrchestratorServer).OptimizeAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonMindOrchestrator_OptimizeAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonMindOrchestratorServer).OptimizeAgent(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonMindOrchestrator_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonMindOrchestratorServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonMindOrchestrator_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonMindOrchestratorServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeonMindOrchestrator_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeonMindOrchestratorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeonMindOrchestrator_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeonMindOrchestratorServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AeonMindOrchestrator_ServiceDesc is the grpc.ServiceDesc for AeonMindOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AeonMindOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aeonmind.AeonMindOrchestrator",
	HandlerType: (*AeonMindOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity",
			Handler:    _AeonMindOrchestrator_CreateEntity_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _AeonMindOrchestrator_GetEntity_Handler,
		},
		{
			MethodName: "ListEntities",
			Handler:    _AeonMindOrchestrator_ListEntities_Handler,
		},
		{
			MethodName: "DispatchTask",
			Handler:    _AeonMindOrchestrator_DispatchTask_Handler,
		},
		{
			MethodName: "EvolveAgent",
			Handler:    _AeonMindOrchestrator_EvolveAgent_Handler,
		},
		{
			MethodName: "OptimizeAgent",
			Handler:    _AeonMindOrchestrator_OptimizeAgent_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _AeonMindOrchestrator_Broadcast_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AeonMindOrchestrator_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DispatchBatch",
			Handler:       _AeonMindOrchestrator_DispatchBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "aeonmind.proto",
}
