# flux/base/configmaps.yaml
# Shared configuration for all nanoservices
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tranc3-config
  namespace: tranc3
  annotations:
    trivy-operator.aquasecurity.github.io/skip-checks: KSV104
data:
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  SHM_DIR: "/dev/shm"
  SHM_PREFIX: "nsa_"
  FORGEJO_URL: "https://forgejo.local"
  FORGEJO_REPO: "Trancendos/Tranc3"
  OLLAMA_HOST: "http://ollama:11434"
  REDPANDA_BROKERS: "redpanda:9092"
  OPA_URL: "http://opa:8181"
  NSA_HTTP_PORT: "7780"
  DNF_HTTP_PORT: "8080"
  SHI_HTTP_PORT: "8000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tranc3-dev-config
  namespace: tranc3
  annotations:
    trivy-operator.aquasecurity.github.io/skip-checks: KSV104
data:
  LOG_LEVEL: "DEBUG"
  ENVIRONMENT: "development"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tranc3-staging-config
  namespace: tranc3
  annotations:
    trivy-operator.aquasecurity.github.io/skip-checks: KSV104
data:
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "staging"
