# Re-export from canonical location — Dimensional.architecture is the source of truth.
from Dimensional.architecture.oci_adaptive_provider import (  # noqa: F401  # codeql[py/unused-import]
    CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    CIRCUIT_BREAKER_RECOVERY_SECONDS,
    IDLE_RECLAIM_THRESHOLD_CPU_PCT,
    KEEPALIVE_INTERVAL_SECONDS,
    MAX_RETRY_ATTEMPTS,
    OCI_FREE_TIER_LIMITS,
    REQUEST_TIMEOUT_SECONDS,
    RETRY_BACKOFF_BASE,
    AdaptiveInstanceDatum,
    AdaptiveProviderConfig,
    CircuitBreaker,
    CircuitState,
    MinioConfig,
    OciAdaptiveProvider,
    OciConfig,
    OciKeepaliveWorker,
    OciQuotaTracker,
    PersistentInfrastructureDatum,
    R2Config,
    StorageTier,
    SystemMode,
    _aws_sig4_sign,  # noqa: F401  # codeql[py/unused-import]
)
