export interface RouteMeta {
  title: string
  label: string
}

const ROUTE_META: Record<string, RouteMeta> = {
  '/': { title: 'Home', label: 'Home page' },
  '/chat': { title: 'Chat', label: 'Chat page' },
  '/dashboard': { title: 'Dashboard', label: 'Dashboard page' },
  '/mission': { title: 'Mission', label: 'Mission page' },
  '/spark': { title: 'The Spark', label: 'The Spark page' },
  '/status': { title: 'Status', label: 'Status page' },
  '/compliance': { title: 'Compliance', label: 'Compliance page' },
  '/grid': { title: 'Digital Grid', label: 'Digital Grid page' },
  '/notifications': { title: 'Alerts', label: 'Alerts page' },
  '/services': { title: 'Services', label: 'Services page' },
  '/ai-providers': { title: 'AI Providers', label: 'AI Providers page' },
  '/storage': { title: 'Storage', label: 'Storage page' },
  '/search': { title: 'Search', label: 'Search page' },
  '/queue': { title: 'Queue', label: 'Queue page' },
  '/admin': { title: 'Admin', label: 'Admin page' },
  '/workers': { title: 'Workers', label: 'Workers page' },
  '/the-lab': { title: 'The Lab', label: 'The Lab page' },
  '/the-dutchy': { title: 'The Dutchy', label: 'The Dutchy page' },
  '/turings-hub': { title: "Turing's Hub", label: "Turing's Hub page" },
  '/deep-agents': { title: 'Deep Agents', label: 'Deep Agents page' },
  '/audit': { title: 'Audit Log', label: 'Audit Log page' },
  '/langchain': { title: 'LangChain', label: 'LangChain page' },
  '/model-router': { title: 'Model Router', label: 'Model Router page' },
  '/ledger': { title: 'Ledger', label: 'Ledger page' },
  '/topology': { title: 'Topology', label: 'Topology page' },
  '/vault': { title: 'The Void', label: 'The Void page' },
  '/analytics': { title: 'Analytics', label: 'Analytics page' },
  '/config': { title: 'Config Store', label: 'Config Store page' },
  '/cron': { title: 'ChronosSphere', label: 'ChronosSphere page' },
  '/cache': { title: 'Cache', label: 'Cache page' },
  '/rate-limit': { title: 'Rate Limiter', label: 'Rate Limiter page' },
  '/geo': { title: 'Geo Service', label: 'Geo Service page' },
  '/email-svc': { title: 'Email Service', label: 'Email Service page' },
  '/sms': { title: 'SMS Gateway', label: 'SMS Gateway page' },
  '/hive': { title: 'The HIVE', label: 'The HIVE page' },
  '/gbrain': { title: 'GBrain', label: 'GBrain page' },
  '/devocity': { title: 'DevOcity', label: 'DevOcity page' },
  '/backup': { title: 'Backup', label: 'Backup page' },
  '/cdn': { title: 'CDN', label: 'CDN page' },
  '/infinity-portal': { title: 'Infinity Portal', label: 'Infinity Portal page' },
  '/swarm-coordinator': { title: 'Swarm Coordinator', label: 'Swarm Coordinator page' },
  '/dimensional-nexus': { title: 'Dimensional Nexus', label: 'Dimensional Nexus page' },
  '/sashas-photo-studio': { title: 'Sashas Photo Studio', label: 'Sashas Photo Studio page' },
  '/imind': { title: 'I-Mind', label: 'I-Mind page' },
  '/resonate': { title: 'Resonate', label: 'Resonate page' },
  '/tranquility': { title: 'Tranquility', label: 'Tranquility page' },
  '/taimra': { title: 'tAimra', label: 'tAimra page' },
  '/the-studio': { title: 'The Studio', label: 'The Studio page' },
  '/the-academy': { title: 'The Academy', label: 'The Academy page' },
  '/warp-radio': { title: 'Warp Radio', label: 'Warp Radio page' },
  '/gateway': { title: 'Gateway', label: 'Gateway page' },
  '/sentinel-station': { title: 'Sentinel Station', label: 'Sentinel Station page' },
  '/ice-box': { title: 'The Ice Box', label: 'The Ice Box page' },
  '/tranceflow': { title: 'TranceFlow', label: 'TranceFlow page' },
  '/tateking': { title: 'TateKing', label: 'TateKing page' },
  '/vrar3d': { title: 'VRAR3D', label: 'VRAR3D page' },
  '/infinity-one': { title: 'Infinity One', label: 'Infinity One page' },
  '/infinity-admin': { title: 'Infinity Admin', label: 'Infinity Admin page' },
  '/infinity-shards': { title: 'Infinity Shards', label: 'Infinity Shards page' },
  '/infinity-bridge': { title: 'Infinity Bridge', label: 'Infinity Bridge page' },
  '/users-service': { title: 'Users Service', label: 'Users Service page' },
  '/settings': { title: 'Settings', label: 'Settings page' },
  '/login': { title: 'Sign In', label: 'Sign in page' },
  '/ux-showcase': { title: 'UX Showcase', label: 'UX Showcase page' },
}

export default ROUTE_META
