-- Generated by scripts/build_domain_model.py — do not edit.
--
-- Schema, constraints and row-level security for the Trancendos domain model.
-- Regenerate rather than patching: this file is derived from src/domain/build.py,
-- which reads the platform's own registers.
--
-- Row-level security below depends on two session settings the application must
-- set per request, after authenticating:
--
--   SET LOCAL trancendos.location = '<Location name>';
--   SET LOCAL trancendos.role     = '<role class>';
--
--   The role is a CLASS, not one of the 56 Job Description titles in
--   module_roles(). 'Location seat' and 'The Ice Box seat' are generic over
--   every Location, which is what lets one rule cover all 43; no Job
--   Description string will ever equal them. This header said
--   '<Job Description>' until 2026-09-28, which made every non-wildcard
--   policy read as unsatisfiable to anyone setting a real seat title.
--
-- LOCAL, so the setting dies with the transaction rather than leaking into the
-- next request that borrows the same pooled connection. A policy that reads an
-- unset setting sees NULL and matches nothing, which is the correct failure.


-- ── Location (The Citadel) ──────────────────────────────
CREATE SCHEMA IF NOT EXISTS the_citadel;
-- One of the platform's named Locations.
-- Source: src/entities/platform.py::PLATFORM_ENTITIES
CREATE TABLE IF NOT EXISTS the_citadel.location (
    id BIGSERIAL PRIMARY KEY,
    pid TEXT NOT NULL,
    name TEXT NOT NULL,
    pillar TEXT NOT NULL,
    primary_function TEXT,
    online_mode TEXT,
    offline_mode TEXT,
    worker_path TEXT,
    worker_port BIGINT,
    status TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS location_pid_key ON the_citadel.location (pid);


-- ── AI (The Citadel) ──────────────────────────────
CREATE SCHEMA IF NOT EXISTS the_citadel;
-- A named AI, at one of the three orchestration tiers.
-- Source: src/entities/platform.py + src/personality/profiles/
CREATE TABLE IF NOT EXISTS the_citadel.ai (
    id BIGSERIAL PRIMARY KEY,
    aid TEXT NOT NULL,
    name TEXT NOT NULL,
    tier TEXT NOT NULL,
    base_model TEXT,
    profile_ref TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS ai_aid_key ON the_citadel.ai (aid);


-- ── RoleSeat (The Town Hall) ──────────────────────────────
CREATE SCHEMA IF NOT EXISTS the_town_hall;
-- One Job Description at one Location — the platform's module role.
-- Source: src/entities/platform.py::get_seats
CREATE TABLE IF NOT EXISTS the_town_hall.role_seat (
    id BIGSERIAL PRIMARY KEY,
    seat_id TEXT NOT NULL,
    location TEXT NOT NULL,
    job_description TEXT NOT NULL,
    designed_for TEXT,
    is_primary BOOLEAN,
    mandate TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS role_seat_seat_id_key ON the_town_hall.role_seat (seat_id);


-- ── Container (The Ice Box) ──────────────────────────────
CREATE SCHEMA IF NOT EXISTS the_ice_box;
-- A containerised unit. Jurisdiction may be unknown; custody may not.
-- Source: src/cmdb/containers.py
CREATE TABLE IF NOT EXISTS the_ice_box.container (
    id BIGSERIAL PRIMARY KEY,
    ci_id TEXT NOT NULL,
    service TEXT NOT NULL,
    image TEXT,
    provenance TEXT NOT NULL,
    runs_as_root BOOLEAN NOT NULL,
    sbom_ref TEXT,
    sbom_scope TEXT,
    ports JSONB,
    volumes JSONB
);
CREATE UNIQUE INDEX IF NOT EXISTS container_ci_id_key ON the_ice_box.container (ci_id);


-- ── Datastore (The Citadel) ──────────────────────────────
CREATE SCHEMA IF NOT EXISTS the_citadel;
-- A database or cache the estate opens.
-- Source: src/cmdb/datastores.py
CREATE TABLE IF NOT EXISTS the_citadel.datastore (
    id BIGSERIAL PRIMARY KEY,
    ci_id TEXT NOT NULL,
    name TEXT NOT NULL,
    engine TEXT NOT NULL,
    locator TEXT,
    file_backed BOOLEAN NOT NULL,
    disposition TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS datastore_ci_id_key ON the_citadel.datastore (ci_id);


-- ── Associations ────────────────────────────────────────
-- Each Location defines the seats that are its module roles.
ALTER TABLE the_town_hall.role_seat ADD COLUMN IF NOT EXISTS location_has_seats_id BIGINT REFERENCES the_citadel.location(id);
-- Required by the model. Backfill the_town_hall.role_seat.location_has_seats_id for any existing rows, then:
ALTER TABLE the_town_hall.role_seat ALTER COLUMN location_has_seats_id SET NOT NULL;

-- Mutable at runtime via the Role Assignment Registry.
ALTER TABLE the_town_hall.role_seat ADD COLUMN IF NOT EXISTS seat_held_by_ai_id BIGINT REFERENCES the_citadel.ai(id);

-- Always The Ice Box. Required: a container with no custodian is the one case the shared-jurisdiction model exists to prevent.
ALTER TABLE the_ice_box.container ADD COLUMN IF NOT EXISTS container_custodied_by_id BIGINT REFERENCES the_citadel.location(id);
-- Required by the model. Backfill the_ice_box.container.container_custodied_by_id for any existing rows, then:
ALTER TABLE the_ice_box.container ALTER COLUMN container_custodied_by_id SET NOT NULL;

-- Whose code runs inside. Optional on purpose: 86 containers are third-party images running nobody's code here.
ALTER TABLE the_ice_box.container ADD COLUMN IF NOT EXISTS container_under_jurisdiction_of_id BIGINT REFERENCES the_citadel.location(id);

-- 114 are currently unrouted and await a Town Hall decision.
ALTER TABLE the_citadel.datastore ADD COLUMN IF NOT EXISTS datastore_owned_by_id BIGINT REFERENCES the_citadel.location(id);

-- A file-backed store inside a container's writable layer dies with the container unless a volume is mounted. This edge is what makes that answerable per store rather than per service.
ALTER TABLE the_citadel.datastore ADD COLUMN IF NOT EXISTS container_runs_datastore_id BIGINT REFERENCES the_ice_box.container(id);

-- The dependency graph blast radius is computed over.
CREATE TABLE IF NOT EXISTS the_citadel.location_location (
    source_location_id BIGINT NOT NULL REFERENCES the_citadel.location(id) ON DELETE CASCADE,
    target_location_id BIGINT NOT NULL REFERENCES the_citadel.location(id) ON DELETE CASCADE,
    PRIMARY KEY (source_location_id, target_location_id)
);
ALTER TABLE the_citadel.location_location ENABLE ROW LEVEL SECURITY;
ALTER TABLE the_citadel.location_location FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS location_location_read ON the_citadel.location_location;
CREATE POLICY location_location_read ON the_citadel.location_location FOR SELECT USING (true);  -- the graph itself is not sensitive; its endpoints carry their own policies

-- ── Row-level security ──────────────────────────────────
ALTER TABLE the_citadel.location ENABLE ROW LEVEL SECURITY;
ALTER TABLE the_citadel.location FORCE ROW LEVEL SECURITY;
-- The Location register is readable platform-wide.
-- members: *
DROP POLICY IF EXISTS location_p0_all ON the_citadel.location;
DROP POLICY IF EXISTS location_p0_all_r ON the_citadel.location;
DROP POLICY IF EXISTS location_p0_all_w ON the_citadel.location;
CREATE POLICY location_p0_all ON the_citadel.location FOR SELECT USING ((true) AND (true));

-- A Location's own seats may edit its operational fields.
-- members: primaryFunction, onlineMode, offlineMode, status
DROP POLICY IF EXISTS location_p1_location_seat ON the_citadel.location;
DROP POLICY IF EXISTS location_p1_location_seat_r ON the_citadel.location;
DROP POLICY IF EXISTS location_p1_location_seat_w ON the_citadel.location;
CREATE POLICY location_p1_location_seat_r ON the_citadel.location FOR SELECT USING ((current_setting('trancendos.role', true) = 'Location seat') AND (name = current_setting('trancendos.location', true)));
CREATE POLICY location_p1_location_seat_w ON the_citadel.location FOR UPDATE USING ((current_setting('trancendos.role', true) = 'Location seat') AND (name = current_setting('trancendos.location', true))) WITH CHECK ((current_setting('trancendos.role', true) = 'Location seat') AND (name = current_setting('trancendos.location', true)));
-- column-level grant (RLS filters rows, not columns):
-- GRANT SELECT, UPDATE (primary_function, online_mode, offline_mode, status) ON the_citadel.location TO <role>;

ALTER TABLE the_citadel.ai ENABLE ROW LEVEL SECURITY;
ALTER TABLE the_citadel.ai FORCE ROW LEVEL SECURITY;
-- members: *
DROP POLICY IF EXISTS ai_p0_all ON the_citadel.ai;
DROP POLICY IF EXISTS ai_p0_all_r ON the_citadel.ai;
DROP POLICY IF EXISTS ai_p0_all_w ON the_citadel.ai;
CREATE POLICY ai_p0_all ON the_citadel.ai FOR SELECT USING ((true) AND (true));

-- Turing's Hub is the AI creation centre and owns personality assignment.
-- members: profileRef, baseModel
DROP POLICY IF EXISTS ai_p1_turing_s_hub_seat ON the_citadel.ai;
DROP POLICY IF EXISTS ai_p1_turing_s_hub_seat_r ON the_citadel.ai;
DROP POLICY IF EXISTS ai_p1_turing_s_hub_seat_w ON the_citadel.ai;
CREATE POLICY ai_p1_turing_s_hub_seat_r ON the_citadel.ai FOR SELECT USING ((current_setting('trancendos.role', true) = 'Turing''s Hub seat') AND (true));
CREATE POLICY ai_p1_turing_s_hub_seat_w ON the_citadel.ai FOR UPDATE USING ((current_setting('trancendos.role', true) = 'Turing''s Hub seat') AND (true)) WITH CHECK ((current_setting('trancendos.role', true) = 'Turing''s Hub seat') AND (true));
-- column-level grant (RLS filters rows, not columns):
-- GRANT SELECT, UPDATE (profile_ref, base_model) ON the_citadel.ai TO <role>;

ALTER TABLE the_town_hall.role_seat ENABLE ROW LEVEL SECURITY;
ALTER TABLE the_town_hall.role_seat FORCE ROW LEVEL SECURITY;
-- members: *
DROP POLICY IF EXISTS role_seat_p0_all ON the_town_hall.role_seat;
DROP POLICY IF EXISTS role_seat_p0_all_r ON the_town_hall.role_seat;
DROP POLICY IF EXISTS role_seat_p0_all_w ON the_town_hall.role_seat;
CREATE POLICY role_seat_p0_all ON the_town_hall.role_seat FOR SELECT USING ((true) AND (true));

-- Assignment is a governance decision and belongs to the Town Hall.
-- members: *
DROP POLICY IF EXISTS role_seat_p1_the_town_hall_seat ON the_town_hall.role_seat;
DROP POLICY IF EXISTS role_seat_p1_the_town_hall_seat_r ON the_town_hall.role_seat;
DROP POLICY IF EXISTS role_seat_p1_the_town_hall_seat_w ON the_town_hall.role_seat;
CREATE POLICY role_seat_p1_the_town_hall_seat_r ON the_town_hall.role_seat FOR SELECT USING ((current_setting('trancendos.role', true) = 'The Town Hall seat') AND (true));
CREATE POLICY role_seat_p1_the_town_hall_seat_w ON the_town_hall.role_seat FOR UPDATE USING ((current_setting('trancendos.role', true) = 'The Town Hall seat') AND (true)) WITH CHECK ((current_setting('trancendos.role', true) = 'The Town Hall seat') AND (true));

ALTER TABLE the_ice_box.container ENABLE ROW LEVEL SECURITY;
ALTER TABLE the_ice_box.container FORCE ROW LEVEL SECURITY;
-- members: service, image, provenance
DROP POLICY IF EXISTS container_p0_all ON the_ice_box.container;
DROP POLICY IF EXISTS container_p0_all_r ON the_ice_box.container;
DROP POLICY IF EXISTS container_p0_all_w ON the_ice_box.container;
CREATE POLICY container_p0_all ON the_ice_box.container FOR SELECT USING ((true) AND (true));
-- column-level grant (RLS filters rows, not columns):
-- GRANT SELECT (service, image, provenance) ON the_ice_box.container TO <role>;

-- The custodian of containment may edit every container record.
-- members: *
DROP POLICY IF EXISTS container_p1_the_ice_box_seat ON the_ice_box.container;
DROP POLICY IF EXISTS container_p1_the_ice_box_seat_r ON the_ice_box.container;
DROP POLICY IF EXISTS container_p1_the_ice_box_seat_w ON the_ice_box.container;
CREATE POLICY container_p1_the_ice_box_seat_r ON the_ice_box.container FOR SELECT USING ((current_setting('trancendos.role', true) = 'The Ice Box seat') AND (true));
CREATE POLICY container_p1_the_ice_box_seat_w ON the_ice_box.container FOR UPDATE USING ((current_setting('trancendos.role', true) = 'The Ice Box seat') AND (true)) WITH CHECK ((current_setting('trancendos.role', true) = 'The Ice Box seat') AND (true));

-- A Location sees its own containers in full detail.
-- members: service, image, sbomRef, ports
DROP POLICY IF EXISTS container_p2_location_seat ON the_ice_box.container;
DROP POLICY IF EXISTS container_p2_location_seat_r ON the_ice_box.container;
DROP POLICY IF EXISTS container_p2_location_seat_w ON the_ice_box.container;
CREATE POLICY container_p2_location_seat ON the_ice_box.container FOR SELECT USING ((current_setting('trancendos.role', true) = 'Location seat') AND (container_under_jurisdiction_of_id IN (SELECT id FROM the_citadel.location WHERE name = current_setting('trancendos.location', true))));
-- column-level grant (RLS filters rows, not columns):
-- GRANT SELECT (service, image, sbom_ref, ports) ON the_ice_box.container TO <role>;

ALTER TABLE the_citadel.datastore ENABLE ROW LEVEL SECURITY;
ALTER TABLE the_citadel.datastore FORCE ROW LEVEL SECURITY;
-- members: name, engine, fileBacked
DROP POLICY IF EXISTS datastore_p0_all ON the_citadel.datastore;
DROP POLICY IF EXISTS datastore_p0_all_r ON the_citadel.datastore;
DROP POLICY IF EXISTS datastore_p0_all_w ON the_citadel.datastore;
CREATE POLICY datastore_p0_all ON the_citadel.datastore FOR SELECT USING ((true) AND (true));
-- column-level grant (RLS filters rows, not columns):
-- GRANT SELECT (name, engine, file_backed) ON the_citadel.datastore TO <role>;

-- members: *
DROP POLICY IF EXISTS datastore_p1_the_citadel_seat ON the_citadel.datastore;
DROP POLICY IF EXISTS datastore_p1_the_citadel_seat_r ON the_citadel.datastore;
DROP POLICY IF EXISTS datastore_p1_the_citadel_seat_w ON the_citadel.datastore;
CREATE POLICY datastore_p1_the_citadel_seat_r ON the_citadel.datastore FOR SELECT USING ((current_setting('trancendos.role', true) = 'The Citadel seat') AND (true));
CREATE POLICY datastore_p1_the_citadel_seat_w ON the_citadel.datastore FOR UPDATE USING ((current_setting('trancendos.role', true) = 'The Citadel seat') AND (true)) WITH CHECK ((current_setting('trancendos.role', true) = 'The Citadel seat') AND (true));
