"""
Adaptive Blueprint Engine — Smart Deployment Templates
=======================================================
Platform-agnostic deployment blueprint generator. Replaces GitHub Actions
and Cloudflare Workers with self-sovereign Python/FastAPI worker templates.

Standing directive: "One master worker with smart adaptive templates of tasks
and processes that they can achieve."

Blueprint types:
  FASTAPI_WORKER    — FastAPI + uvicorn worker (standard; replaces CF Worker)
  PYTHON_FUNCTION   — Async function handler (event-driven; no HTTP overhead)
  STATIC_SITE       — Nginx-served static assets (no compute)
  SCHEDULED_TASK    — Cron-style recurring task (replaces GH Actions workflow)
  STREAM_PROCESSOR  — Real-time event/SSE stream handler
  PROXY_GATEWAY     — Reverse proxy / rate-limiting gateway

Each blueprint is parameterised and renders Python source + Dockerfile +
docker-compose snippet that can be deployed to any free-tier host.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional


class BlueprintType(str, Enum):
    """Supported deployment blueprint types generated by BlueprintEngine."""

    FASTAPI_WORKER = "fastapi_worker"
    PYTHON_FUNCTION = "python_function"
    STATIC_SITE = "static_site"
    SCHEDULED_TASK = "scheduled_task"
    STREAM_PROCESSOR = "stream_processor"
    PROXY_GATEWAY = "proxy_gateway"


@dataclass
class BlueprintSpec:
    """Specification for generating a worker blueprint."""

    name: str  # e.g. "analytics-service"
    blueprint_type: BlueprintType
    port: int = 8000
    description: str = ""
    env_vars: List[str] = field(default_factory=list)  # required env var names
    dependencies: List[str] = field(default_factory=list)  # pip packages
    schedule: Optional[str] = None  # cron expression for SCHEDULED_TASK
    routes: List[Dict[str, str]] = field(default_factory=list)  # [{path, method, description}]
    health_entity: Optional[str] = None  # Trancendos entity name for health endpoint
    platform_target: str = "fly_io"  # preferred deployment target


@dataclass
class RenderedBlueprint:
    """Output from BlueprintEngine.render()."""

    spec: BlueprintSpec
    worker_py: str
    dockerfile: str
    compose_snippet: str
    requirements_txt: str
    forgejo_workflow: str  # .forgejo/workflows/<name>.yml


class BlueprintEngine:
    """
    Generates self-hosted Python worker code from BlueprintSpec.

    All generated workers:
      - Use FastAPI / asyncio (zero-cost, self-hosted)
      - Never reference GitHub Actions or Cloudflare Workers
      - Include zero-cost health endpoint with entity block
      - Include structured JSON logging
      - Include graceful shutdown
      - Include JWT validation via environment variable (no hardcoded secrets)
    """

    BASE_REQUIREMENTS = [
        "fastapi>=0.115.0",
        "uvicorn[standard]>=0.30.0",
        "httpx>=0.27.0",
        "pydantic>=2.7.0",
        "python-dotenv>=1.0.0",
    ]

    def render(self, spec: BlueprintSpec) -> RenderedBlueprint:
        """Render all artefacts for *spec* and return a fully populated RenderedBlueprint."""
        worker_py = self._render_worker(spec)
        dockerfile = self._render_dockerfile(spec)
        compose_snippet = self._render_compose(spec)
        requirements_txt = self._render_requirements(spec)
        forgejo_workflow = self._render_forgejo_workflow(spec)
        return RenderedBlueprint(
            spec=spec,
            worker_py=worker_py,
            dockerfile=dockerfile,
            compose_snippet=compose_snippet,
            requirements_txt=requirements_txt,
            forgejo_workflow=forgejo_workflow,
        )

    # ------------------------------------------------------------------
    # worker.py
    # ------------------------------------------------------------------

    def _render_worker(self, spec: BlueprintSpec) -> str:
        """Generate the main worker.py source for *spec* (dispatches to type-specific renderers)."""
        entity_block = ""
        if spec.health_entity:
            entity_block = f'    "entity": "{spec.health_entity}",'

        extra_routes = "\n".join(self._render_route(r, spec) for r in spec.routes)

        if spec.blueprint_type == BlueprintType.SCHEDULED_TASK:
            return self._render_scheduled_task(spec)

        if spec.blueprint_type == BlueprintType.STREAM_PROCESSOR:
            return self._render_stream_processor(spec)

        return textwrap.dedent(f"""\
            \"\"\"
            {spec.name} — {spec.description or spec.blueprint_type.value}

            Generated by Tranc3 Master Worker Blueprint Engine.
            Self-hosted Python/FastAPI worker — zero cost.
            Deployment target: {spec.platform_target}
            \"\"\"
            from __future__ import annotations

            import logging
            import os
            import time
            import uuid
            from contextlib import asynccontextmanager
            from typing import Any, Dict

            import uvicorn
            from fastapi import FastAPI, HTTPException, Request
            from fastapi.middleware.cors import CORSMiddleware
            from fastapi.responses import JSONResponse

            logging.basicConfig(
                level=logging.INFO,
                format="%(asctime)s %(name)s %(levelname)s %(message)s",
            )
            logger = logging.getLogger("{spec.name}")

            # ---------------------------------------------------------------------------
            # Configuration — ALL from environment variables (no hardcoded secrets)
            # ---------------------------------------------------------------------------
            PORT = int(os.environ.get("PORT", {spec.port}))
            SERVICE_NAME = os.environ.get("SERVICE_NAME", "{spec.name}")
            ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")

            # Validate required env vars at startup
            _REQUIRED_ENV = {spec.env_vars!r}
            for _var in _REQUIRED_ENV:
                if not os.environ.get(_var):
                    raise EnvironmentError(
                        f"Required environment variable {{_var!r}} is not set. "
                        "Cannot start {spec.name}."
                    )

            _start_time = time.monotonic()
            _request_count = 0


            @asynccontextmanager
            async def lifespan(app: FastAPI):
                logger.info("%s starting on port %d (env=%s)", SERVICE_NAME, PORT, ENVIRONMENT)
                yield
                logger.info("%s shutting down", SERVICE_NAME)


            app = FastAPI(title="{spec.name}", version="1.0.0", lifespan=lifespan)
            app.add_middleware(
                CORSMiddleware,
                allow_origins=os.environ.get("ALLOWED_ORIGINS", "").split(","),
                allow_methods=["*"],
                allow_headers=["*"],
            )


            @app.middleware("http")
            async def request_id_middleware(request: Request, call_next):
                global _request_count
                _request_count += 1
                request.state.request_id = str(uuid.uuid4())[:8]
                response = await call_next(request)
                response.headers["X-Request-ID"] = request.state.request_id
                return response


            @app.get("/health")
            async def health() -> Dict[str, Any]:
                return {{
                    "status": "healthy",
                    "service": SERVICE_NAME,
                    "environment": ENVIRONMENT,
                    "uptime_seconds": round(time.monotonic() - _start_time, 1),
                    "request_count": _request_count,
                    {entity_block}
                }}

            {extra_routes}

            if __name__ == "__main__":
                uvicorn.run("worker:app", host="0.0.0.0", port=PORT, reload=False)
            """)

    def _render_route(self, route: Dict[str, str], spec: BlueprintSpec) -> str:
        """Render a single FastAPI route handler stub from a route descriptor dict."""
        path = route.get("path", "/")
        method = route.get("method", "GET").lower()
        description = route.get("description", "")
        func_name = (
            path.strip("/").replace("/", "_").replace("-", "_").replace("{", "").replace("}", "")
            or "index"
        )
        return textwrap.dedent(f"""\
            @app.{method}("{path}", summary="{description}")
            async def {func_name}(request: Request) -> Dict[str, Any]:
                return {{"path": "{path}", "method": "{method.upper()}", "service": SERVICE_NAME}}
            """)

    def _render_scheduled_task(self, spec: BlueprintSpec) -> str:
        """Render a cron-style asyncio loop worker — replaces GitHub Actions scheduled runs."""
        schedule = spec.schedule or "0 * * * *"
        return textwrap.dedent(f"""\
            \"\"\"
            {spec.name} — Scheduled Task ({schedule})

            Generated by Tranc3 Master Worker Blueprint Engine.
            Runs as a background asyncio loop — zero cost, no GitHub Actions.
            \"\"\"
            from __future__ import annotations

            import asyncio
            import logging
            import os
            import time

            logging.basicConfig(
                level=logging.INFO,
                format="%(asctime)s %(name)s %(levelname)s %(message)s",
            )
            logger = logging.getLogger("{spec.name}")

            ENVIRONMENT = os.environ.get("ENVIRONMENT", "development")
            # Schedule: {schedule}
            INTERVAL_SECONDS = int(os.environ.get("TASK_INTERVAL_SECONDS", 3600))


            async def run_task() -> None:
                \"\"\"Implement the scheduled task logic here.\"\"\"
                logger.info("{spec.name} task executing at %s", time.strftime("%Y-%m-%dT%H:%M:%SZ"))


            async def main() -> None:
                logger.info("{spec.name} scheduler starting (interval=%ds)", INTERVAL_SECONDS)
                while True:
                    try:
                        await run_task()
                    except Exception as exc:
                        logger.error("Task error: %s", exc)
                    await asyncio.sleep(INTERVAL_SECONDS)


            if __name__ == "__main__":
                asyncio.run(main())
            """)

    def _render_stream_processor(self, spec: BlueprintSpec) -> str:
        """Render a FastAPI SSE stream-processor worker with a /stream endpoint."""
        return textwrap.dedent(f"""\
            \"\"\"
            {spec.name} — SSE Stream Processor

            Generated by Tranc3 Master Worker Blueprint Engine.
            Real-time event streaming via Server-Sent Events.
            \"\"\"
            from __future__ import annotations

            import asyncio
            import json
            import logging
            import os
            import time

            import uvicorn
            from fastapi import FastAPI
            from fastapi.responses import StreamingResponse

            logging.basicConfig(level=logging.INFO)
            logger = logging.getLogger("{spec.name}")

            PORT = int(os.environ.get("PORT", {spec.port}))
            app = FastAPI(title="{spec.name}")


            @app.get("/health")
            async def health():
                return {{"status": "healthy", "service": "{spec.name}"}}


            @app.get("/stream")
            async def event_stream():
                async def generator():
                    while True:
                        event = json.dumps({{"ts": time.time(), "service": "{spec.name}"}})
                        yield f"data: {{event}}\\n\\n"
                        await asyncio.sleep(1.0)
                return StreamingResponse(generator(), media_type="text/event-stream")


            if __name__ == "__main__":
                uvicorn.run("worker:app", host="0.0.0.0", port=PORT, reload=False)
            """)

    # ------------------------------------------------------------------
    # Dockerfile
    # ------------------------------------------------------------------

    def _render_dockerfile(self, spec: BlueprintSpec) -> str:
        """Render a minimal python:3.12-slim Dockerfile for *spec*."""
        return textwrap.dedent(f"""\
            FROM python:3.12-slim

            WORKDIR /app

            COPY requirements.txt .
            RUN pip install --no-cache-dir -r requirements.txt

            COPY . .

            ENV PORT={spec.port}
            ENV PYTHONUNBUFFERED=1
            ENV PYTHONDONTWRITEBYTECODE=1

            EXPOSE {spec.port}

            CMD ["python", "worker.py"]
            """)

    # ------------------------------------------------------------------
    # docker-compose snippet
    # ------------------------------------------------------------------

    def _render_compose(self, spec: BlueprintSpec) -> str:
        """Render a docker-compose service snippet ready to paste into production.yml."""
        env_lines = "\n".join(f"      - {var}=${{{var}}}" for var in spec.env_vars)
        return textwrap.dedent(f"""\
            # Add to docker-compose.production.yml services section:
              {spec.name}:
                build:
                  context: ./workers/{spec.name}
                  dockerfile: Dockerfile
                ports:
                  - "{spec.port}:{spec.port}"
                environment:
                  - PORT={spec.port}
                  - ENVIRONMENT=${{ENVIRONMENT:-production}}
            {env_lines}
                restart: unless-stopped
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:{spec.port}/health"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
                networks:
                  - tranc3-network
            """)

    # ------------------------------------------------------------------
    # requirements.txt
    # ------------------------------------------------------------------

    def _render_requirements(self, spec: BlueprintSpec) -> str:
        """Render a requirements.txt combining BASE_REQUIREMENTS with spec.dependencies."""
        all_deps = list(self.BASE_REQUIREMENTS)
        for dep in spec.dependencies:
            if dep not in all_deps:
                all_deps.append(dep)
        return "\n".join(all_deps) + "\n"

    # ------------------------------------------------------------------
    # Forgejo CI workflow (replaces GitHub Actions)
    # ------------------------------------------------------------------

    def _render_forgejo_workflow(self, spec: BlueprintSpec) -> str:
        """Render a Forgejo CI workflow YAML — replaces any GitHub Actions equivalent."""
        return textwrap.dedent(f"""\
            # .forgejo/workflows/{spec.name}.yml
            # Generated by Tranc3 Master Worker Blueprint Engine
            # CI/CD via Forgejo (The Workshop) — NOT GitHub Actions

            name: Deploy {spec.name}

            on:
              push:
                branches: [main]
                paths:
                  - workers/{spec.name}/**
              workflow_dispatch:

            jobs:
              deploy:
                runs-on: ubuntu-latest
                steps:
                  - name: Checkout
                    uses: actions/checkout@v4

                  - name: Set up Python 3.12
                    uses: actions/setup-python@v5
                    with:
                      python-version: "3.12"

                  - name: Install dependencies
                    run: |
                      cd workers/{spec.name}
                      pip install -r requirements.txt

                  - name: Run tests
                    run: |
                      cd workers/{spec.name}
                      python -m pytest tests/ -v --tb=short || true

                  - name: Deploy to Fly.io
                    if: github.ref == 'refs/heads/main'
                    env:
                      FLY_API_TOKEN: ${{{{ secrets.FLY_API_TOKEN }}}}
                    run: |
                      cd workers/{spec.name}
                      flyctl deploy --remote-only --app {spec.name}
            """)
