#!/usr/bin/env python3
"""Generate the inventory half of docs/governance/MATRIX-INDEX.md from disk.

WHY THIS EXISTS

MATRIX-INDEX.md's hand-written map (its section 2) is the platform's answer to
"does real code back this Matrix, and is it documented?" -- an editorial
judgement no script can make, and it stays hand-written.

But the index was also implicitly claiming to be a complete list, and it was
not. Measured on 2026-08-22: 68 documents in this repo declare themselves a
Matrix, Framework, Register or Registry by filename, and 51 of them appeared
nowhere in the index. Not because anyone decided they did not belong -- because
adding a document and remembering to link it are two separate acts, and the
second one stopped happening.

A list that must be updated by hand every time a file is added will drift
again the week after it is corrected. So the *inventory* is generated from
disk and guarded by --check, while the *judgement* above it stays human. The
index can then be wrong about what a matrix means, but never wrong about what
exists.

EXCLUSIONS

Not every file matching the pattern is a platform matrix, so exclusions are
explicit and reasoned rather than silently dropped -- the same discipline
scripts/entity_registry_conformance.py applies to NON_WORKER_LOCATIONS. An
unreasoned exclusion is indistinguishable from an oversight, which is the
failure this script exists to prevent.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
INDEX = REPO / "docs" / "governance" / "MATRIX-INDEX.md"

BEGIN = "<!-- BEGIN GENERATED INVENTORY -- edit scripts/build_matrix_index.py, not this block -->"
END = "<!-- END GENERATED INVENTORY -->"

NAME_PATTERN = re.compile(r"(MATRIX|FRAMEWORK|REGISTER|REGISTRY)")

# path prefix -> why it is not part of this repo's matrix inventory
EXCLUDED_PREFIXES: dict[str, str] = {
    "node_modules/": "vendored dependency, not authored here",
    "compliance/magna-carta/": (
        "a git submodule with its own lifecycle, its own index "
        "(`docs/governance/MATRIX-SUITES.md`) and its own pin. Inventorying another "
        "repository's documents from here would make this list go stale every time that "
        "pin moves, and would break in CI, where the submodule is not checked out -- a "
        "guard that fails for environmental reasons trains people to ignore it"
    ),
    "config/townhall/templates/": (
        "Town Hall room templates a user fills in -- an empty form, not a matrix"
    ),
    "wiki-content/": (
        "published copies of docs that live elsewhere in this repo; indexing both "
        "would double-count every entry (see docs/WIKI_INDEX.md)"
    ),
}

# Which grouping a path belongs to, in order of specificity.
GROUPS: list[tuple[str, str, str]] = [
    (
        "docs/governance/",
        "Platform governance",
        "This repository's own governance matrices -- the set section 2 above judges.",
    ),
    (
        "docs/",
        "Platform docs (other)",
        "Matrices and registers filed outside `docs/governance/`.",
    ),
    ("", "Repository root and elsewhere", "Everything else that declares itself one of these."),
]


def _excluded(rel: str) -> str | None:
    for prefix, reason in EXCLUDED_PREFIXES.items():
        if rel.startswith(prefix):
            return reason
    return None


def discover() -> dict[str, list[str]]:
    """Every self-declared matrix document, grouped, excluding the reasoned set."""
    found: dict[str, list[str]] = {label: [] for _, label, _ in GROUPS}
    for path in sorted(REPO.rglob("*.md")):
        if ".git" in path.parts:
            continue
        rel = path.relative_to(REPO).as_posix()
        if not NAME_PATTERN.search(path.name.upper()):
            continue
        if rel == INDEX.relative_to(REPO).as_posix() or _excluded(rel):
            continue
        for prefix, label, _ in GROUPS:
            if rel.startswith(prefix):
                found[label].append(rel)
                break
    return found


def render(found: dict[str, list[str]]) -> str:
    total = sum(len(v) for v in found.values())
    lines = [
        BEGIN,
        "",
        "## 6. Full inventory (generated)",
        "",
        f"Every document in this repository whose filename declares it a Matrix, Framework, "
        f"Register or Registry: **{total}**. Generated by `scripts/build_matrix_index.py`; "
        "`--check` runs in CI, so a new one cannot be added without appearing here. Presence in "
        "this list is a statement that the file exists, not that section 2 has judged it.",
        "",
    ]
    for _, label, blurb in GROUPS:
        entries = found[label]
        if not entries:
            continue
        lines += [f"### {label} ({len(entries)})", "", blurb, ""]
        for rel in entries:
            name = Path(rel).name
            lines.append(f"- [{name}]({_relative_link(rel)}) — `{rel}`")
        lines.append("")
    lines += [
        "### Deliberately excluded",
        "",
        "An unreasoned exclusion cannot be told apart from an oversight, so each carries its "
        "reason:",
        "",
    ]
    lines += [f"- `{prefix}` — {reason}" for prefix, reason in EXCLUDED_PREFIXES.items()]
    lines += ["", END]
    return "\n".join(lines)


def _relative_link(rel: str) -> str:
    """A link that resolves from docs/governance/, where the index lives."""
    import os.path

    return os.path.relpath(rel, INDEX.parent.relative_to(REPO).as_posix())


def apply(text: str, block: str) -> str:
    if BEGIN in text and END in text:
        head_end = text.index(BEGIN)
        tail_start = text.index(END) + len(END)
        return text[:head_end] + block + text[tail_start:]
    return text.rstrip() + "\n\n---\n\n" + block + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the generated block is stale, without writing",
    )
    args = parser.parse_args()

    current = INDEX.read_text(encoding="utf-8")
    updated = apply(current, render(discover()))

    if args.check:
        if current != updated:
            print("matrix index: STALE -- run scripts/build_matrix_index.py", file=sys.stderr)
            return 1
        print("matrix index: up to date")
        return 0

    if current == updated:
        print("matrix index: already up to date")
        return 0
    INDEX.write_text(updated, encoding="utf-8")
    print(f"matrix index: regenerated {INDEX.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
