#!/usr/bin/env python3
"""
Citadel — one script for pre-deploy gate + optional local Docker deploy.

Default (PLATFORM_INFRA_MODE=CLOUD_ONLY): quality gate only — no Docker.
Use --local or set PLATFORM_INFRA_MODE=LOCAL_ONLY when your Citadel server is ready.

Usage:
  python scripts/citadel_deploy_all.py              # gate; skip Docker if CLOUD_ONLY
  python scripts/citadel_deploy_all.py --gate-only  # quality gate only
  python scripts/citadel_deploy_all.py --local      # force Citadel Docker deploy
  python scripts/citadel_deploy_all.py --install-deps
  python scripts/citadel_deploy_all.py --full --force-env --local

Windows CMD (from repo root):
  py -3.11 scripts\\citadel_deploy_all.py
  scripts\\citadel_deploy_all.bat
"""

from __future__ import annotations

import argparse
import os
import secrets
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMPOSE_FILE = ROOT / "docker-compose.production.yml"

CORE_SERVICES = [
    "traefik",
    "valkey",
    "vault",
    "ollama",
    "tranc3-backend",
    "tranc3-ai",
    "infinity-void",
    "infinity-ws",
    "infinity-auth",
    "users-service",
    "products-service",
    "orders-service",
    "payments-service",
    "api-gateway",
    "monitoring",
    "notifications",
    "infinity-ai",
    "infinity-admin",
    "swarm-coordinator",
    "prometheus",
    "grafana",
]

FULL_EXTRA = [
    "the-grid",
    "files-service",
    "identity-service",
    "health-aggregator",
    "vault-service",
    "gbrain-bridge",
]

PIP_TOOLS = ["ruff", "bandit", "pip-audit", "pytest"]


def _log(msg: str) -> None:
    print(msg, flush=True)


def _section(title: str) -> None:
    _log("")
    _log(f"{'=' * 60}")
    _log(f"  {title}")
    _log(f"{'=' * 60}")


def _run(
    cmd: list[str],
    *,
    check: bool = True,
    env: dict[str, str] | None = None,
) -> int:
    _log(f"  $ {' '.join(cmd)}")
    merged = {**os.environ, **(env or {})}
    result = subprocess.run(cmd, cwd=ROOT, env=merged)
    if check and result.returncode != 0:
        raise SystemExit(result.returncode)
    return result.returncode


def _python() -> str:
    return sys.executable


def _ensure_repo() -> None:
    if not (ROOT / "api.py").is_file() or not COMPOSE_FILE.is_file():
        _log(f"ERROR: Run this from the Tranc3 repo root (expected {ROOT})")
        raise SystemExit(1)


def _install_deps() -> None:
    _section("Install Python tools")
    _run([_python(), "-m", "pip", "install", "-q", "-r", "requirements.txt"], check=False)
    _run([_python(), "-m", "pip", "install", "-q", *PIP_TOOLS], check=False)


def _infra_mode() -> str:
    sys.path.insert(0, str(ROOT))
    try:
        from src.platform.infrastructure_mode import get_infrastructure_mode

        return get_infrastructure_mode().value
    except Exception:
        raw = os.environ.get("PLATFORM_INFRA_MODE") or os.environ.get(
            "SYSTEM_MODE", "CLOUD_ONLY"
        )
        return str(raw).strip().upper() or "CLOUD_ONLY"


def _generate_env(force: bool, *, local_stack: bool) -> None:
    out = ROOT / ".env.production"
    if out.exists() and not force:
        _log(f"  Using existing {out.name}")
        return

    mode = _infra_mode()
    use_local_db = local_stack or mode == "LOCAL_ONLY"
    _section(f"Generate .env.production (mode={mode}, local_db={use_local_db})")

    def gen_hex() -> str:
        return secrets.token_hex(32)

    def gen_url() -> str:
        return secrets.token_urlsafe(32)

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    if use_local_db:
        database_url = "sqlite:////app/data/tranc3_platform.db"
        redis_url = "redis://valkey:6379/0"
        rotation_chain = "zero_cost_full"
        mode_line = f"PLATFORM_INFRA_MODE={mode}\n"
    else:
        database_url = (
            "postgresql://postgres:[password]@db.[project-ref].supabase.co:5432/postgres"
        )
        redis_url = "rediss://:[password]@[endpoint].upstash.io:6379"
        rotation_chain = "zero_cost_cloud"
        mode_line = "PLATFORM_INFRA_MODE=CLOUD_ONLY\n"

    content = f"""# AUTO-GENERATED by scripts/citadel_deploy_all.py — {ts}
# DO NOT COMMIT. Fill Supabase/Upstash URLs when CLOUD_ONLY.

{mode_line}ENVIRONMENT=production
DEBUG=false
PORT=8000
LOG_LEVEL=INFO

SECRET_KEY={gen_hex()}
JWT_SECRET={gen_hex()}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

DATABASE_URL={database_url}
REDIS_URL={redis_url}

CORS_ORIGINS=http://localhost,http://127.0.0.1,https://trancendos.com,https://api.trancendos.com
FRONTEND_URL=https://trancendos.com
VITE_API_URL=https://api.trancendos.com
ALLOWED_ORIGINS=https://trancendos.com,https://api.trancendos.com

OLLAMA_URL=http://ollama:11434
OLLAMA_MODEL=llama3.2:1b
EMBED_MODEL=all-MiniLM-L6-v2

INTERNAL_SECRET={gen_hex()}
MASTER_KEY_SEED={gen_hex()}
VAULT_MASTER_KEY={gen_hex()}
AUDIT_SIGNING_KEY={gen_hex()}

ENTITY_OVERRIDES_DB=/app/data/infinity_admin.db
INFINITY_ADMIN_DB_PATH=/app/data/infinity_admin.db
ENTITY_OVERRIDES_CACHE_TTL=60

ADAPTIVE_ROTATION_ENABLED=true
ADAPTIVE_ROTATION_CHAIN={rotation_chain}
ADAPTIVE_CLOUD_AUTO_ROTATE=true
ADAPTIVE_CLOUD_AUTO_ROTATE_SECONDS=180
ADAPTIVE_COOLDOWN_SECONDS=300
PROACTIVE_ORCHESTRATOR_ENABLED=true
PROACTIVE_INTERVAL_SECONDS=600
ENABLE_SWARM=true

TRANC3_BACKEND_URL=http://tranc3-backend:8000
TRANC3_NANO_URL=http://tranc3-backend:8001
AUTH_SERVICE_URL=http://infinity-auth:8005
USERS_SERVICE_URL=http://users-service:8006
PRODUCTS_SERVICE_URL=http://products-service:8011
ORDERS_SERVICE_URL=http://orders-service:8012
PAYMENTS_SERVICE_URL=http://payments-service:8013
INFINITY_WS_URL=http://infinity-ws:8004
INFINITY_AUTH_URL=http://infinity-auth:8005
INFINITY_AI_URL=http://infinity-ai:8009
TRANC3_AI_SERVICE_URL=http://tranc3-ai:8001

VAULT_ADDR=http://tranc3-vault:8200
VAULT_TOKEN=
PROMETHEUS_ENABLED=true
OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317

OUTLINE_DB_PASSWORD={gen_url()}
REDIS_PASSWORD={gen_url()}

OPENROUTER_API_KEY=
HF_API_KEY=
GROQ_API_KEY=
GEMINI_API_KEY=
CEREBRAS_API_KEY=
SAMBANOVA_API_KEY=

STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
"""
    out.write_text(content, encoding="utf-8")
    try:
        os.chmod(out, 0o600)
    except OSError:
        pass  # Windows may not support unix mode
    _log(f"  Wrote {out}")


def _pre_deploy_gate() -> None:
    _section("Pre-deploy quality gate")
    _run([_python(), "scripts/pre_deploy_quality_gate.py"])


def _preflight() -> None:
    _section("Citadel preflight")
    _run([_python(), "scripts/citadel_compose_validate.py"])
    code = _run([_python(), "scripts/citadel_preflight.py"], check=False)
    if code != 0:
        _log("  WARN: preflight reported issues — continuing for bootstrap")


def _docker_cmd() -> list[str]:
    if shutil.which("docker"):
        return ["docker", "compose"]
    raise SystemExit(
        "ERROR: Docker not found. Install Docker Desktop (Windows/Mac) or Docker Engine (Linux)."
    )


def _compose(args: list[str], *, check: bool = True) -> int:
    return _run([*_docker_cmd(), "-f", str(COMPOSE_FILE), *args], check=check)


def _deploy_docker(*, profile: str, skip_build: bool) -> None:
    _section("Docker deploy (Citadel stack)")
    services = list(CORE_SERVICES)
    if profile == "full":
        services.extend(FULL_EXTRA)

    if not skip_build:
        _compose(["build", *services])

    _compose(["up", "-d", "valkey", "vault", "traefik", "ollama"])
    time.sleep(5)
    _log("  If Vault is new, run: deploy\\vault\\init-citadel.sh (Git Bash) or WSL")

    _compose(["up", "-d", *services])

    _section("Wait for health")
    code = _run(
        [_python(), "scripts/wait_for_healthy.py", "--timeout", "600"],
        check=False,
    )
    if code != 0:
        _log("  WARN: some services still starting — run monitor step below")


def _post_deploy() -> None:
    _section("Post-deploy checks")
    _run([_python(), "scripts/health_check.py", "--json"], check=False)
    _run([_python(), "scripts/zero_cost_audit.py"], check=False)
    _run([_python(), "scripts/production_readiness_score.py"], check=False)
    if (ROOT / "scripts/seed_uat_data.py").is_file():
        _run([_python(), "scripts/seed_uat_data.py"], check=False)


def _monitor() -> None:
    _section("P0/P1 health monitor")
    _run([_python(), "scripts/monitor_p0_workers.py"], check=False)


def _print_urls() -> None:
    _log("")
    _log("Done.")
    _log("  API:       http://localhost:8000/health")
    _log("  Ready:     http://localhost:8000/ready")
    _log("  Gateway:   http://localhost:8003/")
    _log("  Admin OS:  http://localhost:8000/dashboard/infinity-admin-os.html")
    _log("  Grafana:   http://localhost:3000")
    _log("  Traefik:   http://localhost:8888")


def main() -> int:
    parser = argparse.ArgumentParser(description="Tranc3 Citadel — gate + deploy in one script")
    parser.add_argument(
        "--gate-only",
        action="store_true",
        help="Run pre-deploy gate only (no Docker)",
    )
    parser.add_argument(
        "--skip-docker",
        action="store_true",
        help="Gate + env + preflight, but do not start Docker",
    )
    parser.add_argument(
        "--local",
        action="store_true",
        help="Force Citadel Docker deploy (LOCAL_ONLY / migration)",
    )
    parser.add_argument(
        "--cloud-only",
        action="store_true",
        help="Explicit CLOUD_ONLY: gate only, no Docker (default when mode is CLOUD_ONLY)",
    )
    parser.add_argument(
        "--full",
        action="store_true",
        help="Deploy full profile (extra P2 workers)",
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Skip docker compose build",
    )
    parser.add_argument(
        "--force-env",
        action="store_true",
        help="Regenerate .env.production",
    )
    parser.add_argument(
        "--install-deps",
        action="store_true",
        help="pip install requirements + ruff/bandit/pytest/pip-audit",
    )
    parser.add_argument(
        "--no-monitor",
        action="store_true",
        help="Skip final make monitor step",
    )
    args = parser.parse_args()

    _ensure_repo()
    mode = _infra_mode()
    _log(f"Tranc3 Citadel deploy — root: {ROOT} — PLATFORM_INFRA_MODE={mode}")

    if args.install_deps:
        _install_deps()

    _pre_deploy_gate()

    if args.gate_only or args.cloud_only:
        _log("")
        _log("Gate-only mode complete (PASS).")
        if mode == "CLOUD_ONLY" or args.cloud_only:
            _log("  CLOUD_ONLY: cloud auto-rotation runs via API/Fly/CF — no Citadel Docker required.")
            _log("  When ready for local: PLATFORM_INFRA_MODE=LOCAL_ONLY scripts/citadel_deploy_all.py --local")
        return 0

    local_deploy = args.local or args.skip_docker is False and mode in (
        "LOCAL_ONLY",
        "HYBRID",
    ) and (
        mode == "LOCAL_ONLY"
        or os.environ.get("CITADEL_LOCAL_STACK", "").lower() in ("1", "true", "yes")
    )
    if mode == "CLOUD_ONLY" and not args.local:
        local_deploy = False

    _generate_env(force=args.force_env, local_stack=local_deploy)
    if not local_deploy:
        _log("")
        _log(f"CLOUD_ONLY ({mode}): skipping Citadel Docker — use --local when your server is ready.")
        _log("  Adaptive: GET /adaptive/mode and GET /adaptive/status on your running API.")
        return 0

    _preflight()

    if args.skip_docker:
        _log("")
        _log("Skip-docker mode complete. Start stack manually when ready:")
        _log("  docker compose -f docker-compose.production.yml up -d")
        return 0

    profile = "full" if args.full else "core"
    _deploy_docker(profile=profile, skip_build=args.skip_build)
    _post_deploy()

    if not args.no_monitor:
        _monitor()

    _print_urls()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
