#!/usr/bin/env bash
# Generate .env.production for Citadel live deploy (self-hosted secrets, zero cloud required).
# Usage: ./scripts/generate_production_env.sh [--force] [--push-to-vault]
#
# --force         Overwrite an existing .env.production
# --push-to-vault After writing .env.production, push all secrets into Vault KV.
#                 Requires VAULT_TOKEN (tranc3-admin policy) and Vault to be unsealed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT="${ENV_OUT:-.env.production}"
FORCE=false
PUSH_TO_VAULT=false
for arg in "$@"; do
  case "$arg" in
    --force)         FORCE=true ;;
    --push-to-vault) PUSH_TO_VAULT=true ;;
  esac
done

if [[ -f "$OUT" && "$FORCE" != true ]]; then
  echo "ERROR: $OUT exists. Use --force to overwrite." >&2
  exit 1
fi

gen_hex() { python3 -c "import secrets; print(secrets.token_hex(32))"; }
gen_url() { python3 -c "import secrets; print(secrets.token_urlsafe(32))"; }

SECRET_KEY="$(gen_hex)"
JWT_SECRET="$(gen_hex)"
INTERNAL_SECRET="$(gen_hex)"
MASTER_KEY_SEED="$(gen_hex)"
VAULT_MASTER_KEY="$(gen_hex)"
AUDIT_SIGNING_KEY="$(gen_hex)"
REDIS_PASSWORD="$(gen_url)"
OUTLINE_DB_PASSWORD="$(gen_url)"

# ── Every `${VAR:?required}` in docker-compose.production.yml ───────────────────
# Compose refuses to interpolate the file at all if any of these is unset, so a
# generated env that omits one makes `docker compose up` fail before a single
# container starts. 47 were missing; scripts/check_env_covers_compose.py now fails
# CI if compose grows a required variable this script does not produce.
#
# The Town Hall (CranBania)
CRANBANIA_API_KEY="$(gen_hex)"
CRANBANIA_CRON_SECRET="$(gen_hex)"
CRANBANIA_WEBHOOK_SECRET="$(gen_hex)"

# Operator identity — override before running to use a real mailbox.
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@trancendos.com}"

# The Workshop (Forgejo) + Woodpecker CI
FORGEJO_SECRET_KEY="$(gen_hex)"
FORGEJO_INTERNAL_TOKEN="$(gen_hex)"
WOODPECKER_SECRET="$(gen_hex)"
WOODPECKER_AGENT_TOKEN="$(gen_hex)"
# Renovate needs a real Forgejo PAT, which cannot exist before Forgejo is up. A
# generated placeholder keeps compose renderable; replace it post-deploy.
RENOVATE_FORGEJO_TOKEN="${RENOVATE_FORGEJO_TOKEN:-$(gen_hex)}"

# Observability + dashboards
GRAFANA_ADMIN_PASSWORD="$(gen_url)"
SIGNOZ_CLICKHOUSE_PASSWORD="$(gen_url)"
LANGFUSE_SECRET="$(gen_hex)"
LANGFUSE_SALT="$(gen_hex)"

# Identity (Authentik)
AUTHENTIK_SECRET_KEY="$(gen_hex)"
AUTHENTIK_DB_PASSWORD="$(gen_url)"
AUTHENTIK_ADMIN_PASSWORD="$(gen_url)"

# The Void / secrets
OPENBAO_ROOT_TOKEN="$(gen_hex)"

# AI gateway (LiteLLM)
LITELLM_MASTER_KEY="sk-$(gen_hex)"
LITELLM_SALT_KEY="$(gen_hex)"

# The Digital Grid (n8n) + Airflow
N8N_USER="${N8N_USER:-admin}"
N8N_PASSWORD="$(gen_url)"
N8N_ENCRYPTION_KEY="$(gen_hex)"
AIRFLOW_USER="${AIRFLOW_USER:-admin}"
AIRFLOW_PASS="$(gen_url)"

# The Library (BookStack) + Outline
BOOKSTACK_DB_PASSWORD="$(gen_url)"
BOOKSTACK_DB_ROOT_PASSWORD="$(gen_url)"
OUTLINE_SECRET_KEY="$(gen_hex)"
OUTLINE_UTILS_SECRET="$(gen_hex)"

# DocUtari (Paperless) + storage/search
PAPERLESS_ADMIN_USER="${PAPERLESS_ADMIN_USER:-admin}"
PAPERLESS_ADMIN_PASSWORD="$(gen_url)"
PAPERLESS_DB_PASSWORD="$(gen_url)"
PAPERLESS_SECRET_KEY="$(gen_hex)"
MINIO_ROOT_PASSWORD="$(gen_url)"
MEILI_MASTER_KEY="$(gen_hex)"

# Cryptex (MISP/Wazuh/OpenVAS) + OpenBAS
MISP_ADMIN_EMAIL="${MISP_ADMIN_EMAIL:-$ADMIN_EMAIL}"
MISP_ADMIN_PASSWORD="$(gen_url)"
MISP_DB_PASSWORD="$(gen_url)"
MISP_DB_ROOT_PASSWORD="$(gen_url)"
WAZUH_API_PASSWORD="$(gen_url)"
WAZUH_INDEXER_PASSWORD="$(gen_url)"
WAZUH_KIBANA_PASSWORD="$(gen_url)"
OPENVAS_PASS="$(gen_url)"
OPENBAS_ADMIN_EMAIL="${OPENBAS_ADMIN_EMAIL:-$ADMIN_EMAIL}"
OPENBAS_ADMIN_PASSWORD="$(gen_url)"
OPENBAS_ADMIN_TOKEN="$(gen_hex)"
OPENBAS_DB_PASSWORD="$(gen_url)"

# ChronosSphere (Cal.com) + Fabulousa (Penpot)
CALCOM_DB_PASSWORD="$(gen_url)"
CALCOM_NEXTAUTH_SECRET="$(gen_hex)"
CALCOM_ENCRYPTION_KEY="$(gen_hex)"
PENPOT_SECRET_KEY="$(gen_hex)"

cat > "$OUT" <<EOF
# AUTO-GENERATED by scripts/generate_production_env.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Self-hosted Citadel stack. DO NOT COMMIT. Store backup in The Void (Vault).

ENVIRONMENT=production
DEBUG=false
PORT=8000
LOG_LEVEL=INFO

SECRET_KEY=${SECRET_KEY}
JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

# Self-hosted SQLite on shared admin-data volume (no Supabase required for Citadel)
DATABASE_URL=sqlite:////app/data/tranc3_platform.db

# Valkey (Redis-compatible) in docker-compose.production.yml
REDIS_URL=redis://valkey:6379/0

CORS_ORIGINS=http://localhost,http://127.0.0.1,https://trancendos.com,https://api.trancendos.com
FRONTEND_URL=https://trancendos.com
VITE_API_URL=https://api.trancendos.com
ALLOWED_ORIGINS=https://trancendos.com,https://api.trancendos.com

OLLAMA_URL=http://ollama:11434
OLLAMA_MODEL=llama3.2:1b
EMBED_MODEL=all-MiniLM-L6-v2

INTERNAL_SECRET=${INTERNAL_SECRET}
MASTER_KEY_SEED=${MASTER_KEY_SEED}
VAULT_MASTER_KEY=${VAULT_MASTER_KEY}
AUDIT_SIGNING_KEY=${AUDIT_SIGNING_KEY}

ENTITY_OVERRIDES_DB=/app/data/infinity_admin.db
INFINITY_ADMIN_DB_PATH=/app/data/infinity_admin.db
ENTITY_OVERRIDES_CACHE_TTL=60

# ── Compose-required variables ────────────────────────────────────────────────
# Every one of these is marked \`:?required\` in docker-compose.production.yml.
# Compose will not render the file with any of them unset.

# The Town Hall (CranBania)
CRANBANIA_API_KEY=${CRANBANIA_API_KEY}
CRANBANIA_CRON_SECRET=${CRANBANIA_CRON_SECRET}
CRANBANIA_WEBHOOK_SECRET=${CRANBANIA_WEBHOOK_SECRET}

ADMIN_EMAIL=${ADMIN_EMAIL}

# The Workshop (Forgejo) + Woodpecker CI
FORGEJO_SECRET_KEY=${FORGEJO_SECRET_KEY}
FORGEJO_INTERNAL_TOKEN=${FORGEJO_INTERNAL_TOKEN}
WOODPECKER_SECRET=${WOODPECKER_SECRET}
WOODPECKER_AGENT_TOKEN=${WOODPECKER_AGENT_TOKEN}
# Placeholder — replace with a real Forgejo PAT once The Workshop is running.
RENOVATE_FORGEJO_TOKEN=${RENOVATE_FORGEJO_TOKEN}

# Observability
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
SIGNOZ_CLICKHOUSE_PASSWORD=${SIGNOZ_CLICKHOUSE_PASSWORD}
LANGFUSE_SECRET=${LANGFUSE_SECRET}
LANGFUSE_SALT=${LANGFUSE_SALT}

# Identity (Authentik)
AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
AUTHENTIK_DB_PASSWORD=${AUTHENTIK_DB_PASSWORD}
AUTHENTIK_ADMIN_PASSWORD=${AUTHENTIK_ADMIN_PASSWORD}

# The Void
OPENBAO_ROOT_TOKEN=${OPENBAO_ROOT_TOKEN}

# AI gateway (LiteLLM)
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
LITELLM_SALT_KEY=${LITELLM_SALT_KEY}

# The Digital Grid (n8n) + Airflow
N8N_USER=${N8N_USER}
N8N_PASSWORD=${N8N_PASSWORD}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
AIRFLOW_USER=${AIRFLOW_USER}
AIRFLOW_PASS=${AIRFLOW_PASS}

# The Library (BookStack) + Outline
BOOKSTACK_DB_PASSWORD=${BOOKSTACK_DB_PASSWORD}
BOOKSTACK_DB_ROOT_PASSWORD=${BOOKSTACK_DB_ROOT_PASSWORD}
OUTLINE_SECRET_KEY=${OUTLINE_SECRET_KEY}
OUTLINE_UTILS_SECRET=${OUTLINE_UTILS_SECRET}

# DocUtari (Paperless) + storage/search
PAPERLESS_ADMIN_USER=${PAPERLESS_ADMIN_USER}
PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
PAPERLESS_DB_PASSWORD=${PAPERLESS_DB_PASSWORD}
PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MEILI_MASTER_KEY=${MEILI_MASTER_KEY}

# Cryptex (MISP/Wazuh/OpenVAS) + OpenBAS
MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
MISP_ADMIN_PASSWORD=${MISP_ADMIN_PASSWORD}
MISP_DB_PASSWORD=${MISP_DB_PASSWORD}
MISP_DB_ROOT_PASSWORD=${MISP_DB_ROOT_PASSWORD}
WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}
WAZUH_INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD}
WAZUH_KIBANA_PASSWORD=${WAZUH_KIBANA_PASSWORD}
OPENVAS_PASS=${OPENVAS_PASS}
OPENBAS_ADMIN_EMAIL=${OPENBAS_ADMIN_EMAIL}
OPENBAS_ADMIN_PASSWORD=${OPENBAS_ADMIN_PASSWORD}
OPENBAS_ADMIN_TOKEN=${OPENBAS_ADMIN_TOKEN}
OPENBAS_DB_PASSWORD=${OPENBAS_DB_PASSWORD}

# ChronosSphere (Cal.com) + Fabulousa (Penpot)
CALCOM_DB_PASSWORD=${CALCOM_DB_PASSWORD}
CALCOM_NEXTAUTH_SECRET=${CALCOM_NEXTAUTH_SECRET}
CALCOM_ENCRYPTION_KEY=${CALCOM_ENCRYPTION_KEY}
PENPOT_SECRET_KEY=${PENPOT_SECRET_KEY}

ADAPTIVE_ROTATION_ENABLED=true
ADAPTIVE_ROTATION_CHAIN=zero_cost_full
ADAPTIVE_COOLDOWN_SECONDS=300
PROACTIVE_ORCHESTRATOR_ENABLED=true
PROACTIVE_INTERVAL_SECONDS=600
ENABLE_SWARM=true

TRANC3_BACKEND_URL=http://tranc3-backend:8000
TRANC3_NANO_URL=http://tranc3-backend:8001
AUTH_SERVICE_URL=http://infinity-auth:8005
USERS_SERVICE_URL=http://users-service:8006
PRODUCTS_SERVICE_URL=http://products-service:8011
ORDERS_SERVICE_URL=http://orders-service:8012
PAYMENTS_SERVICE_URL=http://payments-service:8013
INFINITY_WS_URL=http://infinity-ws:8004
INFINITY_AUTH_URL=http://infinity-auth:8005
INFINITY_AI_URL=http://infinity-ai:8009
TRANC3_AI_SERVICE_URL=http://tranc3-ai:8001

VAULT_ADDR=http://tranc3-vault:8200
VAULT_TOKEN=
PROMETHEUS_ENABLED=true
OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317

OUTLINE_DB_PASSWORD=${OUTLINE_DB_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}

# Optional cloud AI (leave empty for strict zero-cost)
OPENROUTER_API_KEY=
HF_API_KEY=
GROQ_API_KEY=
GEMINI_API_KEY=
CEREBRAS_API_KEY=
SAMBANOVA_API_KEY=

STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
EOF

chmod 600 "$OUT"
echo "Wrote $OUT (mode 600)."

if [[ "$PUSH_TO_VAULT" == true ]]; then
  echo "Pushing secrets into Vault KV..."
  VAULT_TOKEN="${VAULT_TOKEN:-}" \
    ENV_OUT="$OUT" \
    "$ROOT/scripts/vault-sync-secrets.sh" --push --env-file "$OUT"
  echo "Vault push complete."
fi

echo "Next: make deploy-live"
