#!/usr/bin/env bash
# Generate .env.production for Citadel live deploy (self-hosted secrets, zero cloud required).
# Usage: ./scripts/generate_production_env.sh [--force]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT="${ENV_OUT:-.env.production}"
FORCE=false
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=true ;;
  esac
done

if [[ -f "$OUT" && "$FORCE" != true ]]; then
  echo "ERROR: $OUT exists. Use --force to overwrite." >&2
  exit 1
fi

gen_hex() { python3 -c "import secrets; print(secrets.token_hex(32))"; }
gen_url() { python3 -c "import secrets; print(secrets.token_urlsafe(32))"; }

SECRET_KEY="$(gen_hex)"
JWT_SECRET="$(gen_hex)"
INTERNAL_SECRET="$(gen_hex)"
MASTER_KEY_SEED="$(gen_hex)"
VAULT_MASTER_KEY="$(gen_hex)"
AUDIT_SIGNING_KEY="$(gen_hex)"
REDIS_PASSWORD="$(gen_url)"
OUTLINE_DB_PASSWORD="$(gen_url)"

cat > "$OUT" <<EOF
# AUTO-GENERATED by scripts/generate_production_env.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Self-hosted Citadel stack. DO NOT COMMIT. Store backup in The Void (Vault).

ENVIRONMENT=production
DEBUG=false
PORT=8000
LOG_LEVEL=INFO

SECRET_KEY=${SECRET_KEY}
JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

# Self-hosted SQLite on shared admin-data volume (no Supabase required for Citadel)
DATABASE_URL=sqlite:////app/data/tranc3_platform.db

# Valkey (Redis-compatible) in docker-compose.production.yml
REDIS_URL=redis://valkey:6379/0

CORS_ORIGINS=http://localhost,http://127.0.0.1,https://trancendos.com,https://api.trancendos.com
FRONTEND_URL=https://trancendos.com
VITE_API_URL=https://api.trancendos.com
ALLOWED_ORIGINS=https://trancendos.com,https://api.trancendos.com

OLLAMA_URL=http://ollama:11434
OLLAMA_MODEL=llama3.2:1b
EMBED_MODEL=all-MiniLM-L6-v2

INTERNAL_SECRET=${INTERNAL_SECRET}
MASTER_KEY_SEED=${MASTER_KEY_SEED}
VAULT_MASTER_KEY=${VAULT_MASTER_KEY}
AUDIT_SIGNING_KEY=${AUDIT_SIGNING_KEY}

ENTITY_OVERRIDES_DB=/app/data/infinity_admin.db
INFINITY_ADMIN_DB_PATH=/app/data/infinity_admin.db
ENTITY_OVERRIDES_CACHE_TTL=60

ADAPTIVE_ROTATION_ENABLED=true
ADAPTIVE_ROTATION_CHAIN=zero_cost_full
ADAPTIVE_COOLDOWN_SECONDS=300
PROACTIVE_ORCHESTRATOR_ENABLED=true
PROACTIVE_INTERVAL_SECONDS=600
ENABLE_SWARM=true

TRANC3_BACKEND_URL=http://tranc3-backend:8000
TRANC3_NANO_URL=http://tranc3-backend:8001
AUTH_SERVICE_URL=http://infinity-auth:8005
USERS_SERVICE_URL=http://users-service:8006
PRODUCTS_SERVICE_URL=http://products-service:8011
ORDERS_SERVICE_URL=http://orders-service:8012
PAYMENTS_SERVICE_URL=http://payments-service:8013
INFINITY_WS_URL=http://infinity-ws:8004
INFINITY_AUTH_URL=http://infinity-auth:8005
INFINITY_AI_URL=http://infinity-ai:8009
TRANC3_AI_SERVICE_URL=http://tranc3-ai:8001

VAULT_ADDR=http://tranc3-vault:8200
VAULT_TOKEN=
PROMETHEUS_ENABLED=true
OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317

OUTLINE_DB_PASSWORD=${OUTLINE_DB_PASSWORD}
REDIS_PASSWORD=${REDIS_PASSWORD}

# Optional cloud AI (leave empty for strict zero-cost)
OPENROUTER_API_KEY=
HF_API_KEY=
GROQ_API_KEY=
GEMINI_API_KEY=
CEREBRAS_API_KEY=
SAMBANOVA_API_KEY=

STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
EOF

chmod 600 "$OUT"
echo "Wrote $OUT (mode 600). Run: make deploy-live"
