#!/usr/bin/env python3
"""Render Trancendos_Master_Service_Matrix.xlsx as a static HTML site.

Reads every sheet's cell values (data_only=False, so formula text is shown
verbatim — a static page can't recalculate them) and writes one self-contained
index.html with a tab per sheet. Used by .github/workflows/publish-matrix-site.yml
to publish a browsable copy of the workbook to GitHub Pages; this script has no
GitHub-specific logic itself, it just produces plain HTML in an output directory.

Usage:
    python scripts/render_matrix_html.py [--out site]
"""

from __future__ import annotations

import argparse
import html
import re
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = ROOT / "docs" / "architecture" / "ea-workbook" / "Trancendos_Master_Service_Matrix.xlsx"

PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Trancendos Master Service Matrix</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          margin: 0; padding: 0; background: canvas; color: canvastext; }}
  header {{ padding: 1rem 1.5rem; border-bottom: 1px solid color-mix(in srgb, canvastext 15%, transparent); }}
  header h1 {{ margin: 0 0 0.25rem; font-size: 1.25rem; }}
  header p {{ margin: 0; opacity: 0.7; font-size: 0.85rem; }}
  nav {{ display: flex; flex-wrap: wrap; gap: 0.25rem; padding: 0.75rem 1.5rem;
         border-bottom: 1px solid color-mix(in srgb, canvastext 15%, transparent);
         position: sticky; top: 0; background: canvas; z-index: 1; }}
  nav button {{ font: inherit; font-size: 0.8rem; padding: 0.35rem 0.7rem; border-radius: 6px;
                border: 1px solid color-mix(in srgb, canvastext 20%, transparent);
                background: transparent; color: inherit; cursor: pointer; }}
  nav button.active {{ background: color-mix(in srgb, canvastext 12%, transparent); font-weight: 600; }}
  main {{ padding: 1rem 1.5rem 3rem; overflow-x: auto; }}
  .sheet {{ display: none; }}
  .sheet.active {{ display: block; }}
  table {{ border-collapse: collapse; width: max-content; min-width: 100%; font-size: 0.8rem; }}
  th, td {{ border: 1px solid color-mix(in srgb, canvastext 15%, transparent);
            padding: 0.35rem 0.55rem; text-align: left; vertical-align: top; white-space: pre-wrap; }}
  th {{ background: color-mix(in srgb, canvastext 8%, transparent); position: sticky; top: 0; }}
  tr:nth-child(even) td {{ background: color-mix(in srgb, canvastext 4%, transparent); }}
  footer {{ padding: 1rem 1.5rem; opacity: 0.6; font-size: 0.75rem; }}
</style>
</head>
<body>
<header>
  <h1>Trancendos Master Service Matrix</h1>
  <p>Auto-published from docs/architecture/ea-workbook/Trancendos_Master_Service_Matrix.xlsx on every push to main. Formula cells show their formula text, not a computed value — open the .xlsx in Excel/LibreOffice to recalculate.</p>
</header>
<nav>{tabs}</nav>
<main>{sheets}</main>
<footer>Generated by scripts/render_matrix_html.py from scripts/build_master_service_matrix.py's output.</footer>
<script>
  document.querySelectorAll('nav button').forEach(btn => {{
    btn.addEventListener('click', () => {{
      document.querySelectorAll('nav button').forEach(b => b.classList.remove('active'));
      document.querySelectorAll('.sheet').forEach(s => s.classList.remove('active'));
      btn.classList.add('active');
      document.getElementById(btn.dataset.target).classList.add('active');
    }});
  }});
</script>
</body>
</html>
"""


_BUILD_SCRIPT = ROOT / "scripts" / "build_master_service_matrix.py"


def _load_header_fill_rgb() -> str:
    """Read HEADER_FILL's hex colour straight from build_master_service_matrix.py's
    source, rather than hardcoding a copy of it here. That script executes its
    workbook-building code at module level (no __main__ guard), so it can't be
    imported without re-running the whole build — parsing the source text is the
    cheap way to stay in sync if HEADER_FILL's value ever changes there."""
    src = _BUILD_SCRIPT.read_text(encoding="utf-8")
    m = re.search(
        r"HEADER_FILL\s*=\s*PatternFill\(\s*start_color\s*=\s*['\"]([0-9A-Fa-f]{6})['\"]", src
    )
    if not m:
        raise RuntimeError(f"Could not find HEADER_FILL definition in {_BUILD_SCRIPT}")
    return "00" + m.group(1).upper()


# Sheets don't all put their header row at row 1 (some have a title row, or a
# summary block, before it), so detecting the header by its actual styling is
# more robust than assuming a fixed row.
_HEADER_FILL_RGB = _load_header_fill_rgb()


def _is_header_row(row) -> bool:
    cells = [c for c in row if c.value is not None]
    if not cells:
        return False
    return all(
        c.fill and c.fill.start_color and c.fill.start_color.rgb == _HEADER_FILL_RGB for c in cells
    )


def _sheet_html(ws) -> str:
    rows_html = []
    for row in ws.iter_rows():
        tag = "th" if _is_header_row(row) else "td"
        attrs = ' scope="col"' if tag == "th" else ""
        cells = "".join(
            f"<{tag}{attrs}>{html.escape(str(c.value)) if c.value is not None else ''}</{tag}>"
            for c in row
        )
        rows_html.append(f"<tr>{cells}</tr>")
    return f"<table>{''.join(rows_html)}</table>"


def render(workbook_path: Path, out_dir: Path) -> None:
    wb = load_workbook(workbook_path, data_only=False)
    tabs = []
    sheets = []
    for i, name in enumerate(wb.sheetnames):
        slug = f"sheet-{i}"
        active = " active" if i == 0 else ""
        tabs.append(
            f'<button data-target="{slug}" class="{active.strip()}">{html.escape(name)}</button>'
        )
        sheets.append(f'<div id="{slug}" class="sheet{active}">{_sheet_html(wb[name])}</div>')

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index.html").write_text(
        PAGE_TEMPLATE.format(tabs="".join(tabs), sheets="".join(sheets)), encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="site", help="Output directory (default: site)")
    args = parser.parse_args()

    if not WORKBOOK.exists():
        print(f"MISSING: {WORKBOOK}")
        return 1

    out_dir = ROOT / args.out
    render(WORKBOOK, out_dir)
    print(f"Wrote {out_dir / 'index.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
