#!/usr/bin/env bash
# =============================================================================
# Trancendos Zero-Cost Bootstrap — brings the full free stack online
# =============================================================================
# What this does:
#   1. Checks Docker + compose are present
#   2. Generates a .env if none exists (with safe defaults)
#   3. Starts OSS foundations (n8n, Outline, Penpot, Qdrant, LiteLLM, etc.)
#   4. Starts core workers (infinity-auth, infinity-ai, gateway, etc.)
#   5. Reports health of all running services
#
# Zero-cost mandate: ALL services here are free/self-hosted.
#                    No credit card, no paid tier.
#
# Usage:
#   bash scripts/zero-cost-bootstrap.sh            # start everything
#   bash scripts/zero-cost-bootstrap.sh --minimal  # start only core workers
#   bash scripts/zero-cost-bootstrap.sh --status   # show status only
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERR]${NC}   $*" >&2; }
header(){ echo -e "\n${BOLD}${CYAN}══ $* ══${NC}\n"; }

MINIMAL=false
STATUS_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --minimal)    MINIMAL=true ;;
    --status)     STATUS_ONLY=true ;;
    --help|-h)
      echo "Usage: $0 [--minimal] [--status] [--help]"
      exit 0 ;;
  esac
done

# ─── Pre-flight checks ────────────────────────────────────────────
header "Pre-flight Checks"

check_cmd() {
  if command -v "$1" &>/dev/null; then
    ok "$1 found: $(command -v "$1")"
  else
    err "$1 not found — please install it first"
    exit 1
  fi
}

check_cmd docker
check_cmd openssl

# Detect docker compose (plugin v2 takes precedence over legacy standalone)
if docker compose version &>/dev/null 2>&1; then
  ok "docker compose (plugin) found"
  DOCKER_COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
  ok "docker-compose (standalone) found"
  DOCKER_COMPOSE="docker-compose"
else
  err "Neither 'docker compose' plugin nor 'docker-compose' found — please install Docker Compose"
  exit 1
fi

# ─── Generate .env if missing ─────────────────────────────────────
header "Environment Setup"

if [[ ! -f .env ]]; then
  warn ".env not found — generating from .env.example with safe defaults"
  if [[ -f .env.example ]]; then
    cp .env.example .env
  else
    cat > .env << ENVEOF
# Trancendos Zero-Cost .env — generated by zero-cost-bootstrap.sh
# Fill in API keys for free providers below. All are optional;
# the system falls back through the chain until Offline mode.

# ── Core ──────────────────────────────────────────────────────────
SECRET_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
ENVIRONMENT=development

# ── Free AI Providers (all optional — system degrades gracefully) ─
GROQ_API_KEY=                      # https://console.groq.com (free, no CC)
GOOGLE_GEMINI_API_KEY=             # https://aistudio.google.com (free, no CC)
GITHUB_TOKEN=                      # Any GitHub PAT — no special scopes needed
MISTRAL_API_KEY=                   # https://console.mistral.ai (free, no CC)
CEREBRAS_API_KEY=                  # https://cloud.cerebras.ai (free, no CC)
SAMBANOVA_API_KEY=                 # https://cloud.sambanova.ai (free, no CC)
OPENROUTER_API_KEY=                # https://openrouter.ai (free models)
HF_API_TOKEN=                      # https://huggingface.co/settings/tokens
DEEPSEEK_API_KEY=                  # https://platform.deepseek.com

# ── Local Ollama ──────────────────────────────────────────────────
OLLAMA_URL=http://localhost:11434

# ── LiteLLM Proxy ────────────────────────────────────────────────
LITELLM_MASTER_KEY=$(openssl rand -hex 24)

# ── OSS Foundations ──────────────────────────────────────────────
OSS_PG_PASSWORD=$(openssl rand -hex 16)
OUTLINE_SECRET_KEY=$(openssl rand -hex 32)
OUTLINE_UTILS_SECRET=$(openssl rand -hex 32)
OUTLINE_URL=http://localhost:3100
PENPOT_SECRET_KEY=$(openssl rand -hex 32)
PAPERLESS_SECRET_KEY=$(openssl rand -hex 32)
PAPERLESS_URL=http://localhost:8390
TYPESENSE_API_KEY=$(openssl rand -hex 16)
CALCOM_SECRET=$(openssl rand -hex 32)
CALCOM_ENCRYPTION_KEY=$(openssl rand -hex 32)
N8N_USER=admin
N8N_PASSWORD=$(openssl rand -hex 12)
GRAFANA_PASSWORD=$(openssl rand -hex 12)
ENVEOF
  fi
  ok ".env created"
else
  ok ".env already exists"
fi

if [[ "$STATUS_ONLY" == "true" ]]; then
  header "Service Status"
  $DOCKER_COMPOSE -f docker-compose.production.yml ps 2>/dev/null || true
  $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml ps 2>/dev/null || true
  exit 0
fi

# ─── Start OSS Foundations ────────────────────────────────────────
if [[ "$MINIMAL" == "false" ]]; then
  header "Starting OSS Foundations"

  info "Starting AI proxy (LiteLLM)..."
  $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml --profile ai-proxy up -d
  ok "LiteLLM proxy starting on :4000"

  info "Starting The Digital Grid (n8n)..."
  $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml --profile grid up -d
  ok "n8n starting on :5678"

  info "Starting Vector DB (Qdrant)..."
  $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml --profile vector up -d
  ok "Qdrant starting on :6333"

  info "Starting Search (Typesense)..."
  $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml --profile search up -d
  ok "Typesense starting on :8108"

  info "Starting The Observatory (Prometheus + Grafana)..."
  $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml --profile observatory up -d
  ok "Grafana starting on :3300, Prometheus on :9090"

  # Optional heavy services — skip if resource-constrained
  if [[ "${START_HEAVY:-false}" == "true" ]]; then
    info "Starting The Library (Outline)..."
    $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml --profile library up -d

    info "Starting DocUtari (Paperless-ngx)..."
    $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml --profile doc-utari up -d

    info "Starting Fabulousa (Penpot)..."
    $DOCKER_COMPOSE -f docker-compose.oss-foundations.yml --profile fabulousa up -d
  else
    warn "Heavy services (Outline, Paperless, Penpot) skipped."
    warn "Run START_HEAVY=true $0 to include them."
  fi
fi

# ─── Start Core Workers ───────────────────────────────────────────
header "Starting Core Workers"

info "Starting core platform workers..."
$DOCKER_COMPOSE up -d \
  infinity-auth \
  infinity-ws \
  infinity-ai \
  gateway-service \
  monitoring \
  queue-service \
  rate-limit-service \
  2>/dev/null || warn "Some core workers may need docker-compose.production.yml — run: make dev-api"

# ─── Health Summary ───────────────────────────────────────────────
header "Platform Health Summary"

check_service() {
  local name="$1"
  local url="$2"
  local port="$3"

  if curl -sf --max-time 5 "$url" &>/dev/null; then
    ok "${name} (${port}) — LIVE"
  else
    warn "${name} (${port}) — starting / not reachable yet"
  fi
}

sleep 5  # give containers a moment to bind ports

check_service "LiteLLM AI Proxy"     "http://localhost:4000/health"       ":4000"
check_service "n8n (Digital Grid)"   "http://localhost:5678/healthz"      ":5678"
check_service "Qdrant"               "http://localhost:6333/healthz"      ":6333"
check_service "Typesense"            "http://localhost:8108/health"       ":8108"
check_service "Prometheus"           "http://localhost:9090/-/healthy"    ":9090"
check_service "Grafana"              "http://localhost:3300/api/health"   ":3300"
check_service "FastAPI Backend"      "http://localhost:8000/health"       ":8000"
check_service "Infinity Auth"        "http://localhost:8005/health"       ":8005"

echo ""
info "Full status: docker compose -f docker-compose.oss-foundations.yml ps"
info "Logs:        docker compose -f docker-compose.oss-foundations.yml logs -f"
info "Stop all:    docker compose -f docker-compose.oss-foundations.yml down"
echo ""
ok "Zero-cost bootstrap complete. All free, all self-hosted."
