# src/security/falco_rules_generator.py
# Falco runtime security rules generator for the Trancendos platform.
#
# Generates YAML Falco rules from Cryptex threat patterns and built-in
# Tranc3-specific security policies.  Falco is free and open-source (Apache 2.0):
# https://falco.org/
#
# No paid external dependencies. Pure Python — uses stdlib only.
# All methods catch exceptions and return safe defaults; they never raise.

from __future__ import annotations

import logging
import os
import textwrap
from datetime import datetime, timezone
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# YAML serialisation (stdlib only — no pyyaml required)
# ---------------------------------------------------------------------------


def _yaml_str(value: str) -> str:
    """Minimal YAML scalar quoting for single-line strings."""
    # Quote if string contains special characters
    specials = (
        ":",
        "#",
        "{",
        "}",
        "[",
        "]",
        ",",
        "&",
        "*",
        "?",
        "|",
        "-",
        "<",
        ">",
        "=",
        "!",
        "%",
        "@",
        "`",
        "'",
        '"',
        "\n",
        "\\",
    )
    if any(c in value for c in specials) or not value:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def _yaml_list(items: List[str], indent: int = 4) -> str:
    pad = " " * indent
    return "\n".join(f"{pad}- {_yaml_str(item)}" for item in items)


# ---------------------------------------------------------------------------
# Rule templates
# ---------------------------------------------------------------------------

_FALCO_HEADER = """\
# Tranc3 Platform — Falco Runtime Security Rules
# Generated by FalcoRulesGenerator at {timestamp}
# Platform: Trancendos / Cryptex security engine
# Falco docs: https://falco.org/docs/rules/
#
# Load with: falco -r /etc/falco/rules.d/tranc3.yaml
---
"""

# Curated built-in lists / macros / rules for the Trancendos platform.
_BUILTIN_RULES = """\
# ── Lists ──────────────────────────────────────────────────────────────────

- list: tranc3_allowed_processes
  items: [python3, uvicorn, gunicorn, node, npm, sh, bash, sleep, curl, wget]

- list: tranc3_sensitive_dirs
  items: [/etc, /proc/sysrq-trigger, /proc/mem, /dev/mem, /boot]

- list: tranc3_secret_files
  items:
    - /etc/passwd
    - /etc/shadow
    - /etc/sudoers
    - /root/.ssh/id_rsa
    - /root/.ssh/authorized_keys
    - .env
    - .env.local
    - .env.production
    - secrets.json
    - credentials.json

- list: tranc3_privesc_binaries
  items: [sudo, su, setuid, chmod, chown, newgrp, pkexec, doas]

- list: tranc3_known_malware_tools
  items: [nc, ncat, netcat, nmap, masscan, sqlmap, hydra, john, hashcat, mimikatz]

- list: tranc3_cve_payload_patterns
  items:
    - "log4j:jndi"
    - "${jndi:"
    - "../../../../etc/passwd"
    - "eval(base64_decode"
    - "phpinfo()"
    - "system("
    - "exec("

# ── Macros ─────────────────────────────────────────────────────────────────

- macro: tranc3_container
  condition: container.id != host

- macro: tranc3_spawned_process
  condition: evt.type = execve and evt.dir = <

- macro: tranc3_file_write
  condition: evt.type in (open, openat) and evt.arg.flags contains O_WRONLY

- macro: tranc3_network_outbound
  condition: evt.type = connect and evt.arg.fd.type = ipv4

- macro: tranc3_sensitive_mount
  condition: evt.type = mount

- macro: tranc3_privileged_call
  condition: evt.type in (setuid, setgid, fchown, fchmod, chmod, chown)

# ── Rules ──────────────────────────────────────────────────────────────────

- rule: Tranc3 — Unexpected Process in Container
  desc: >
    A process not in the Tranc3 allowlist was spawned inside a container.
    This may indicate a container escape attempt or code injection.
  condition: >
    tranc3_container
    and tranc3_spawned_process
    and not proc.name in (tranc3_allowed_processes)
  output: >
    Unexpected process spawned in Tranc3 container
    (proc=%proc.name cmd=%proc.cmdline container=%container.name
     image=%container.image.repository user=%user.name)
  priority: WARNING
  tags: [tranc3, container, process]

- rule: Tranc3 — Python/Go Binary Writing to Sensitive Path
  desc: >
    A Python or Go process is writing to a sensitive system directory.
    This may indicate malicious payload delivery or privilege abuse.
  condition: >
    tranc3_file_write
    and proc.name in (python3, python, go)
    and (fd.directory in (tranc3_sensitive_dirs) or fd.name in (tranc3_secret_files))
  output: >
    Python/Go process writing to sensitive path
    (proc=%proc.name file=%fd.name user=%user.name container=%container.name)
  priority: ERROR
  tags: [tranc3, file, injection]

- rule: Tranc3 — Outbound Connection to Non-Allowlisted IP
  desc: >
    A container process is making an outbound TCP connection to an IP not in
    the known allowlist. This may indicate C2 callback or data exfiltration.
  condition: >
    tranc3_container
    and tranc3_network_outbound
    and not fd.sip in ("127.0.0.1", "::1")
    and not fd.sport in (80, 443, 8000, 8001, 8004, 8005, 8071, 11434)
  output: >
    Outbound connection to unexpected destination
    (proc=%proc.name dst=%fd.sip:%fd.sport container=%container.name user=%user.name)
  priority: WARNING
  tags: [tranc3, network, exfiltration]

- rule: Tranc3 — Privilege Escalation Attempt
  desc: >
    A process attempted a privilege escalation via setuid/setgid or launched
    a known privilege-escalation binary.
  condition: >
    (tranc3_privileged_call or proc.name in (tranc3_privesc_binaries))
    and user.name != root
  output: >
    Privilege escalation attempt detected
    (proc=%proc.name syscall=%evt.type user=%user.name container=%container.name)
  priority: CRITICAL
  tags: [tranc3, privesc, security]

- rule: Tranc3 — Secret File Access
  desc: >
    A process opened a known secret or credential file. Accessing /etc/shadow,
    .env files, or SSH private keys outside expected paths is suspicious.
  condition: >
    evt.type in (open, openat)
    and fd.name in (tranc3_secret_files)
    and not proc.name in (python3, uvicorn, gunicorn)
  output: >
    Secret file accessed
    (proc=%proc.name file=%fd.name user=%user.name container=%container.name)
  priority: ERROR
  tags: [tranc3, secrets, credential-access]

- rule: Tranc3 — Known Malware / Reconnaissance Tool
  desc: >
    A well-known attack tool (netcat, nmap, sqlmap, etc.) was executed.
    These are never expected inside Tranc3 production containers.
  condition: >
    tranc3_spawned_process
    and proc.name in (tranc3_known_malware_tools)
  output: >
    Known attack tool executed
    (tool=%proc.name cmd=%proc.cmdline user=%user.name container=%container.name)
  priority: CRITICAL
  tags: [tranc3, malware, attack-tool]

- rule: Tranc3 — CVE Exploitation Payload Detected
  desc: >
    A process argument or environment variable contains a known CVE exploitation
    pattern (Log4Shell JNDI, path traversal, PHP code injection, etc.).
  condition: >
    tranc3_spawned_process
    and (proc.args contains "${jndi:"
         or proc.args contains "../../../../etc/passwd"
         or proc.args contains "eval(base64_decode"
         or proc.args contains "phpinfo()")
  output: >
    CVE exploitation payload in process arguments
    (proc=%proc.name args=%proc.args user=%user.name container=%container.name)
  priority: CRITICAL
  tags: [tranc3, cve, exploitation]

- rule: Tranc3 — Sensitive Mount Operation
  desc: >
    A container attempted to mount a filesystem, which may indicate a container
    escape or attempt to access host storage.
  condition: >
    tranc3_container
    and tranc3_sensitive_mount
  output: >
    Unexpected mount operation in Tranc3 container
    (proc=%proc.name user=%user.name container=%container.name)
  priority: ERROR
  tags: [tranc3, container, escape]
"""


# ---------------------------------------------------------------------------
# Dynamic rule builder
# ---------------------------------------------------------------------------


def _rule_from_pattern(pattern: Dict[str, Any], sid_base: int = 100000) -> str:
    """
    Build a single Falco rule YAML block from a Cryptex threat pattern dict.

    Expected keys in ``pattern``:
        name (str)        — threat name
        description (str) — human-readable description
        severity (str)    — info/low/medium/high/critical
        pattern (str)     — regex or substring to match in proc args/cmdline
        tags (list[str])  — optional tags list
    """
    name = pattern.get("name", "Unnamed Threat Pattern")
    description = pattern.get("description", "Threat pattern from Cryptex")
    severity = pattern.get("severity", "medium").upper()
    raw_pattern = pattern.get("pattern", "")
    tags = pattern.get("tags", ["tranc3", "dynamic"])

    # Map Cryptex severity → Falco priority
    priority_map = {
        "INFO": "INFORMATIONAL",
        "LOW": "NOTICE",
        "MEDIUM": "WARNING",
        "HIGH": "ERROR",
        "CRITICAL": "CRITICAL",
    }
    priority = priority_map.get(severity, "WARNING")

    safe_name = f"Tranc3 — Dynamic: {name}"
    tag_list = ", ".join(tags)
    condition_pattern = raw_pattern.replace('"', '\\"') if raw_pattern else "never"
    condition = (
        f'tranc3_spawned_process and proc.cmdline contains "{condition_pattern}"'
        if raw_pattern
        else "never"
    )

    return textwrap.dedent(f"""\
        - rule: {_yaml_str(safe_name)}
          desc: {_yaml_str(description)}
          condition: >
            {condition}
          output: >
            Dynamic threat pattern match: {_yaml_str(name)}
            (proc=%proc.name cmd=%proc.cmdline user=%user.name container=%container.name)
          priority: {priority}
          tags: [{tag_list}]
        """)


# ---------------------------------------------------------------------------
# FalcoRulesGenerator
# ---------------------------------------------------------------------------


class FalcoRulesGenerator:
    """
    Falco runtime security rules generator for the Tranc3 / Cryptex platform.

    Generates YAML-formatted Falco rules files from:
    * Built-in Tranc3 rules (process allowlisting, privilege escalation,
      secret access, CVE payload patterns, container escape detection).
    * Dynamic rules derived from ``ThreatSignal`` patterns produced by
      the Cryptex threat detector.

    Usage
    -----
    >>> gen = FalcoRulesGenerator()
    >>> yaml_str = gen.generate_default_rules()
    >>> gen.save_rules("/etc/falco/rules.d/tranc3.yaml")

    All methods catch exceptions and return safe defaults; they never raise.
    """

    def __init__(self) -> None:
        self._generated_rules: str = ""
        self._extra_rules: List[str] = []

    # ── Public API ────────────────────────────────────────────────────────

    def generate_default_rules(self) -> str:
        """
        Return the built-in Tranc3 Falco rules as a YAML string.

        Covers:
        - Unexpected process spawning in containers
        - Python/Go binary writing to sensitive paths
        - Outbound connections to non-allowlisted IPs
        - Privilege escalation attempts
        - Secret file access (passwd, shadow, .env, etc.)
        - Known attack tool detection (netcat, sqlmap, …)
        - CVE exploitation payload signatures (Log4Shell, path traversal, …)
        - Unexpected mount operations (container escape indicator)

        Returns
        -------
        str — Valid Falco YAML content.
        """
        try:
            header = _FALCO_HEADER.format(timestamp=datetime.now(timezone.utc).isoformat())
            self._generated_rules = header + _BUILTIN_RULES
            return self._generated_rules
        except Exception as exc:  # noqa: BLE001
            logger.error("falco: generate_default_rules error: %s", exc)
            return ""

    def generate_rules(self, threat_patterns: List[Dict[str, Any]]) -> str:
        """
        Generate Falco rules from a list of Cryptex threat pattern dicts.

        Each dict should contain at minimum:
            ``name``, ``description``, ``severity``, ``pattern``

        The default built-in rules are always included first.

        Parameters
        ----------
        threat_patterns: List of threat-pattern dicts from Cryptex.

        Returns
        -------
        str — Complete Falco YAML content (builtins + dynamic rules).
        """
        try:
            base = self.generate_default_rules()
            if not threat_patterns:
                return base

            dynamic_blocks: List[str] = []
            for idx, pattern in enumerate(threat_patterns):
                try:
                    block = _rule_from_pattern(pattern, sid_base=200000 + idx)
                    dynamic_blocks.append(block)
                except Exception as inner:  # noqa: BLE001
                    logger.warning("falco: skipping pattern %d: %s", idx, inner)

            if not dynamic_blocks:
                return base

            separator = "\n# ── Dynamic rules from Cryptex threat patterns ──────────────────────────────\n\n"
            self._generated_rules = base + separator + "\n".join(dynamic_blocks)
            logger.info(
                "falco: generated %d dynamic rule(s) from %d pattern(s)",
                len(dynamic_blocks),
                len(threat_patterns),
            )
            return self._generated_rules
        except Exception as exc:  # noqa: BLE001
            logger.error("falco: generate_rules error: %s", exc)
            return self._generated_rules or ""

    def save_rules(self, output_path: str = "/etc/falco/rules.d/tranc3.yaml") -> bool:
        """
        Write the most recently generated rules to ``output_path``.

        Falls back to generating default rules if ``generate_rules`` /
        ``generate_default_rules`` has not been called yet.

        Parameters
        ----------
        output_path: Destination file path (must be writable).

        Returns
        -------
        True on success; False on any error.
        """
        try:
            rules = self._generated_rules or self.generate_default_rules()
            if not rules:
                logger.warning("falco: no rules to write")
                return False
            os.makedirs(
                os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True
            )
            with open(output_path, "w", encoding="utf-8") as fh:
                fh.write(rules)
            logger.info("falco: rules written to %s (%d bytes)", output_path, len(rules))
            return True
        except Exception as exc:  # noqa: BLE001
            logger.error("falco: save_rules error [%s]: %s", output_path, exc)
            return False

    def get_rule_count(self) -> int:
        """
        Return the number of Falco ``- rule:`` blocks in the last generated output.

        Returns
        -------
        int — rule count (0 if no rules have been generated yet).
        """
        try:
            content = self._generated_rules or self.generate_default_rules()
            return content.count("\n- rule:")
        except Exception as exc:  # noqa: BLE001
            logger.error("falco: get_rule_count error: %s", exc)
            return 0
