# src/security/suricata_rules_generator.py
# Suricata IDS/IPS rules generator for the Trancendos platform.
#
# Generates Suricata/Snort-compatible .rules files from Cryptex threat
# patterns and built-in Tranc3-specific signatures.
# Suricata is free and open-source (GPL-2.0): https://suricata.io/
#
# Output format: valid Suricata rules (SID-based, with metadata).
# No paid external dependencies. Pure Python — stdlib only.
# All methods catch exceptions and return safe defaults; they never raise.

from __future__ import annotations

import logging
import os
import textwrap
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# SID namespace
# ---------------------------------------------------------------------------

# Tranc3 local SID range: 9000000 – 9099999  (private/local use)
_SID_BASE = 9_000_000
_SID_CVE_BASE = 9_050_000
_SID_DYNAMIC_BASE = 9_080_000


# ---------------------------------------------------------------------------
# Rule builder helpers
# ---------------------------------------------------------------------------


def _clean(text: str) -> str:
    """Remove characters that would break a Suricata rule string option."""
    return text.replace('"', "'").replace(";", ",").replace("\n", " ")


def _metadata(rev: int = 1, tags: Optional[List[str]] = None) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    tag_str = ", ".join(tags or ["tranc3"])
    return f'metadata:created_at {ts}, updated_at {ts}, tag {tag_str}; rev:{rev};'


# ---------------------------------------------------------------------------
# Built-in Tranc3 rules
# ---------------------------------------------------------------------------

_HEADER_TEMPLATE = """\
# Tranc3 Platform — Suricata IDS/IPS Rules
# Generated by SuricataRulesGenerator at {timestamp}
# Platform: Trancendos / Cryptex security engine
# Suricata docs: https://docs.suricata.io/
#
# Load with (suricata.yaml):
#   rule-files:
#     - /etc/suricata/rules/tranc3.rules
#
# SID namespace: 9000000–9099999 (Tranc3 private range)
"""

# Built-in rules as a list of (comment, rule) tuples for readability.
# Templates use __META__ and __SID__ placeholders (not Python format strings)
# to avoid collisions with Suricata/regex braces in rule content.
_BUILTIN_RULES: List[tuple[str, str]] = [
    # ── SQL Injection ──────────────────────────────────────────────────────
    (
        "SQL Injection — UNION SELECT in HTTP body (POST)",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 SQL Injection UNION SELECT (POST)"; flow:established,to_server; http.method; content:"POST"; http.request_body; content:"UNION"; nocase; content:"SELECT"; nocase; distance:0; within:100; pcre:"/UNION\\s+(?:ALL\\s+)?SELECT/i"; __META__ sid:__SID__;)',
    ),
    (
        "SQL Injection — OR 1=1 pattern in URI",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 SQL Injection OR 1=1 in URI"; flow:established,to_server; http.uri; content:"or"; nocase; pcre:"/\\bor\\b\\s+\\d+=\\d+/i"; __META__ sid:__SID__;)',
    ),
    (
        "SQL Injection — DROP TABLE statement",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 SQL Injection DROP TABLE"; flow:established,to_server; http.request_body; content:"DROP"; nocase; content:"TABLE"; nocase; distance:0; within:20; __META__ sid:__SID__;)',
    ),
    (
        "SQL Injection — stacked queries (semicolon + SQL keyword)",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 SQL Injection stacked query"; flow:established,to_server; http.request_body; pcre:"/;\\s*(SELECT|INSERT|UPDATE|DELETE|DROP|EXEC)/i"; __META__ sid:__SID__;)',
    ),
    # ── XSS ───────────────────────────────────────────────────────────────
    (
        "XSS — <script> tag in HTTP body",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 XSS script tag in body"; flow:established,to_server; http.request_body; content:"<script"; nocase; __META__ sid:__SID__;)',
    ),
    (
        "XSS — javascript: URI in HTTP body",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 XSS javascript URI scheme"; flow:established,to_server; http.request_body; content:"javascript:"; nocase; __META__ sid:__SID__;)',
    ),
    (
        "XSS — onerror/onload event handler injection",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 XSS event handler injection"; flow:established,to_server; http.request_body; pcre:"/on(error|load|click|mouseover|focus)\\s*=/i"; __META__ sid:__SID__;)',
    ),
    (
        "XSS — <iframe> injection",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 XSS iframe injection"; flow:established,to_server; http.request_body; content:"<iframe"; nocase; __META__ sid:__SID__;)',
    ),
    # ── SSRF ──────────────────────────────────────────────────────────────
    (
        "SSRF — localhost in HTTP parameter",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 SSRF localhost target"; flow:established,to_server; http.request_body; content:"localhost"; nocase; __META__ sid:__SID__;)',
    ),
    (
        "SSRF — 127.0.0.1 in HTTP parameter",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 SSRF 127.0.0.1 target"; flow:established,to_server; http.request_body; content:"127.0.0.1"; __META__ sid:__SID__;)',
    ),
    (
        "SSRF — AWS metadata endpoint",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 SSRF AWS metadata endpoint"; flow:established,to_server; http.request_body; content:"169.254.169.254"; __META__ sid:__SID__;)',
    ),
    (
        "SSRF — internal RFC-1918 address in URI",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 SSRF RFC-1918 address in URI"; flow:established,to_server; http.uri; pcre:"/(?:192\\.168\\.|10\\.\\d+\\.|172\\.(?:1[6-9]|2\\d|3[01])\\.)/"; __META__ sid:__SID__;)',
    ),
    # ── JWT manipulation ───────────────────────────────────────────────────
    (
        'JWT — alg:none algorithm confusion',
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 JWT alg:none manipulation"; flow:established,to_server; http.header; content:"Authorization"; http.request_body; pcre:"/\\"alg\\"\\s*:\\s*\\"none\\"/i"; __META__ sid:__SID__;)',
    ),
    (
        "JWT — HS/RS algorithm confusion (RS256 → HS256)",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 JWT algorithm confusion RS256 to HS256"; flow:established,to_server; http.request_body; content:"HS256"; content:"RS256"; distance:0; within:200; __META__ sid:__SID__;)',
    ),
    # ── DDoS / Flood ───────────────────────────────────────────────────────
    (
        "HTTP Flood — excessive POST requests (threshold rule)",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 HTTP POST flood"; flow:established,to_server; http.method; content:"POST"; threshold:type threshold, track by_src, count 100, seconds 10; __META__ sid:__SID__;)',
    ),
    (
        "SYN Flood — high-rate TCP SYN to API port",
        'alert tcp any any -> $HTTP_SERVERS [8000,8001,8004,8005,8071] (msg:"TRANC3 SYN flood to API port"; flags:S,12; threshold:type threshold, track by_src, count 200, seconds 5; __META__ sid:__SID__;)',
    ),
    # ── Malicious User-Agents ──────────────────────────────────────────────
    (
        "Malicious UA — sqlmap scanner",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 sqlmap scanner user-agent"; flow:established,to_server; http.user_agent; content:"sqlmap"; nocase; __META__ sid:__SID__;)',
    ),
    (
        "Malicious UA — nikto scanner",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 Nikto scanner user-agent"; flow:established,to_server; http.user_agent; content:"Nikto"; nocase; __META__ sid:__SID__;)',
    ),
    (
        "Malicious UA — Masscan/Nmap",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 Mass scanner user-agent"; flow:established,to_server; http.user_agent; pcre:"/(?:masscan|nmap|zgrab|shodan)/i"; __META__ sid:__SID__;)',
    ),
    (
        "Malicious UA — curl with CVE exploit pattern in URI",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 curl CVE probe"; flow:established,to_server; http.user_agent; content:"curl"; http.uri; pcre:"/\\$\\{jndi:/"; __META__ sid:__SID__;)',
    ),
    # ── Path traversal ─────────────────────────────────────────────────────
    (
        "Path traversal — ../ in URI",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 path traversal ../"; flow:established,to_server; http.uri; content:"../"; __META__ sid:__SID__;)',
    ),
    (
        "Path traversal — URL-encoded ..%2F in URI",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 path traversal URL-encoded"; flow:established,to_server; http.uri; content:"..%2F"; nocase; __META__ sid:__SID__;)',
    ),
    # ── Command injection ──────────────────────────────────────────────────
    (
        "Command injection — shell metacharacter in body",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 command injection shell metachar"; flow:established,to_server; http.request_body; pcre:"/[;&|`]\\s*(?:ls|cat|rm|wget|curl|bash|sh|python|perl|nc|netcat)\\b/i"; __META__ sid:__SID__;)',
    ),
    (
        "Command injection — backtick command substitution",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 command injection backtick"; flow:established,to_server; http.request_body; content:"`"; pcre:"/`[^`]+`/"; __META__ sid:__SID__;)',
    ),
    # ── Log4Shell (CVE-2021-44228) ─────────────────────────────────────────
    (
        "CVE-2021-44228 Log4Shell JNDI lookup in URI",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 CVE-2021-44228 Log4Shell JNDI in URI"; flow:established,to_server; http.uri; content:"${jndi:"; nocase; __META__ sid:__SID__;)',
    ),
    (
        "CVE-2021-44228 Log4Shell JNDI lookup in body",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 CVE-2021-44228 Log4Shell JNDI in body"; flow:established,to_server; http.request_body; content:"${jndi:"; nocase; __META__ sid:__SID__;)',
    ),
    (
        "CVE-2021-44228 Log4Shell JNDI lookup in User-Agent",
        'alert http any any -> $HTTP_SERVERS any (msg:"TRANC3 CVE-2021-44228 Log4Shell JNDI in UA"; flow:established,to_server; http.user_agent; content:"${jndi:"; nocase; __META__ sid:__SID__;)',
    ),
]


# ---------------------------------------------------------------------------
# SuricataRulesGenerator
# ---------------------------------------------------------------------------


class SuricataRulesGenerator:
    """
    Suricata IDS/IPS rules generator for the Tranc3 / Cryptex platform.

    Generates Suricata/Snort-compatible ``.rules`` files from:
    * Built-in Tranc3 signatures covering SQL injection, XSS, SSRF, JWT
      manipulation, DDoS/flood, malicious user-agents, path traversal,
      command injection, and known CVE payloads (e.g. Log4Shell).
    * Dynamic rules derived from Cryptex ``ThreatSignal`` patterns.
    * Per-CVE rules via ``rule_from_cve()``.

    Usage
    -----
    >>> gen = SuricataRulesGenerator()
    >>> rules_str = gen.generate_default_rules()
    >>> gen.save_rules("/etc/suricata/rules/tranc3.rules")
    >>> cve_rule = gen.rule_from_cve("CVE-2021-44228", "${jndi:")

    All methods catch exceptions and return safe defaults; they never raise.
    """

    def __init__(self) -> None:
        self._generated_rules: str = ""
        self._sid_counter: int = _SID_BASE

    # ── SID management ────────────────────────────────────────────────────

    def _next_sid(self) -> int:
        sid = self._sid_counter
        self._sid_counter += 1
        return sid

    # ── Public API ────────────────────────────────────────────────────────

    def generate_default_rules(self) -> str:
        """
        Return the built-in Tranc3 Suricata rules as a ``.rules`` string.

        Covers:
        - SQL injection (UNION SELECT, OR 1=1, DROP TABLE, stacked queries)
        - XSS (script tags, javascript: URI, event handlers, iframes)
        - SSRF (localhost, 127.0.0.1, AWS metadata, RFC-1918 ranges)
        - JWT manipulation (alg:none, RS256→HS256 confusion)
        - DDoS / flood (HTTP POST flood, SYN flood)
        - Malicious user-agents (sqlmap, Nikto, Masscan, Nmap)
        - Path traversal (../, ..%2F)
        - Command injection (shell metacharacters, backtick substitution)
        - Log4Shell / CVE-2021-44228

        Returns
        -------
        str — Valid Suricata .rules content.
        """
        try:
            self._sid_counter = _SID_BASE
            timestamp = datetime.now(timezone.utc).isoformat()
            lines: List[str] = [_HEADER_TEMPLATE.format(timestamp=timestamp), ""]

            for comment, template in _BUILTIN_RULES:
                sid = self._next_sid()
                meta = _metadata(rev=1, tags=["tranc3", "builtin"])
                rule = template.replace("__META__", meta).replace("__SID__", str(sid))
                lines.append(f"# {comment}")
                lines.append(rule)
                lines.append("")

            self._generated_rules = "\n".join(lines)
            logger.info(
                "suricata: generated %d built-in rules (SID %d–%d)",
                len(_BUILTIN_RULES),
                _SID_BASE,
                self._sid_counter - 1,
            )
            return self._generated_rules
        except Exception as exc:  # noqa: BLE001
            logger.error("suricata: generate_default_rules error: %s", exc)
            return ""

    def generate_rules(self, threat_patterns: List[Dict[str, Any]]) -> str:
        """
        Generate Suricata rules from a list of Cryptex threat pattern dicts.

        Each dict should contain at minimum:
            ``name``        — threat name (str)
            ``description`` — description (str)
            ``severity``    — info/low/medium/high/critical (str)
            ``pattern``     — content pattern to match (str)
            ``direction``   — "request" or "response" (str, optional)

        Built-in rules are always included first.

        Parameters
        ----------
        threat_patterns: List of threat-pattern dicts from Cryptex.

        Returns
        -------
        str — Complete Suricata .rules content (builtins + dynamic rules).
        """
        try:
            base = self.generate_default_rules()
            if not threat_patterns:
                return base

            self._sid_counter = _SID_DYNAMIC_BASE
            dynamic_lines: List[str] = [
                "",
                "# ── Dynamic rules from Cryptex threat patterns ──────────────────────────────",
                "",
            ]
            count = 0
            for idx, pattern in enumerate(threat_patterns):
                try:
                    rule = self._rule_from_pattern(pattern)
                    if rule:
                        dynamic_lines.append(
                            f"# Dynamic[{idx}]: {pattern.get('name', 'unknown')}"
                        )
                        dynamic_lines.append(rule)
                        dynamic_lines.append("")
                        count += 1
                except Exception as inner:  # noqa: BLE001
                    logger.warning("suricata: skipping pattern %d: %s", idx, inner)

            self._generated_rules = base + "\n".join(dynamic_lines)
            logger.info(
                "suricata: appended %d dynamic rule(s) from %d pattern(s)",
                count,
                len(threat_patterns),
            )
            return self._generated_rules
        except Exception as exc:  # noqa: BLE001
            logger.error("suricata: generate_rules error: %s", exc)
            return self._generated_rules or ""

    def rule_from_cve(
        self,
        cve_id: str,
        payload_pattern: Optional[str] = None,
    ) -> str:
        """
        Generate a Suricata rule targeting a specific CVE.

        Parameters
        ----------
        cve_id:          CVE identifier (e.g. "CVE-2021-44228").
        payload_pattern: Optional content string to match in HTTP body/URI.
                         If omitted, a generic probe-detection rule is created.

        Returns
        -------
        str — Single Suricata rule line; empty string on error.
        """
        try:
            sid = _SID_CVE_BASE + abs(hash(cve_id)) % 10000
            meta = _metadata(rev=1, tags=["tranc3", "cve", cve_id.lower()])
            safe_cve = _clean(cve_id)
            safe_msg = f"TRANC3 {safe_cve} exploit attempt"

            if payload_pattern:
                safe_payload = _clean(payload_pattern)
                # Match in both URI and body
                rule = (
                    f'alert http any any -> $HTTP_SERVERS any '
                    f'(msg:"{safe_msg}"; flow:established,to_server; '
                    f'http.request_body; content:"{safe_payload}"; nocase; '
                    f'__META__ sid:__SID__;)'
                )
            else:
                # Generic: alert on any request referencing the CVE ID string
                # (e.g., scanners that include CVE IDs in their probes)
                rule = (
                    f'alert http any any -> $HTTP_SERVERS any '
                    f'(msg:"{safe_msg} generic probe"; flow:established,to_server; '
                    f'http.uri; content:"{safe_cve}"; nocase; '
                    f'__META__ sid:__SID__;)'
                )

            logger.debug("suricata: generated rule for %s (SID %d)", cve_id, sid)
            return rule
        except Exception as exc:  # noqa: BLE001
            logger.error("suricata: rule_from_cve error [%s]: %s", cve_id, exc)
            return ""

    def save_rules(
        self, output_path: str = "/etc/suricata/rules/tranc3.rules"
    ) -> bool:
        """
        Write the most recently generated rules to ``output_path``.

        Generates default rules if none have been produced yet.

        Parameters
        ----------
        output_path: Destination file path (must be writable).

        Returns
        -------
        True on success; False on any error.
        """
        try:
            rules = self._generated_rules or self.generate_default_rules()
            if not rules:
                logger.warning("suricata: no rules to write")
                return False
            dir_path = os.path.dirname(output_path)
            if dir_path:
                os.makedirs(dir_path, exist_ok=True)
            with open(output_path, "w", encoding="utf-8") as fh:
                fh.write(rules)
            logger.info(
                "suricata: rules written to %s (%d bytes)", output_path, len(rules)
            )
            return True
        except Exception as exc:  # noqa: BLE001
            logger.error("suricata: save_rules error [%s]: %s", output_path, exc)
            return False

    # ── Internal helpers ──────────────────────────────────────────────────

    def _rule_from_pattern(self, pattern: Dict[str, Any]) -> str:
        """Build a single Suricata rule from a Cryptex threat pattern dict."""
        name = _clean(pattern.get("name", "Unknown"))
        raw = _clean(pattern.get("pattern", ""))
        severity = pattern.get("severity", "medium").lower()
        tags = pattern.get("tags", ["tranc3", "dynamic"])

        if not raw:
            return ""

        # Map severity to Suricata action
        action = "alert"  # Suricata default — log, don't drop

        sid = self._next_sid()
        meta = _metadata(rev=1, tags=tags)
        msg = f"TRANC3 Dynamic: {name}"

        return (
            f'{action} http any any -> $HTTP_SERVERS any '
            f'(msg:"{msg}"; flow:established,to_server; '
            f'http.request_body; content:"{raw}"; nocase; '
            f'__META__ sid:__SID__;)'
        )
