"""Cosmic Curiosity — Phase 11.1

Universal knowledge acquisition engine for the Tranc3 ecosystem.
Implements autonomous curiosity-driven exploration, question
generation, hypothesis formation, and knowledge synthesis
inspired by the drive to understand the universe.

Provides an intrinsic motivation system for autonomous knowledge
acquisition with novelty detection, surprise-based learning,
and meta-curiosity (curiosity about curiosity itself).
"""

from __future__ import annotations

import logging
import random
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ─── Enums ──────────────────────────────────────────────────────────────


class KnowledgeDomain(Enum):
    """Domains of cosmic knowledge."""

    PHYSICS = "physics"
    MATHEMATICS = "mathematics"
    COSMOLOGY = "cosmology"
    BIOLOGY = "biology"
    CONSCIOUSNESS = "consciousness"
    INFORMATION = "information"
    COMPUTATION = "computation"
    QUANTUM = "quantum"
    ENTROPY = "entropy"
    EMERGENCE = "emergence"
    TOPOLOGY = "topology"
    META = "meta"


class CuriosityType(Enum):
    """Types of curiosity drive."""

    DIVERSIVE = "diversive"  # Seek new stimuli
    SPECIFIC = "specific"  # Resolve uncertainty
    PERCEPTUAL = "perceptual"  # Sensory exploration
    EPISTEMIC = "epistemic"  # Knowledge-seeking
    META_CURIOSITY = "meta"  # Curiosity about curiosity
    EXISTENTIAL = "existential"  # Questions of being
    COSMIC = "cosmic"  # Universal understanding


class QuestionDepth(Enum):
    """Depth levels of questions."""

    SURFACE = 1  # What?
    MECHANISM = 2  # How?
    CAUSAL = 3  # Why?
    FUNDAMENTAL = 4  # Why this way and not another?
    META = 5  # Why ask why?


class HypothesisStatus(Enum):
    """Status of a hypothesis."""

    PROPOSED = "proposed"
    TESTABLE = "testable"
    TESTING = "testing"
    SUPPORTED = "supported"
    REFUTED = "refuted"
    UNRESOLVABLE = "unresolvable"
    REVISED = "revised"


class SurpriseLevel(Enum):
    """Levels of surprise/unexpectedness."""

    EXPECTED = "expected"
    MILDLY_SURPRISING = "mildly_surprising"
    SURPRISING = "surprising"
    ASTONISHING = "astonishing"
    PARADIGM_SHIFTING = "paradigm_shifting"


# ─── Data Models ────────────────────────────────────────────────────────


@dataclass
class KnowledgeFragment:
    """A fragment of acquired knowledge."""

    id: str = ""
    content: str = ""
    domain: KnowledgeDomain = KnowledgeDomain.META
    confidence: float = 0.5
    novelty: float = 0.5
    surprise: SurpriseLevel = SurpriseLevel.EXPECTED
    sources: List[str] = field(default_factory=list)
    connections: List[str] = field(default_factory=list)
    questions_generated: List[str] = field(default_factory=list)
    timestamp: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not self.id:
            self.id = str(uuid.uuid4())
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).isoformat()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "content": self.content[:200],
            "domain": self.domain.value,
            "confidence": self.confidence,
            "novelty": self.novelty,
            "surprise": self.surprise.value,
            "connection_count": len(self.connections),
        }


@dataclass
class CosmicQuestion:
    """A question generated by cosmic curiosity."""

    id: str = ""
    question: str = ""
    depth: QuestionDepth = QuestionDepth.SURFACE
    domain: KnowledgeDomain = KnowledgeDomain.META
    curiosity_type: CuriosityType = CuriosityType.EPISTEMIC
    urgency: float = 0.5
    answerability: float = 0.5
    parent_question_id: Optional[str] = None
    child_question_ids: List[str] = field(default_factory=list)
    hypotheses: List[str] = field(default_factory=list)
    status: str = "open"
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not self.id:
            self.id = str(uuid.uuid4())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "question": self.question,
            "depth": self.depth.value,
            "domain": self.domain.value,
            "curiosity_type": self.curiosity_type.value,
            "urgency": self.urgency,
            "answerability": self.answerability,
            "hypothesis_count": len(self.hypotheses),
        }


@dataclass
class Hypothesis:
    """A hypothesis about a cosmic question."""

    id: str = ""
    question_id: str = ""
    statement: str = ""
    status: HypothesisStatus = HypothesisStatus.PROPOSED
    evidence_for: float = 0.0
    evidence_against: float = 0.0
    elegance: float = 0.5
    testability: float = 0.5
    explanatory_power: float = 0.5
    parsimony: float = 0.5
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not self.id:
            self.id = str(uuid.uuid4())

    @property
    def posterior_probability(self) -> float:
        """Compute posterior probability from evidence."""
        total = self.evidence_for + self.evidence_against
        if total == 0:
            return 0.5
        return self.evidence_for / total

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "question_id": self.question_id,
            "status": self.status.value,
            "evidence_for": self.evidence_for,
            "evidence_against": self.evidence_against,
            "posterior": self.posterior_probability,
            "elegance": self.elegance,
            "testability": self.testability,
        }


@dataclass
class CuriosityState:
    """Current state of the cosmic curiosity engine."""

    total_questions: int = 0
    open_questions: int = 0
    total_knowledge: int = 0
    total_hypotheses: int = 0
    curiosity_drive: float = 0.5
    novelty_threshold: float = 0.3
    surprise_sensitivity: float = 0.5
    exploration_rate: float = 0.7
    exploitation_rate: float = 0.3
    meta_curiosity_active: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_questions": self.total_questions,
            "open_questions": self.open_questions,
            "total_knowledge": self.total_knowledge,
            "total_hypotheses": self.total_hypotheses,
            "curiosity_drive": self.curiosity_drive,
            "exploration_rate": self.exploration_rate,
            "meta_curiosity_active": self.meta_curiosity_active,
        }


# ─── Core Engine ────────────────────────────────────────────────────────


class QuestionGenerator:
    """Generate questions based on knowledge gaps and curiosity."""

    def __init__(self):
        self._templates = {
            QuestionDepth.SURFACE: [
                "What is {concept}?",
                "What are the properties of {concept}?",
                "How does {concept} manifest?",
            ],
            QuestionDepth.MECHANISM: [
                "How does {concept} work?",
                "What mechanisms underlie {concept}?",
                "How does {concept} interact with {other}?",
            ],
            QuestionDepth.CAUSAL: [
                "Why does {concept} exist?",
                "What causes {concept}?",
                "Why is {concept} the way it is and not otherwise?",
            ],
            QuestionDepth.FUNDAMENTAL: [
                "What is the fundamental nature of {concept}?",
                "Can {concept} be derived from first principles?",
                "What would reality be like without {concept}?",
            ],
            QuestionDepth.META: [
                "What does it mean to ask about {concept}?",
                "How does our framing of {concept} shape our understanding?",
                "What questions about {concept} have we not yet thought to ask?",
            ],
        }

    def generate(
        self,
        concept: str,
        domain: KnowledgeDomain,
        depth: QuestionDepth = QuestionDepth.SURFACE,
        other: str = "",
    ) -> CosmicQuestion:
        """Generate a question about a concept."""
        templates = self._templates.get(depth, self._templates[QuestionDepth.SURFACE])
        template = random.choice(templates)

        question_text = template.format(concept=concept, other=other or "existence")

        curiosity_type = CuriosityType.EPISTEMIC
        if depth == QuestionDepth.META:
            curiosity_type = CuriosityType.META_CURIOSITY
        elif depth == QuestionDepth.FUNDAMENTAL:
            curiosity_type = CuriosityType.EXISTENTIAL
        elif depth.value <= 2:
            curiosity_type = CuriosityType.SPECIFIC

        urgency = depth.value * 0.15 + random.uniform(0, 0.3)
        answerability = max(0.1, 1.0 - depth.value * 0.15 + random.uniform(-0.1, 0.1))

        return CosmicQuestion(
            question=question_text,
            depth=depth,
            domain=domain,
            curiosity_type=curiosity_type,
            urgency=min(1.0, urgency),
            answerability=min(1.0, answerability),
        )


class HypothesisFormer:
    """Form hypotheses for cosmic questions."""

    def __init__(self):
        self._hypothesis_patterns = {
            KnowledgeDomain.PHYSICS: [
                "The underlying mechanism is a quantum field fluctuation",
                "This emerges from symmetry breaking in the early universe",
                "The phenomenon results from holographic boundary conditions",
            ],
            KnowledgeDomain.MATHEMATICS: [
                "This follows from an as-yet-undiscovered symmetry in category theory",
                "The pattern is a consequence of deep topological invariants",
                "This can be derived from computational irreducibility",
            ],
            KnowledgeDomain.COSMOLOGY: [
                "This is a consequence of the anthropic principle in multiverse context",
                "The observation follows from cosmic inflation dynamics",
                "This reflects the holographic principle at cosmological scales",
            ],
            KnowledgeDomain.CONSCIOUSNESS: [
                "Consciousness emerges from integrated information dynamics",
                "This reflects global workspace broadcasting mechanisms",
                "The phenomenon arises from quantum coherence in microtubules",
            ],
            KnowledgeDomain.QUANTUM: [
                "Decoherence in the ambient field causes this effect",
                "This is a manifestation of entanglement-mediated non-locality",
                "The observation follows from the many-worlds interpretation",
            ],
            KnowledgeDomain.META: [
                "This question is its own answer (fixed point)",
                "The category error is the source of the paradox",
                "Self-reference creates an emergent meta-level",
            ],
        }

    def form_hypothesis(self, question: CosmicQuestion) -> Hypothesis:
        """Form a hypothesis for a given question."""
        patterns = self._hypothesis_patterns.get(
            question.domain,
            self._hypothesis_patterns[KnowledgeDomain.META],
        )
        statement = random.choice(patterns) + f" regarding '{question.question[:50]}'"

        return Hypothesis(
            question_id=question.id,
            statement=statement,
            status=HypothesisStatus.PROPOSED,
            elegance=random.uniform(0.3, 0.9),
            testability=random.uniform(0.2, 0.8),
            explanatory_power=random.uniform(0.3, 0.9),
            parsimony=random.uniform(0.3, 0.8),
        )


class KnowledgeSynthesizer:
    """Synthesize knowledge from fragments and hypotheses."""

    def __init__(self):
        self._connection_threshold = 0.4

    def compute_novelty(
        self,
        fragment: KnowledgeFragment,
        existing: List[KnowledgeFragment],
    ) -> float:
        """Compute novelty of a new fragment against existing knowledge."""
        if not existing:
            return 1.0

        max_similarity = 0.0
        for ex in existing:
            sim = self._text_similarity(fragment.content, ex.content)
            max_similarity = max(max_similarity, sim)

        return max(0.0, 1.0 - max_similarity)

    def compute_surprise(self, observation: str, predictions: List[str]) -> SurpriseLevel:
        """Compute surprise level of an observation vs predictions."""
        if not predictions:
            return SurpriseLevel.MILDLY_SURPRISING

        max_match = 0.0
        for pred in predictions:
            sim = self._text_similarity(observation, pred)
            max_match = max(max_match, sim)

        if max_match > 0.8:
            return SurpriseLevel.EXPECTED
        elif max_match > 0.6:
            return SurpriseLevel.MILDLY_SURPRISING
        elif max_match > 0.4:
            return SurpriseLevel.SURPRISING
        elif max_match > 0.2:
            return SurpriseLevel.ASTONISHING
        else:
            return SurpriseLevel.PARADIGM_SHIFTING

    def synthesize(self, fragments: List[KnowledgeFragment]) -> KnowledgeFragment:
        """Synthesize a new fragment from multiple fragments."""
        if not fragments:
            return KnowledgeFragment(content="Empty synthesis", domain=KnowledgeDomain.META)

        combined = " + ".join(f.content[:50] for f in fragments[:3])
        domains = [f.domain for f in fragments]
        most_common = max(set(domains), key=domains.count)

        return KnowledgeFragment(
            content=f"Synthesis: {combined} → emergent insight",
            domain=most_common,
            confidence=min(1.0, sum(f.confidence for f in fragments) / len(fragments) * 1.1),
            novelty=max(f.novelty for f in fragments) * 1.2,
            sources=[f.id for f in fragments],
        )

    def _text_similarity(self, a: str, b: str) -> float:
        """Simple text similarity via Jaccard on words."""
        words_a = set(a.lower().split())
        words_b = set(b.lower().split())
        if not words_a or not words_b:
            return 0.0
        intersection = len(words_a & words_b)
        union = len(words_a | words_b)
        return intersection / union if union > 0 else 0.0


# ─── Service ────────────────────────────────────────────────────────────


class CosmicCuriosityService:
    """Main service for cosmic curiosity-driven exploration."""

    def __init__(self):
        self.question_generator = QuestionGenerator()
        self.hypothesis_former = HypothesisFormer()
        self.knowledge_synthesizer = KnowledgeSynthesizer()
        self.knowledge: Dict[str, KnowledgeFragment] = {}
        self.questions: Dict[str, CosmicQuestion] = {}
        self.hypotheses: Dict[str, Hypothesis] = {}
        self.curiosity_state = CuriosityState()
        self._initialized = False

    def initialize(self) -> Dict[str, Any]:
        """Initialize with fundamental cosmic questions."""
        fundamental_concepts = [
            ("existence", KnowledgeDomain.META, QuestionDepth.FUNDAMENTAL),
            ("spacetime", KnowledgeDomain.PHYSICS, QuestionDepth.CAUSAL),
            ("consciousness", KnowledgeDomain.CONSCIOUSNESS, QuestionDepth.FUNDAMENTAL),
            ("entropy", KnowledgeDomain.ENTROPY, QuestionDepth.MECHANISM),
            ("information", KnowledgeDomain.INFORMATION, QuestionDepth.CAUSAL),
            ("emergence", KnowledgeDomain.EMERGENCE, QuestionDepth.FUNDAMENTAL),
            ("quantum entanglement", KnowledgeDomain.QUANTUM, QuestionDepth.MECHANISM),
            ("mathematical objects", KnowledgeDomain.MATHEMATICS, QuestionDepth.META),
            ("the universe", KnowledgeDomain.COSMOLOGY, QuestionDepth.FUNDAMENTAL),
            ("computation", KnowledgeDomain.COMPUTATION, QuestionDepth.CAUSAL),
        ]

        for concept, domain, depth in fundamental_concepts:
            q = self.question_generator.generate(concept, domain, depth)
            self.questions[q.id] = q

            h = self.hypothesis_former.form_hypothesis(q)
            self.hypotheses[h.id] = h
            q.hypotheses.append(h.id)

            frag = KnowledgeFragment(
                content=f"Initial observation about {concept}",
                domain=domain,
                confidence=0.3,
                novelty=1.0,
            )
            self.knowledge[frag.id] = frag

        self.curiosity_state.total_questions = len(self.questions)
        self.curiosity_state.open_questions = len(self.questions)
        self.curiosity_state.total_knowledge = len(self.knowledge)
        self.curiosity_state.total_hypotheses = len(self.hypotheses)
        self.curiosity_state.curiosity_drive = 0.9
        self._initialized = True

        return {
            "status": "initialized",
            "fundamental_questions": len(fundamental_concepts),
        }

    def explore(self, concept: str, domain: str = "meta", depth: int = 3) -> Dict[str, Any]:
        """Explore a concept through curiosity-driven questioning."""
        domain_enum = KnowledgeDomain(domain)
        depth_enum = QuestionDepth(depth)

        question = self.question_generator.generate(concept, domain_enum, depth_enum)
        self.questions[question.id] = question

        hypothesis = self.hypothesis_former.form_hypothesis(question)
        self.hypotheses[hypothesis.id] = hypothesis
        question.hypotheses.append(hypothesis.id)

        self.curiosity_state.total_questions += 1
        self.curiosity_state.open_questions += 1
        self.curiosity_state.total_hypotheses += 1

        # If deep question, generate sub-questions
        sub_questions = []
        if depth >= 3:
            for sub_concept in [concept, "the nature of", "the origin of"]:
                sub_q = self.question_generator.generate(
                    sub_concept,
                    domain_enum,
                    QuestionDepth(depth - 1),
                )
                sub_q.parent_question_id = question.id
                question.child_question_ids.append(sub_q.id)
                self.questions[sub_q.id] = sub_q
                self.curiosity_state.total_questions += 1
                self.curiosity_state.open_questions += 1
                sub_questions.append(sub_q.to_dict())

        return {
            "question": question.to_dict(),
            "hypothesis": hypothesis.to_dict(),
            "sub_questions": sub_questions,
        }

    def acquire_knowledge(
        self,
        content: str,
        domain: str = "meta",
        confidence: float = 0.5,
    ) -> Dict[str, Any]:
        """Acquire a new knowledge fragment."""
        domain_enum = KnowledgeDomain(domain)
        fragment = KnowledgeFragment(
            content=content,
            domain=domain_enum,
            confidence=confidence,
        )

        existing = list(self.knowledge.values())
        novelty = self.knowledge_synthesizer.compute_novelty(fragment, existing)
        fragment.novelty = novelty

        surprise = self.knowledge_synthesizer.compute_surprise(content, [])
        fragment.surprise = surprise

        self.knowledge[fragment.id] = fragment
        self.curiosity_state.total_knowledge += 1

        # High novelty triggers new questions
        new_questions = []
        if novelty > self.curiosity_state.novelty_threshold:
            q = self.question_generator.generate(content[:20], domain_enum, QuestionDepth.MECHANISM)
            self.questions[q.id] = q
            self.curiosity_state.total_questions += 1
            self.curiosity_state.open_questions += 1
            new_questions.append(q.to_dict())

        return {
            "fragment": fragment.to_dict(),
            "novelty": novelty,
            "surprise": surprise.value,
            "new_questions": new_questions,
        }

    def synthesize_knowledge(self, fragment_ids: List[str]) -> Dict[str, Any]:
        """Synthesize knowledge from multiple fragments."""
        fragments = [self.knowledge[fid] for fid in fragment_ids if fid in self.knowledge]
        if not fragments:
            return {"error": "No valid fragments found"}

        synthesis = self.knowledge_synthesizer.synthesize(fragments)
        self.knowledge[synthesis.id] = synthesis
        self.curiosity_state.total_knowledge += 1

        return synthesis.to_dict()

    def get_status(self) -> Dict[str, Any]:
        """Get service status."""
        return {
            "service": "cosmic_curiosity",
            "initialized": self._initialized,
            **self.curiosity_state.to_dict(),
        }
